apiVersion: v1
kind: Secret
metadata:
    name: hass-mcp-secret
    namespace: llm
type: Opaque
stringData:
    HA_URL: ENC[AES256_GCM,data:wJHlu4h52L3wxg1f7zEGAdpPMuMul5Z8yIQZtFB7O0WJrUfQA7CvhVA/zHCv2dg=,iv:ebjAbxD4+n81uVDy0D+PkXgvVhM9EPhIbzah/yJrtuI=,tag:MFLK9brvIvnvZLb/lY+Qlw==,type:str]
    HA_TOKEN: ENC[AES256_GCM,data:sXKkymzo6wfxOGT6anuHHCs9B6tZdV/jV/laDE3VEJJWixhBsgHxuOeMurkboGDcW2UyDTeyuEXUJyHl8vfpzIdEfdxFVkB0jhtAQFqDTTO6Aclhi6u+xdg9AbSoOWTjsN5gyUMSpmC81vUghZuVJxV+Sa2oc98kZw9rqGvyGmJqVkb++3tUqse9XRInCPUSbZCWCXDw1iazuqwkXBakwDVfFXZqGGEmnPAAXp0o3q1+h0VjSbWh,iv:Ac1NqQtuZOg7vyXl7ux/Z4AviWCJOQ+Wqo/0EXJUEmM=,tag:XFFhRGlWTrUHOjhBsFQRPQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ckJlbzBmdWJidzlFMkh4
            QllNMVNJckZBSkYrWVJRVi9aZGV5T1NYVEZzCkVvRDR5SU1IM1NuQUZRYWJObzZN
            WStLd2YycjMxNk9XTnJDK0ZnRDNHVTQKLS0tIFFwSlh1dXlGU1JrVkhBTFAzREJz
            UnFiYWZwdVlFaWRLUk0zMjZrTG9ZbkUKlagZKv80r5LjOZMftaYSF3CBQIIOjbmD
            9PGAB6KiYF5XhNd8A4p6uc8P9P6EayOsDZnwiRAXA1ACV4ai2kanCA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IFJTSlJydyBBamJkMEFr
            RmNEeUFqazFWRE9LcWs5bGpMMFRSc3ZzNU9TMytWVVZxWDljQgovNThuZFF4a0RL
            WnZ6UFk2WXpIeGVBMHgwRG9JWTFrYWxGZk9NU3hkWHdRCi0tLSBEa3lUZzRMNDF5
            UGQwN0h6S0dzOGFGQVBWM0c0dnZwWjZLUlgxbHcwdVBrCofXeiKdchPHpr59R5Fd
            ONcmx9o8GX9G3acFaWfrVtfrDl+B3lqyBSGH2LVj+NzMW3ZuGpwSXIZ/zhWF0BHy
            kOY=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qgn7ll64pzy4wd64h85xxq386cexa98676zw4raej9rvxl822p782xrjn5z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDY0dUwvQSBBeXFXYXRY
            VFBiQ3dxN2RJbjdZNGMrcS91YXhXNmpFelowR3FlUDlKdEdBZApkVmlnbzJMQ2ln
            R01VZyt4SDJ2TzdCOFA5ZjZtOUtPU1A4UDRqcEh0U0RBCi0tLSBBc0pDbzRMdzlw
            YS93TCtGV2lEOHBWTEFmRVk1Y0pnRTNIdWExcG5iKzJnCjOQNYI9NoXkkbFt9thc
            5UomiazlIxG2oX87HJ+SN63E79qLl9OU6ZS7Hzk0rS4bbg/AQN0kIMi/y3fPcHlv
            gzQ=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtvpgtvl83qxn5kferysjnzrt0zs2svfygeuvqznlupmvtepcwv37v7pace
    encrypted_regex: ^(stringData)$
    lastmodified: "2025-12-04T11:38:24Z"
    mac: ENC[AES256_GCM,data:R1ezWWLgKhx4p/7R18YZeZd3PTOtZ1ugjYckhaOPxgXrNFkVMTAjnnbSnEI8imkrudVCX84p3VocJRMql270j8uovBpih3cPjf0e4DKzVMsUC7fY3+z1li4XFIPnQWCtj7LkHTGN4kYf4xGuaPRbNqaAHNzzVfaebi4mjI0XRPE=,iv:tzJcVbk9TUhnMqVRV/qexVaWkoRK+jpJFYKf6cmLUTE=,tag:WzQvY34qKNYE/o5azx5o7A==,type:str]
    version: 3.9.0
