---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: unifi-egress-to-local-network
  namespace: redirect
spec:
  podSelector:
    matchLabels:
      app: unifi-proxy
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 192.168.1.1/32
      ports:
      - protocol: TCP
        port: 80
      - protocol: TCP
        port: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-proxy
  namespace: redirect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifi-proxy
  template:
    metadata:
      labels:
        app: unifi-proxy
    spec:
      containers:
      - name: nginx
        image: nginx:1.29-perl
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-config
        configMap:
          name: unifi-proxy-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: unifi-proxy-config
  namespace: redirect
data:
  default.conf: |
    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

    server {
        listen 80;

        location / {
            proxy_pass https://192.168.1.1;

            # UniFi uses a self-signed cert
            proxy_ssl_verify off;
            proxy_ssl_server_name on;

            # UniFi expects its IP as Host header
            proxy_set_header Host 192.168.1.1;

            # Standard forwarding headers
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;

            # WebSocket support (required for UniFi UI)
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;

            # Disable buffering for better UI responsiveness
            proxy_buffering off;
            proxy_request_buffering off;

            # Long timeouts (UniFi can be slow)
            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;
            send_timeout 3600s;
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-proxy
  namespace: redirect
spec:
  selector:
    app: unifi-proxy
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: unifi
  namespace: redirect
spec:
  hostnames:
  - unifi.klimlive.de
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: services
    namespace: infra
    sectionName: main
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: unifi-proxy
      port: 80
