---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: crc-disk
spec:
  storageClassName: openebs-crucial
  volumeMode: Filesystem
  resources:
    requests:
      storage: 55Gi
  accessModes:
    - ReadWriteOnce
