apiVersion: v1
kind: Secret
metadata:
    name: enshrouded-backup-credentials
    namespace: enshrouded
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:/sIg0oO7oRuxqU4Yd3e2IG9DmoxvADQHbA==,iv:mFHQ3fkiT6PJHz3AGLZGngJyL3PW0q9llAYejZgm9vE=,tag:dR64dXfCAsHo7skT82etUQ==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:8b5oQnkqg6paYdzGYEH4SydsaMTRE2gsUEoixeIrww==,iv:zp+LP6NwD74i+pKvoFhFGOnuQTwkL6x6PmhcUreADws=,tag:8GNcjiQRdhdxxysDV5v5uQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:cwg3Kkvs0o7UtLf5SSnpeMPPMTboT7fKrSWfgraYBA==,iv:bZCPXm9u4ugPGEerCGbBo6tdIHWycokCaMDlQKJS0No=,tag:s05LKjQVDsNJfbC5G9z1ug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvQTRpVXZmSlpyOUo3VlU4
            TjJkVVhhSXVReWh6ZlNxRmtjcHczdnAwMWlRClk5RmtiSTc4c3V5a0ZaZGEyQnRK
            dER2RENValphdGRNQjVxWFUwN2pGclUKLS0tIEZqOFEyaWdNWFJ6SUlScWFRdFJq
            OXIwSThWY0UxSW9BVWhhMis2dmNSVDgKQFLDM/z+0RRE0aCSV5CVuPuBD/irOq2e
            X/jPce0xQ3xAhC8uHdu0iYv5OEfQCy5cB/gKaWLc9En28YyPue5hgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T12:45:22Z"
    mac: ENC[AES256_GCM,data:d2/P21vjXi3CIhHP5LS8B8z84tso1ncF9nK/o/Lti9EB5XP1j5n4fo1pkgI7FQTlyDEszsOSwo9oD3M+TnsTxPfTEz9jQHzhM5ffU3Df++nAEyLS7c7bcLv122x14kqIoGOa3P7d23Urr5X/etn/8395qMkhXHV0oIrUF+YPPGA=,iv:wPr+6id5XvNlkjQH/obFtjyY4psFETt14LWcAdmDSwY=,tag:5QCmEn1QGhSs/aL8JFIiOA==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
