apiVersion: v1
kind: Secret
metadata:
    name: enshrouded-backup-credentials
    namespace: enshrouded
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:/sIg0oO7oRuxqU4Yd3e2IG9DmoxvADQHbA==,iv:mFHQ3fkiT6PJHz3AGLZGngJyL3PW0q9llAYejZgm9vE=,tag:dR64dXfCAsHo7skT82etUQ==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:8b5oQnkqg6paYdzGYEH4SydsaMTRE2gsUEoixeIrww==,iv:zp+LP6NwD74i+pKvoFhFGOnuQTwkL6x6PmhcUreADws=,tag:8GNcjiQRdhdxxysDV5v5uQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:cwg3Kkvs0o7UtLf5SSnpeMPPMTboT7fKrSWfgraYBA==,iv:bZCPXm9u4ugPGEerCGbBo6tdIHWycokCaMDlQKJS0No=,tag:s05LKjQVDsNJfbC5G9z1ug==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJd1NlSCtyQldSekFQSm9p
            d2w4TkNzUndlKzJiL3BDNGJxODFwQVh1L1VnCng1eHdCY3IxaDR6SVNCdWZORnNL
            VzFjM2JZc2Rqd3hrRzRqamZsN21malEKLS0tIE1CNmZlVkNoY21BMmFVb2dOR0ZO
            dERuck92TjJNYU9EMThWZXZtRmxwK1kKmpjy4OYPGuNKL7Yyxg98IGv7H4BL5s+R
            rJGAU6h5znYDkrUwNewWQD2bkdLqz3AgJXM921pj1VsjkmKbKhqjkQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IFJTSlJydyBBaGJNRjlZ
            WmZDdktJYWxmWnNvMHUvVVZUdUhONGtqbjNGQTJKVTJlUXdSOApxSjc3U0ljclM1
            Ujd5OWwxNE95d0NlUWpQQXU2eFNjK0NFWEl6dEVmR2tvCi0tLSBlMzhlNm9FaU9T
            TTZvZ0dxblNlM1dHdVZKTzhodUxZME1iUE9LcXNVYnA0ClSDFvch2DoupLqNTzo3
            g3Rumpo9gH5hZi66U9S1lmrDluQqSouu5ZYpuOxDOws9ekVuNsXsCATJlc31jE1h
            km0=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qgn7ll64pzy4wd64h85xxq386cexa98676zw4raej9rvxl822p782xrjn5z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDY0dUwvQSBBb1RXd2Rn
            ZjhOVzhWc0VDTTUvcDg0b2xtZ0o0eDB0Q2lPTGphUjB4OEpNagpmeGJYdmI0YWE0
            V29VbUFGQ0hVRlJ6TW9hRVBHZHNzbEpVNUxVYXhmTUZFCi0tLSBURzRyVTBLc2Fr
            VTNSdGNFVXlEV1hlWmovcmFuOXp3Q2d3OXFRMEpSSVdJCp6ozSjYU1ptb1Q8XohY
            Xg90jV7duz6FgL7ZRSbv5PrdgVlYWRyZ4r1bEMzY5pxHiHaK3kRtJ0kQnEXVjgEI
            f8E=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtvpgtvl83qxn5kferysjnzrt0zs2svfygeuvqznlupmvtepcwv37v7pace
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-04-11T12:45:22Z"
    mac: ENC[AES256_GCM,data:d2/P21vjXi3CIhHP5LS8B8z84tso1ncF9nK/o/Lti9EB5XP1j5n4fo1pkgI7FQTlyDEszsOSwo9oD3M+TnsTxPfTEz9jQHzhM5ffU3Df++nAEyLS7c7bcLv122x14kqIoGOa3P7d23Urr5X/etn/8395qMkhXHV0oIrUF+YPPGA=,iv:wPr+6id5XvNlkjQH/obFtjyY4psFETt14LWcAdmDSwY=,tag:5QCmEn1QGhSs/aL8JFIiOA==,type:str]
    version: 3.9.0
