---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - rbac.yaml
  - task-git-clone.yaml
  - task-buildah.yaml
  - pipeline-build-and-push.yaml
  - secret-cosign-key.yaml
  - secret-ghcr-credentials.yaml
  - blog-klimlive/secret-mastodon.yaml
  - servicemonitor.yaml
  - otel-config.yaml
  - acore
  - desktop-build
  - forgejo-mcp-build
