apiVersion: v1
kind: Secret
metadata:
    name: cosign-key
    namespace: cicd-builds
type: Opaque
stringData:
    cosign.key: ENC[AES256_GCM,data:r/ZV6OYIFBfI1wEcKO4qAB1PSA/kFWhgEsLHGNMY6SL7NdBWP2EydlppD8g97oOgyO6tJ522ZcnbwdannE6dbIH94emcwxMA0kH4cUQhs6z4mSRQ3F72U/OQNRuriUl4wcIdY7DZrvR6W2u+NpZrz11KQllThZGFye3pdafGX6lA+SVDTyoa+4KD+LxrUpEHXpUUcR3uB6Qwz5k/p7rFmTd5kHmLheb0j/8Xs5vYgQmfT3MNjMlifKkR3DIbL/eGw3oCaOw/MTzrBx6In+ffaaCn1wC4qTWRyU7JUUAGXa7oNxpP8w+OlQPNLhwuZtfAU3URYbwWptS7lsQ3L2okVs5MOBirAog4x6mQgCetZBr5Yq//mrdkx8YT3TUqFotJUOm+F9zlQqZzNP3+H7oCl0g5P585YpDYheDBZ1Emdchhs52ViSiQ9ipQBz2taU4EJpA1dx0QD8rgjGRNRBbiIzHoQQw4EeBWdsjtF1zD5ooNkO0L88b9WDILeQLwfWdN8Ic1H0m0mCLTNjZGHkqTn4nK2L+gQIVCaAN6m9MA1/qjH9DZL06Q23j4we1DgLJruQ3UMaPEoB6JJJueh1etO2wzqNJo7xG8CdGC4jbLwmJtPckYzqkckbwXS9uVcE05FgMubHNaIeEPEhRulG+D6mVm3Y5XiBHI6jmY+U0jbnvwZ8de5e8Tymwt9rzgL3mcBhgrwBdnrcbCXfgZLPP+V+Cn660JA3Im10GDo0EaRCFf8iTJY8iNyPDa3p3ayUNptXRJbeNDK7unKXzolSg389cVpYk8DGynQyqxYpyoTEJ0cDvVz7X6BVlaZGj4kcNAWLlYHt/oQbHn0yX6nHx0oyM3i+2T3uDin/7krN8=,iv:t4/CkrIQjmHTh5TV70uC064hkz3igClSgAyjlltPLmg=,tag:6Vq21ouaJzn4yDCZzNJB4A==,type:str]
    cosign.password: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4TmlMTWF0eXhKZWlWdTEr
            L2R5dlh6czQ5T1ozM1dvT0VrYkNaMnFZMW5ZClhXVjBCRlpyNmJUTkxHNTdwUHJH
            eU55VFJ4SzNodm5MQTFKREppbnhud3MKLS0tIE9pZmQzMzNVZ0NqcGpxaEhXY0Nr
            SjdUSjYrK3JYRHBNcEhrTHR5ZHBxd0UKE03RfKoz7tKfV5wBT2d84MBx/ZaFjepA
            /aWfRWFDdzQEytm1YB9tCE+JC1JwpH0bumkEgze/tEcrR3G9+Nw4Kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T15:16:07Z"
    mac: ENC[AES256_GCM,data:ZYzhybvI/YxF+CbGhgZig0uwsmF4IgycQys1uOhUI/A6eD8EKAbWp3cFANY6jE9KT0BVhjmkHdkCjvC5mLztkC9YBanio1oiG2MdQ2e/bDvNFaM4wdPKkv7iXdo7PFCbl9bGZrK4BUENyU7JYuYjL8FW+8hYc7o/3lDzQ6ifm+4=,iv:9tZEFEb5hRA+P6KODqK4K1mmEru2Y30Y1WVAQxlSjF8=,tag:3tIoaccvLOEQJFSnEF9fig==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
