apiVersion: v1
kind: Secret
metadata:
    name: ghcr-credentials
    namespace: cicd-builds
type: Opaque
data:
    config.json: ENC[AES256_GCM,data:GjfduI7yZVPzK9E0cW+S4wne8tad6Y0//jiVewLpgfhHGjxhwinQGGzHmmhPwUAOfGeNaMM4Q0KGv1PM7d8PsXNUEI83l+vt/24Bdna4hKADQoh7wkULGavDJTwv5CkB/kZMFIBCpRpVksmOEB8Ep+THESzZWoYSACLuao4sUfXDdS84CJaKylkqgVE6fPfYoRqY3w2Nkxvw4Hjh0ss95tkgbAIARxvubW5E6TtGpHKButueAeFQYd2CsUMlBO7nhhMuKgH5uIp/Hddd++NusUqAc7GVhaWbKF/auvF2HSfPUyxr9lei2Q==,iv:HeYzBzVDVnuedap9NkN76omLcfOxuioWjD/gs5IKzvY=,tag:6D3o9tYCDbjeNbSL2nU2fg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDVkk3Y0tSMFppMmJHd2ln
            TzBWbVR0VlB1ZytybkJFL3ZuZS85MDJsbW5NClZYWkRLUTRraTBmRzZmaDlkY3Jj
            VmYrYUVFMXNlTm1JY2ovVVEyZy9rc1UKLS0tIFFSZnJrNHU0bE1vK3k0QzNhSStt
            ektvTE0xQ0h0a1N0SVRETkpPd2NiU1kKByyKlfWguTF3MtT2mUDWo8lvs6O7h7Ty
            CtbqV3OtoKA7pGwPyh0Wf/OUkrdnM8fQ0E4MhrxTT6ASD2RD/JortQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-07T15:14:07Z"
    mac: ENC[AES256_GCM,data:qOrLqC+SYjW5oPddePNACKbDXCCWVech6QfaiSLy/Pzl50b8G66+srXDuF2Fw81dqOWVTfI45JagCTSHpspjdTHNz/5zQxvS5vXFWuJV6nn3hJu97i/NJ7TmGYX2fer/39Z0LCD5DG7XDdQZKGmRzUYV1lohwbKw4wgPGI5vE9c=,iv:YRvQ4CSCSxB4hxIiSpUNgp2SQFSrc4x/104rKqmP2ko=,tag:WpuP0UwhPccsqP0Kl7sQfQ==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.0
