apiVersion: v1
kind: Secret
metadata:
    name: ghcr-credentials
    namespace: cicd-builds
type: Opaque
data:
    config.json: ENC[AES256_GCM,data:KUm1J0dU1HRNjYhH4dG5EF85L8NgolZjGeFjBwGaYGb7CQ1XONo6GpjB05eHZVYQsdXor90sbLgLfwGZFPyp8/5EUK2IHn7nUZDbz0xJBxq0lVY4i5r3oFjp5OQFPL9Lm2gmtnLY3SrOaB21i3U9cmBnxaBgtdvhOlWo3v3yXWWMPMxlo1IdYuX4y3k70M39RMbhuIbFUGrS5SFhN3HY05JG8gAtVZTfCxXVXHSDG8X63TRORYqm++b+6PD0t30IAWGEjAiBOfolLCanIqGaKjyXGfAgu4Vjfdc9aov2dejqy8JF4fA1HHyXqIIbTv5n,iv:TIaGa583OiGwrqHC4sLkhUWnM19707RfHul7ie3OMB8=,tag:6eyxX1viqeBY/+8oJpG+1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5M3lYV2lCc2FyaEl2MS96
            UEE5cnh6ZEx1YWhrY0t1bExTMEcydXhzdEdBCmtqU3JwSnk0VUJXNXVlVmM5NndK
            OWExVHdiWjhuNWlwRWVFcHBNd0Y3b2MKLS0tIFErWUR5Ykt1NHdidVVOL1NUamEz
            WFJKVXQzUFFrS1VIaXpGa1RPOVB4S1UK7/Q7Vm3c62sG9eHu/X7eqM0ya/wSvqFY
            YJ6joe+wHszWDsbdmKQTcD1UYXKEgqL6izM7pYevVuLg51W4XRzeGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-06T14:37:27Z"
    mac: ENC[AES256_GCM,data:rdPf+OfJq/Pae0BD8q6/WrSroAhX5XL2FsXa/GWcP9lwyquu3DK+QzBxmXoFCg9g4Ck6P9WQOCTNdDMstDDEphmurwIhHZIhNXZ2WF4556yHkBA54jEK6S+hdG4QxGCyNYTVSDROrrYRGblKw5ntLaCpNo6j3SNI2N+xqKkzjps=,iv:b0CWMQAgi+qjroPSJlVydX63X2eK+Lhggebimhsb0L8=,tag:mGlePzZZnY9b4D5T6aQw2w==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.0
