en:
  label: English
  weight: 1
  title: blog.klimlive.de
  params:
    description: A blog by frzifus

de:
  label: Deutsch
  weight: 2
  title: blog.klimlive.de
  params:
    description: Ein Blog von frzifus
