main:
  - name: Beiträge
    url: /de/posts/
    weight: 1
  - name: Tags
    url: /de/tags/
    weight: 2
  - name: Archiv
    url: /de/archive/
    weight: 3
  - name: Suche
    url: /de/search/
    weight: 4
