env: production

profileMode:
  enabled: true
  title: "Benedikt Bongartz"
  subtitle: "Software, infrastructure, open source and other things."
  imageUrl: "images/profile.webp"
  imageTitle: "frzifus"
  imageWidth: 150
  imageHeight: 150
  buttons:
    - name: Posts
      url: /posts/
    - name: Tags
      url: /tags/

socialIcons:
  - name: github
    url: https://github.com/frzifus
  - name: mastodon
    url: https://mastodon.klimlive.de/@frzifus
  - name: matrix
    url: https://matrix.to/#/@frzifus:matrix.org
  - name: linkedin
    url: https://www.linkedin.com/in/benedikt-b-b11788192/

comments: true
ShowReadingTime: true
ShowShareButtons: true
ShareButtons:
  - linkedin
  - reddit
  - ycombinator
ShowPostNavLinks: true
ShowBreadCrumbs: true
ShowCodeCopyButtons: true
ShowToc: true
TocOpen: false

defaultTheme: auto
disableThemeToggle: false

mastodonInstance: https://mastodon.klimlive.de

footer:
  text: "[Impressum](/impressum/)"

label:
  text: frzifus

assets:
  disableFingerprinting: false
