apiVersion: v1
kind: Secret
metadata:
    name: signoz-mcp-secret
    namespace: llm
type: Opaque
stringData:
    SIGNOZ_API_KEY: ENC[AES256_GCM,data:Ulug3uD7X/dokDH8hQjVJ3U5rD0gCLU4XjcdvYWYHWqJaii2B28nV9VOl4Y=,iv:BsHYgEFSlCFMg3CqezFcRKs8aTcMEzsPq6EdE21YC3M=,tag:M3KFFE/Uu0sScSFL4ryddw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxcTNwOTE2ODY3akw3emM0
            aU5jZDFGRDVpSUpSa0dUWlkyNTNydGlnREh3CllRYXA1V2VyUUxoUTJpb0wrRTAw
            dkNvWUxHMkhWQzdNOTlvWG5XajllVDQKLS0tIDFSTW5BMmJVRm9oa1V0ZjEzRklF
            Mm02SHNRRUFOSTNjVmVHN3QrVzkxRWsKHvrjgTZe7vZeZrN53u+564gxFHg5wLUu
            W0QmZlBLAvBok7ogE5okmBPzDs2O/B7iW/S+4AM3MB5KCJ5/WCaTzA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IFJTSlJydyBBdjZZbmw0
            eHN3Rzl3SE1VWU9SbXlYUXZGN0cxNERxTnVHWHFrNU1HWmZ5ZgpqSjhsQVY1Qk9s
            TDBuNVdITWdOcEU2bjVFMHFiUDlYbFFTdmxVaTV3MzlVCi0tLSBpWEx6MklFRmRR
            enhjMzZ0MmVLRFFOUjZFWFM4cmRRQmpmeko1cnU1RFpvChEZ+Sgmir+BOudCPw3A
            dep9aKFeNQ5WJRhYaSMnaU6T2yNglVzDKeq+qzz7KU5gciwfhCxmV0ALj+VlyKNA
            HZE=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qgn7ll64pzy4wd64h85xxq386cexa98676zw4raej9rvxl822p782xrjn5z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDY0dUwvQSBBckVHbFR3
            RGRKemRZNDBseDhCWm8yc3hMTit5MTIrZXRGUnNSaStXR2FSQwpNOGJpNTV5OEsr
            MERmVlhONXJsQ0hTcGJyTFFXVTYzL1p2TGFmbVlEU25nCi0tLSAwdmZ3ekRhSkNx
            RTNsd2lBN3VzMS8vZ3hqQTFjaVo3ZUk3dEFmVTRwRUo4ChN/rjCdq/VPOgPn4fxL
            VOBb7h6Kx9L03lH3WYU92VRCtN6aG7qPr5tKTTQN+KICUUPESZpjeRLtkJC5p2fY
            O+M=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtvpgtvl83qxn5kferysjnzrt0zs2svfygeuvqznlupmvtepcwv37v7pace
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-08-13T13:57:25Z"
    mac: ENC[AES256_GCM,data:p1JKDFRfUmiK30cbqfaHhnFKEpHxn1qYl7s8R/oO44VIfA8uSuseeo/uvEmk5AHNu2ODaZ+7yElRcfN/ttQKUa9Jil3GenCRd9PvbKqPYbwmuw8KWW9KeMNQidHkSree3BBYERyCgdrA9J0TT8krZbKPVZTQpDuxajSVf03iB3E=,iv:UrEsx2sIuMJBPCNgB9t1NI/m5Hu1gr5pwJ6j4bdpmwg=,tag:PaCXdnkgRcz95TzuPnQouw==,type:str]
    version: 3.9.0
