apiVersion: v1
kind: Secret
metadata:
    name: signoz-mcp-secret
    namespace: llm
type: Opaque
stringData:
    SIGNOZ_API_KEY: ENC[AES256_GCM,data:Ulug3uD7X/dokDH8hQjVJ3U5rD0gCLU4XjcdvYWYHWqJaii2B28nV9VOl4Y=,iv:BsHYgEFSlCFMg3CqezFcRKs8aTcMEzsPq6EdE21YC3M=,tag:M3KFFE/Uu0sScSFL4ryddw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VHlvQWJxelAwSGp1ZnVB
            MUtHclk0ZHVEQVU1d0toUzZIa0wyeUpmb1E4CmNJYjBrMVVabzNNQ2JQL2ltWE5N
            RnJHcmlaY1ZyaDNhMENvbi9MMVAwTncKLS0tIDVNMitVZmM3cHdvNDViUUY4dTBz
            bjZlZHdZM1dvbjdjUkx3RWdQeTh6VkEKAJbgWa0l6cf6jmRBiLIwOR6i9aKXHaSf
            as1PFYOd+SPZt4KJzEyGqjb/LlxApofVvYP+RH4PCpjc/HNCokvTnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-13T13:57:25Z"
    mac: ENC[AES256_GCM,data:p1JKDFRfUmiK30cbqfaHhnFKEpHxn1qYl7s8R/oO44VIfA8uSuseeo/uvEmk5AHNu2ODaZ+7yElRcfN/ttQKUa9Jil3GenCRd9PvbKqPYbwmuw8KWW9KeMNQidHkSree3BBYERyCgdrA9J0TT8krZbKPVZTQpDuxajSVf03iB3E=,iv:UrEsx2sIuMJBPCNgB9t1NI/m5Hu1gr5pwJ6j4bdpmwg=,tag:PaCXdnkgRcz95TzuPnQouw==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
