apiVersion: v1
kind: Secret
metadata:
    name: forgejo-mcp-token
    namespace: llm
type: Opaque
stringData:
    FORGEJO_ACCESS_TOKEN: ENC[AES256_GCM,data:xNKibMPmVxMdkYhrnf6ss+FBc9f1H2qqIunvVchRkbVdHIfqxuLhnQ==,iv:qsWQIDsZvjq889JRLSvj7k9ByxiKSr21x8JQA6Orp5g=,tag:+Wdip5VhTxXcWWzChebIew==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQYitkd3c4UzhhMUpYNmlF
            SlViTklFUGNnN0lGb1Q1VGtMaHhnYTBicW0wCjhsaU5oVWJwSU12TVRkc3BiYkZW
            TTduNUk1YlFnREIvaXBYMjdQMVQvS0EKLS0tIC9vQ2NzYlZnM0RPdVkvRW92UklL
            RngzWENzdlAzYjdoMjhNbUJReXJuZ2cKgIoVmnCREDk8wMALlamm6aZkv8zW+m9/
            yOBuuVw4j6IWTfFpNOcRKS+f7GgpJjYc1w84cKe7ytyMaRVoHt+yLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IFJTSlJydyBBZ25xWVp3
            d1VISTU3RGZnTy92enlCcXpwVHliS25leEtZb0JZL2hhM01yYgpUd3Y4MVRnTG5i
            UDBmZ1F0STZpSnkyZ1g2YVNLNjJDaWVGUkZQUXpDTDZZCi0tLSBLeWhJTEtDcDlM
            alFXLy85RE1VZUZpbGlJNnpXSGRWZ3pEeHlMNzdINnp3Cj8z6A1NodUy9+RKAY3Q
            2Xex/vo+Knv8Vdzr6YwV+yeW0zm0VYMmShHrBCN8T0SPAYLQh94ahr+yxbd1QcJJ
            ua0=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qgn7ll64pzy4wd64h85xxq386cexa98676zw4raej9rvxl822p782xrjn5z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDY0dUwvQSBBNXpnazVC
            aWlYN2RWWDFxZThjNnRxNmVOQ2JYQm9wZWN0WEQrVzlscHlncgpEc0Zva3Jac3RN
            c2V3Qkdac0R3NWM4NlVPNUZmQ2NPSFEyeUpwUkZobXhZCi0tLSBqWUNNcGxLMmp0
            MXVCdXJNMDRRQWlZU2VPZmFRS2dTVDlhYUZjYklkcis0Cmru4ziSWqeeNRgKyT9P
            AkotNbZ/iuuJsjOuzGNVa7B5XdugWyR6N+b0H1GCDKCz7PUcUTZaNZ5EQBJupIfC
            4TI=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtvpgtvl83qxn5kferysjnzrt0zs2svfygeuvqznlupmvtepcwv37v7pace
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-04-09T14:45:01Z"
    mac: ENC[AES256_GCM,data:3fGhV8IZRYWgQLHR1VFurch6JqyP/rMiIFgh9VFzIcTKdUWSD/Kzguz7VxPJE/YVhnmz6PV11ExTj8T3uZ8lGn60nxB+EzoyPAnkPCmt+PuJYNtbGMTt/D+zuxDfLZbBAHOwe+8V2QcbwqnpFVFYQqJvZZOQ3eeS8p1lpjvlBGY=,iv:RkJ5P2UITK8hpjxnod3h9yct0/O49d19cxo5KSLat0A=,tag:tdTS6IA9Q5c1e4NY5jH4cg==,type:str]
    version: 3.9.0
