apiVersion: v1
kind: Secret
metadata:
    name: github-mcp-token
    namespace: llm
type: Opaque
stringData:
    #ENC[AES256_GCM,data:HUJtyO7Y3VQ3/ni2Lcdf0iwbNgKShquQKU1eagND1ZxMQjc4S2DD,iv:MJ8D/mebgU5JEFbJEezsCmM7EZXBXBKCGQZkwWXaZIY=,tag:L94oW+GIruMKZbCtcg6VEA==,type:comment]
    GITHUB_PERSONAL_ACCESS_TOKEN: ENC[AES256_GCM,data:OuE9BmMINw5myfsq99guEhd28ltL+qCEWTPBtaVh2RRaRoVemeKs+g==,iv:Fw4piCNU8l27HxFB6tAS1B4lz8Sq7NkrJZXgpk9+V9Q=,tag:6SO0cgvNrAJgCS4syR7n/Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZXhiVWY1T2VnNnRhblcw
            YXpZTWlCck1YRkNUcklvcEtUb1EyT3U4OWtzCjMrUFdvNVNCK3I3RWM0aTJKSjQ3
            WGN3WnFsVS9ueGptUWZvbXhDUHNJTmsKLS0tIDdyRWs2MVV0eXp6TC9jMjRhbFRO
            bU5PK09UbDhHOUtlZk1NeTlMRUdzdlkKwlbsUiStENaTfhAg1RmwAC9ZqGRyUNX0
            VChhPwp3gYfI9GUiy1rU6rrvpQ/NUJ6lnzN9PgTRCpfgYnsmiaWc7w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IFJTSlJydyBBbnVFYitq
            OGlzM2ttdGRuUmJxU1NZb0dtamxzYmVGdHJObGV4OWRqL0t0RwpPeVNmM08rSEkz
            QkdMU1h0Si9mS3VZcVUrbHpvN2lnaVZqNjlLZ1hUTkVRCi0tLSBCMVNwM0ZhMy9T
            MUFES0ZNeUl6Sm1udGxaYVMyam0zZllSSTYxaDZCUEI0CrhSI4T5n+BWFyRlRzUF
            cwsXuUbamaj/0AAmtc6cEGlmS3i+8wH00tX0LMwcvEno0xvz4OYuZ2fbPsu97Uaz
            Ec8=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qgn7ll64pzy4wd64h85xxq386cexa98676zw4raej9rvxl822p782xrjn5z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDY0dUwvQSBBaFBCOEVS
            c2dKQ3hJMUJLazFIbDdaRWt6Z1ZDZ01MNkovNEgxTmJVSkswcQp2aHZkQU1yL3dk
            WEcwMkhqSjRIcUNhcS80RmZIM3dtRm1hamxuZVBRMkVBCi0tLSA0RlhaM1NCM2Fs
            U2JvRUpGN0hoWVA2aU9haEMrYlFJbFMyMHAzTGd0dGhRCue1hpBiSmc/Hpb3Cu25
            NDgvFpYZo2MtVrGqiMujiLdmsA8trl0OO+DD9Zi7yX7w37ZdGWK9ifkIKgxPBQMi
            fx0=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtvpgtvl83qxn5kferysjnzrt0zs2svfygeuvqznlupmvtepcwv37v7pace
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-04-09T14:56:28Z"
    mac: ENC[AES256_GCM,data:9YvZ33yYKo4GgIU+XWVONFi+minfj7qyDzOQNd3vJ2+uQKPYvuuDlyWON7liQ1x+Fo86Ga0W2l+K6PFB7ujWrFLwlv8m/n6Ha4DlQY2XO1qE3hfssM84kBF8bJFYcPYVqfIvdHpoMfPb9OLFsfS7C60/dZIkoM5dEDjAOpLb0ac=,iv:RIh63CqAt+RcuGPf3P17KkC9K+zNxdCOFsMQc1kTO3s=,tag:GHOPQqYqdulTThpyPk5oxw==,type:str]
    version: 3.9.0
