apiVersion: v1
kind: Secret
metadata:
    name: github-mcp-token
    namespace: llm
type: Opaque
stringData:
    #ENC[AES256_GCM,data:HUJtyO7Y3VQ3/ni2Lcdf0iwbNgKShquQKU1eagND1ZxMQjc4S2DD,iv:MJ8D/mebgU5JEFbJEezsCmM7EZXBXBKCGQZkwWXaZIY=,tag:L94oW+GIruMKZbCtcg6VEA==,type:comment]
    GITHUB_PERSONAL_ACCESS_TOKEN: ENC[AES256_GCM,data:OuE9BmMINw5myfsq99guEhd28ltL+qCEWTPBtaVh2RRaRoVemeKs+g==,iv:Fw4piCNU8l27HxFB6tAS1B4lz8Sq7NkrJZXgpk9+V9Q=,tag:6SO0cgvNrAJgCS4syR7n/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJYXY5MHdqM0V2T2piRzRM
            c3Arc0tQTlRXQ3AxalFkU3BPdGhvYm85K3lnCm9sQVM0emVUMGFra3pZVE16WjUr
            czl1SW9pZldqUzZTL1dFSUoyaVlzc2sKLS0tIE56OEhmVFVtMCtKK1NaMGhaaGJR
            SU8zaEZ3d05SWjBLTEkxZjBERndxRGsKGRS3AfnpveGzfxrZberfaQOABeBF7o9e
            ypqj5RsWToSiXa0j+BKHiULYNqjQ0sVpO+9di3YWJy9DEEzkkaty8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T14:56:28Z"
    mac: ENC[AES256_GCM,data:9YvZ33yYKo4GgIU+XWVONFi+minfj7qyDzOQNd3vJ2+uQKPYvuuDlyWON7liQ1x+Fo86Ga0W2l+K6PFB7ujWrFLwlv8m/n6Ha4DlQY2XO1qE3hfssM84kBF8bJFYcPYVqfIvdHpoMfPb9OLFsfS7C60/dZIkoM5dEDjAOpLb0ac=,iv:RIh63CqAt+RcuGPf3P17KkC9K+zNxdCOFsMQc1kTO3s=,tag:GHOPQqYqdulTThpyPk5oxw==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
