---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-data
  namespace: git
spec:
  storageClassName: openebs-crucial
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
