apiVersion: v1
kind: Secret
metadata:
    name: git-secrets
    namespace: git
type: Opaque
stringData:
    git_admin_username: ENC[AES256_GCM,data:hpY5Rcz0gw==,iv:7kK5UAJoYBMWak4ngIs/VekPiJUSHFDDtaYJxr/wGns=,tag:veYFqeFmtU+44jjjhQYSnw==,type:str]
    git_admin_password: ENC[AES256_GCM,data:afms76TQtEkR,iv:nUjJiRHpBEYJVZusvFF5QKRubsCh1ERkoe/fXgxxAHE=,tag:sAAM1TNB5r/dew4lXxEBzg==,type:str]
    git_admin_email: ENC[AES256_GCM,data:7kbfCpTh/cPozu7mEg7qoDcJhs0=,iv:2sgNsVXhT2/cJ1OHOuBM132OXYpnmxCqU+Z2XdrT+5Y=,tag:E48Na/XF7llJFfsQk+8c2g==,type:str]
    redis_password: ENC[AES256_GCM,data:3lB9eA==,iv:3QTkF7eSzdLj8maQCkbh+rao2P+Hbsidki9V3am3LMo=,tag:ZABjNWiNLcV70x629KSmhw==,type:str]
    username: ENC[AES256_GCM,data:tZ4KA8LpUw==,iv:L//RLpEnkJaT2vlRzDBa9y7Cf3MJFvhZy63wlfuk1nY=,tag:hMUi3DGoCgUpYKKybsUhjw==,type:str]
    password: ENC[AES256_GCM,data:1t923zaHCiqc8g==,iv:aaAje5BzQ1kRWPG2wnDSVH37dvdzgpjKtFPrfJ+eecU=,tag:Erx72dEbVw4L1vvAuvfTlQ==,type:str]
    dbname: ENC[AES256_GCM,data:jpnczyhMvxQU,iv:Ex2/7r45QQNpLZ9cYmHUn8QFR3lR3Kdb+DM31UE90Fo=,tag:nUIbkwD0ORPs0nhLJTRrXQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQUVB5R1FNQ3RteVc4R0RH
            dTJBUlA3WjVtSnNHZy83SVZsaUFiRXc1QTBvCmlqclhSUmJlVWhuc0U4clNzdEhm
            NncrOU0rbWhhblJEUEYyUW1CSHE5YUUKLS0tIFRobW1SMjJnNkhsdStyZ3ZEVjRI
            U3cwWHptOUdqT2xKMFBNUHVrNjJ6elUKcoBmrLXhOVJ1Kp6lQlW1aqe1c8dMD+Gz
            kA8xB4S6lO/KC12pHlwJ/Lm3C+p02dGNqA4ouy2YOdZkifiaXDcx7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IFJTSlJydyBBcjdFUmc1
            Wk5EaWo2S3ZHMEVhcExJckdyQVdxWUNsVHVyTzFrRkRBMFhDTgpuT0ZlSzRrRlVI
            YlBDWTJybFZObkxqclFQbVVrK0F3ZnUySERkdXJkdTR3Ci0tLSBNZ0U3cE15R3J2
            WDZjUzBlNWhKNnNleGJhY0FMRitQcGFzZjVEbUFzM3dzCgYpR+TIyZjg49O4fzGj
            DATGJfW/lY1Ct3iCAW/wmYU8ZOjI4d4kE3ie/PlEHXyBBIj3yc+5BxK5bUkoN2BV
            +Sg=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qgn7ll64pzy4wd64h85xxq386cexa98676zw4raej9rvxl822p782xrjn5z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDY0dUwvQSBBbDd3Nm9Q
            V1M5UGg5THhMcVFIc00rWUM2UHkvUzd2TjJrYldsZlE3S041TAo2UUZDaFdxMUlp
            UWNFQnZzdjdmL08rQjVoQmZ3L0o4em5UOTJyM3kvU1VrCi0tLSBRS2IxZkg5dmMy
            SUU2dmNUZjJUd0ZGc2RFVEVoUDJJMjBaRGRUSlBhaFJrCoS8iZCWNzr8MZ5Pwyeh
            dH2atiVUlpogC/vSDQrz8vocq1noEh8hSG1DZIJlG6/P+ijvRCoy3SIJQyt3DR1+
            cJ8=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtvpgtvl83qxn5kferysjnzrt0zs2svfygeuvqznlupmvtepcwv37v7pace
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-04-08T16:09:32Z"
    mac: ENC[AES256_GCM,data:/JgCufGvhnJaYydS6BXckLgIxnliYSMPmuJ6Da4tieBdoOp+fLwy81E6+S3Rat80jvHe0epYXpBkA7jWTcTTWvdhnSyO/pOTTGFTk5u5oQTJqoEbw8BJf2BR+rVJAgRBKIHWrANZY3mSqBPzT4/B3oCscFRbtjkF0krYtLme4Mo=,iv:4l3cMFwc/U8EAzfBMgrMgk0LniSBnZMKL4d6BSgyOp4=,tag:C4j2awm2nf3AJQ+ysbWZPw==,type:str]
    version: 3.9.0
