apiVersion: v1
kind: Secret
metadata:
    name: git-secrets
    namespace: git
type: Opaque
stringData:
    git_admin_username: ENC[AES256_GCM,data:hpY5Rcz0gw==,iv:7kK5UAJoYBMWak4ngIs/VekPiJUSHFDDtaYJxr/wGns=,tag:veYFqeFmtU+44jjjhQYSnw==,type:str]
    git_admin_password: ENC[AES256_GCM,data:afms76TQtEkR,iv:nUjJiRHpBEYJVZusvFF5QKRubsCh1ERkoe/fXgxxAHE=,tag:sAAM1TNB5r/dew4lXxEBzg==,type:str]
    git_admin_email: ENC[AES256_GCM,data:7kbfCpTh/cPozu7mEg7qoDcJhs0=,iv:2sgNsVXhT2/cJ1OHOuBM132OXYpnmxCqU+Z2XdrT+5Y=,tag:E48Na/XF7llJFfsQk+8c2g==,type:str]
    redis_password: ENC[AES256_GCM,data:3lB9eA==,iv:3QTkF7eSzdLj8maQCkbh+rao2P+Hbsidki9V3am3LMo=,tag:ZABjNWiNLcV70x629KSmhw==,type:str]
    username: ENC[AES256_GCM,data:tZ4KA8LpUw==,iv:L//RLpEnkJaT2vlRzDBa9y7Cf3MJFvhZy63wlfuk1nY=,tag:hMUi3DGoCgUpYKKybsUhjw==,type:str]
    password: ENC[AES256_GCM,data:1t923zaHCiqc8g==,iv:aaAje5BzQ1kRWPG2wnDSVH37dvdzgpjKtFPrfJ+eecU=,tag:Erx72dEbVw4L1vvAuvfTlQ==,type:str]
    dbname: ENC[AES256_GCM,data:jpnczyhMvxQU,iv:Ex2/7r45QQNpLZ9cYmHUn8QFR3lR3Kdb+DM31UE90Fo=,tag:nUIbkwD0ORPs0nhLJTRrXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDM3FYb0VUaG1vWWtpK0hO
            ckhyckVhSEJreEx6R09PVFh4ZTV3eWhzUEdBCldOVS9wM21odW5PekZyS2lIMnh1
            R3V0eG1uWU1FU0dMSXgwY1V2eUgwYjQKLS0tIFRrQTJjYWJzZ2VzUGxWTUsvT1NK
            VjFDYTBVWEE0YiszVGZNZlZUaS92aGMKGyfzWDPzt4uqtQ5i6RR8Tdih3L425/p/
            NxRwFJ4Ovz5hlY5zQAD/agWRXE9Y+sD+NXPSab2xCAfxcLLEL/VXVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-08T16:09:32Z"
    mac: ENC[AES256_GCM,data:/JgCufGvhnJaYydS6BXckLgIxnliYSMPmuJ6Da4tieBdoOp+fLwy81E6+S3Rat80jvHe0epYXpBkA7jWTcTTWvdhnSyO/pOTTGFTk5u5oQTJqoEbw8BJf2BR+rVJAgRBKIHWrANZY3mSqBPzT4/B3oCscFRbtjkF0krYtLme4Mo=,iv:4l3cMFwc/U8EAzfBMgrMgk0LniSBnZMKL4d6BSgyOp4=,tag:C4j2awm2nf3AJQ+ysbWZPw==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
