apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: observability
spec:
  ports:
  - name: otlp
    port: 4317
    protocol: TCP
    targetPort: otlp
  - name: otlp-http
    port: 4318
    protocol: TCP
    targetPort: otlp-http
  selector:
    app.kubernetes.io/component: otel-collector
    app.kubernetes.io/instance: backend
    app.kubernetes.io/name: signoz
  sessionAffinity: None
  type: ClusterIP
