apiVersion: opentelemetry.io/v1alpha1
kind: ClusterObservability
metadata:
  name: gateway
  namespace: observability
spec:
  exporter:
    endpoint: "http://backend.observability.svc.cluster.local:4318"
