---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: metrics-collector
  namespace: observability
spec:
  mode: statefulset
  replicas: 1
  targetAllocator:
    enabled: true
    allocationStrategy: consistent-hashing
    filterStrategy: relabel-config
    prometheusCR:
      enabled: true
      scrapeInterval: 30s
      # Empty selectors mean "select all"
      serviceMonitorSelector: {}
      serviceMonitorNamespaceSelector: {}
      podMonitorSelector: {}
      podMonitorNamespaceSelector: {}
  config:
    receivers:
      prometheus:
        config:
          scrape_configs: []
        target_allocator:
          endpoint: http://metrics-collector-targetallocator:80
          interval: 30s
          collector_id: "${POD_NAME}"
    processors:
      batch:
        timeout: 10s
        send_batch_size: 1024
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
    exporters:
      otlp:
        endpoint: backend-signoz-otel-collector.observability.svc.cluster.local:4317
        tls:
          insecure: true
      # otlp/weaver:
      #   endpoint: weaver.observability.svc.cluster.local:5317
      #   compression: none
      #   tls:
      #     insecure: true
      #   retry_on_failure:
      #     enabled: false
      #   sending_queue:
      #     enabled: true
      #     queue_size: 100
    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: [memory_limiter, batch]
          exporters: [otlp]
