---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: openobserve
  namespace: observability
spec:
  url: https://charts.openobserve.ai
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: o2c
  namespace: observability
spec:
  releaseName: o2c
  chart:
    spec:
      chart: openobserve-collector
      sourceRef:
        kind: HelmRepository
        name: openobserve
        namespace: observability
  interval: 15m
  values: # TODO: testing
    k8sCluster: homelab
    exporters:
      "otlphttp/openobserve":
        endpoint: http://backend:4318/
      "otlphttp/openobserve_k8s_events":
        endpoint: http://backend:4318/
