apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: signoz
  namespace: observability
spec:
  url: https://charts.signoz.io
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: backend
  namespace: observability
spec:
  releaseName: backend
  interval: 30m
  chart:
    spec:
      chart: signoz
      version: "0.89.1"
      sourceRef:
        kind: HelmRepository
        name: signoz
        namespace: observability
  install:
    createNamespace: false
  upgrade:
    crds: CreateReplace
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: signoz
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: k8s-infra
      sourceRef:
        kind: HelmRepository
        name: signoz
        namespace: observability
      version: "0.14.1"
  values:
    otelCollectorEndpoint: "backend-signoz-otel-collector:4317"
