FROM docker.io/library/golang:1.26 AS builder

WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -o /serve ./cmd/serve

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=builder /serve /serve
ENTRYPOINT ["/serve"]
