---
apiVersion: v1
kind: Namespace
metadata:
  name: amd-gpu-plugin
  labels:
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: amd-gpu-operator
  namespace: amd-gpu-plugin
spec:
  url: https://rocm.github.io/gpu-operator
  interval: 1h
---
# NOTE: https://github.com/ROCm/gpu-operator/issues/30#issuecomment-2564065704
#
# helm install amd-gpu-operator rocm/gpu-operator-charts --namespace amd-gpu-plugin --set kmm.enabled=false --set node-feature-discovery.enabled=false
#
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: amd-gpu-operator
  namespace: amd-gpu-plugin
spec:
  interval: 5m
  releaseName: amd-plugin
  chart:
    spec:
      chart: gpu-operator-charts
      sourceRef:
        kind: HelmRepository
        name: amd-gpu-operator
        namespace: amd-gpu-plugin
      version: "*"
      # version: "1.0.0"
  values:
    kmm:
      enabled: false
    node-feature-discovery:
      enabled: false
---
apiVersion: amd.com/v1alpha1
kind: DeviceConfig
metadata:
  name: amd-device-plugin
  # use the namespace where AMD GPU Operator is running
  namespace: amd-gpu-plugin
spec:
  driver:
    # disable the installation of our-of-tree amdgpu kernel module
    enable: false

  # devicePlugin:
  #   devicePluginImage: rocm/k8s-device-plugin:latest
  #   nodeLabellerImage: rocm/k8s-device-plugin:labeller-latest

  # Specify the metrics exporter config
  metricsExporter:
     enable: true
     serviceType: "ClusterIP"
     # Node port for metrics exporter service, metrics endpoint $node-ip:$nodePort
     port: 5000
     # NOTE: defaults ends with: ErrImagePull
     # Selected default image is:
     # registry.test.pensando.io:5000/device-metrics-exporter/rocm-metrics-exporter:v1
     image: rocm/device-metrics-exporter:v1.2.1

  # Specifythe node to be managed by this DeviceConfig Custom Resource
  selector:
    feature.node.kubernetes.io/amd-gpu: "true"
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: amd-device-plugin-metrics
  namespace: node-feature-discovery
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: metrics-exporter
  endpoints:
  - interval: 10s
    path: /metrics
    targetPort: 5000
    scheme: http
