---
clusterName: homelab
talosVersion: v1.9.4
endpoint: https://192.168.5.2:6443
allowSchedulingOnMasters: true
additionalApiServerCertSans:
  - home-cluster
cniConfig:
  name: none
patches:
  - |-
    - op: add
      path: /machine/sysctls
      value:
        net.ipv4.ip_unprivileged_port_start: "0"
  - |-
    cluster:
      proxy:
        disabled: true
  - |-
    machine:
      systemDiskEncryption:
        state:
          provider: luks2
          keys:
            - tpm: {}
              slot: 0
        ephemeral:
          provider: luks2
          keys:
            - static:
                passphrase: ${diskEncryption}
              slot: 0
  - |-
    - op: add
      path: /machine/kubelet/extraMounts
      value:
        - destination: /var/local
          type: bind
          source: /var/local
          options:
            - bind
            - rshared
            - rw

# NOTE: Contains
# schematic:
#   customization:
#     systemExtensions:
#       officialExtensions:
#         - siderolabs/iscsi-tools
#         - siderolabs/util-linux-tool
#         - siderolabs/amd-ucode
#         - siderolabs/amdgpu
#         - siderolabs/i915
#         - siderolabs/intel-ucode
#         - siderolabs/mei
#         - siderolabs/qemu-guest-agent
#         - siderolabs/tailscale

controlPlane:
  talosImageURL: factory.talos.dev/installer-secureboot/d1dcbd874be717cf1c5706bbe5c102bce507a1041f997d06f70dffc0556fe3a4
  extensionServices:
    - name: tailscale
      environment:
        - TS_AUTHKEY=${tsAuth}

worker:
  talosImageURL: factory.talos.dev/installer-secureboot/d1dcbd874be717cf1c5706bbe5c102bce507a1041f997d06f70dffc0556fe3a4
  extensionServices:
    - name: tailscale
      environment:
        - TS_AUTHKEY=${tsAuth}

nodes:
  - hostname: master1
    ipAddress: 192.168.5.2
    installDisk: /dev/sda
    controlPlane: true
  - hostname: master2
    ipAddress: 192.168.5.3
    installDisk: /dev/sda
    controlPlane: true
  - hostname: master3
    ipAddress: 192.168.5.4
    installDisk: /dev/nvme0n1
    controlPlane: true
  - hostname: storage1
    ipAddress: 192.168.5.6
    installDisk: /dev/nvme0n1
    controlPlane: false
    patches:
      - |-
        - op: add
          path: /machine/sysctls
          value:
            vm.nr_hugepages: "1024"
      - |- # https://www.talos.dev/v1.9/advanced/advanced-networking/#bonding
        machine:
          network:
            interfaces:
              - interface: bond0
                dhcp: true
                bond:
                  mode: 802.3ad
                  lacpRate: fast
                  xmitHashPolicy: layer3+4
                  miimon: 100
                  updelay: 200
                  downdelay: 200
                  interfaces:
                    - enp1s0
                    - enp2s0
    nodeLabels:
      openebs.io/engine: mayastor
      role: "storage-node"
    taints:
      - key: "role"
        value: "storage-node"
        effect: "NoSchedule"
  - hostname: storage2
    ipAddress: 192.168.5.8
    installDisk: /dev/nvme0n1
    controlPlane: false
    patches:
      - |-
        - op: add
          path: /machine/sysctls
          value:
            vm.nr_hugepages: "1024"
      - |- # https://www.talos.dev/v1.9/advanced/advanced-networking/#bonding
        machine:
          network:
            interfaces:
              - interface: bond0
                dhcp: true
                bond:
                  mode: 802.3ad
                  lacpRate: fast
                  xmitHashPolicy: layer3+4
                  miimon: 100
                  updelay: 200
                  downdelay: 200
                  interfaces:
                    - enp1s0
                    - enp2s0
    nodeLabels:
      role: "storage-node"
      openebs.io/engine: mayastor
    taints:
      - key: "role"
        value: "storage-node"
        effect: "NoSchedule"
  - hostname: worker1
    ipAddress: 192.168.5.9
    installDisk: /dev/nvme0n1
    controlPlane: false
  - hostname: worker2
    ipAddress: 192.168.5.10
    installDisk: /dev/nvme0n1
    controlPlane: false
  - hostname: gpu1
    ipAddress: 192.168.5.11
    installDisk: /dev/sda
    controlPlane: false
  - hostname: gpu2
    ipAddress: 192.168.5.12
    installDisk: /dev/nvme0n1
    controlPlane: false
    patches:
      - |- # https://www.talos.dev/v1.9/advanced/advanced-networking/#bonding
        machine:
          network:
            interfaces:
              - interface: bond0
                dhcp: true
                bond:
                  mode: 802.3ad
                  lacpRate: fast
                  xmitHashPolicy: layer3+4
                  miimon: 100
                  updelay: 200
                  downdelay: 200
                  interfaces:
                    - eno1
                    - enp7s0
