FROM debian:bookworm

RUN apt-get update && apt-get install -y git curl unzip sudo wget gnupg cmake make gcc g++ clang libssl-dev libbz2-dev libreadline-dev libncurses-dev libboost-all-dev

RUN git clone https://github.com/liyunfan1223/azerothcore-wotlk.git --branch=Playerbot /azerothcore-wotlk

RUN git clone https://github.com/liyunfan1223/mod-playerbots.git --branch=master /azerothcore-wotlk/modules/mod-playerbots

WORKDIR /azerothcore-wotlk

RUN sed -i 's|# OSDISTRO="ubuntu"|OSDISTRO="debian"|' conf/dist/config.sh

RUN sed -i 's|ORIGIN_REMOTE="https://github.com/azerothcore/azerothcore-wotlk.git"|ORIGIN_REMOTE="https://github.com/liyunfan1223/azerothcore-wotlk.git"|' conf/dist/config.sh && \
    cp conf/dist/config.sh conf/config.sh

RUN ./acore.sh install-deps

RUN ./acore.sh compiler all

RUN ./acore.sh client-data

# # NOTE: nice to have
# https://www.azerothcore.org/catalogue.html#/details/74011079
# .npc add 190010
# > exec mod-transmog/data/sql
RUN ./acore.sh module-install mod-transmog
# https://www.azerothcore.org/catalogue.html#/details/113239863
RUN ./acore.sh module-install mod-learn-spells
# https://www.azerothcore.org/catalogue.html#/details/65892802
RUN ./acore.sh module-install mod-duel-reset
# https://www.azerothcore.org/catalogue.html#/details/291842397
RUN ./acore.sh module-install mod-account-mounts
# https://www.azerothcore.org/catalogue.html#/details/108285701
RUN ./acore.sh module-install mod-account-achievements
# https://www.azerothcore.org/catalogue.html#/details/138432861
RUN ./acore.sh module-install mod-ah-bot


# # # NOTE: Arena
# # https://www.azerothcore.org/catalogue.html#/details/243375326
# RUN ./acore.sh module-install mod-arena-tigerspeak
# # https://www.azerothcore.org/catalogue.html#/details/243374275
# RUN ./acore.sh module-install mod-arena-tolviron

# # # NOTE: bg
# # https://www.azerothcore.org/catalogue.html#/details/227439010
# RUN ./acore.sh module-install mod-bg-battle-for-gilneas
# # https://www.azerothcore.org/catalogue.html#/details/215361574
# RUN ./acore.sh module-install mod-bg-twinpeaks
# # https://www.azerothcore.org/catalogue.html#/details/174038200
# RUN ./acore.sh module-install mod-bg-slaveryvalley

# NOTE: testing
# https://gitlab.realsoftgames.win/krazor/mod_llm_chat
# ollama pull socialnetwooky/llama3.2-abliterated:1b_q8
# RUN apt-get install -y \
#     libboost-all-dev \
#     nlohmann-json3-dev \
#     build-essential
# RUN git clone https://gitlab.realsoftgames.win/krazor/mod_llm_chat --branch=main /azerothcore-wotlk/modules/mod_llm_chat

RUN ./acore.sh compiler build
