---
apiVersion: "openebs.io/v1beta2"
kind: DiskPool
metadata:
  name: storage1-cache-ssd
  namespace: openebs
spec:
  node: storage1
  disks: ["/dev/disk/by-id/ata-SanDisk_SSD_PLUS_480GB_24036A805360"]
  topology:
    labelled:
      type: cache
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-cache
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
parameters:
  protocol: nvmf
  repl: "1"
  thin: "true"
  fsType: xfs
  poolAffinityTopologyLabel: |
    type: cache
allowVolumeExpansion: true
provisioner: io.openebs.csi-mayastor
reclaimPolicy: Delete # Retain
