---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: novnc
  namespace: steam
  labels:
    app: novnc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: novnc
  template:
    metadata:
      labels:
        app: novnc
    spec:
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: novnc
        image: gotget/novnc
        args:
        - "--vnc"
        - "headless:5900"
        ports:
        - containerPort: 6080
          name: novnc
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
---
apiVersion: v1
kind: Service
metadata:
  name: novnc
  namespace: steam
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 6080
  selector:
    app: novnc
