---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: games
spec:
  storageClassName: openebs-cache # NOTE: testing
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home
spec:
  volumeMode: Filesystem
  storageClassName: openebs-cache # NOTE: testing
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce

