---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - task-desktop-image-build.yaml
  - task-desktop-image-build-arm64.yaml
  # Uncomment to enable scheduled builds:
  - cronjob-desktop-build.yaml
  # - cronjob-desktop-build-arm64.yaml
