apiVersion: v1
kind: Secret
metadata:
    name: openebs-etcd-backup-credentials
    namespace: openebs
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:1iGLiSS8E5zyjG5+WlJikPugLgyvvoFIAQ==,iv:zpFA3A6gdqL6n8+Hg0jLAqh+ghupMo7YKgBfJ0vRvUU=,tag:tohEBY9uMipUQ4zSuOLKaQ==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:a4kxeeBWj+rpSI2PXw0Mw9ie8Z+e9umOHklwQOZa3Q==,iv:M2hCFs2U+laL/rqqznCFCzODL7eWF+UJuczEHWMP9Kc=,tag:KAOePn1pDF+hAS1baxVhCA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:o/bHDb+lZk96E/ZuXQ5H9zCnefdRo2M6e8KmlMIdWQ==,iv:UklUeIbwtOmtNwyOrzk6apLObOUdLx20ggP60YUWQBc=,tag:xd0zHqUlX6crCUHQPn0SZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4SWxLOXlSNU5XblFqVDIr
            MlVEcXFvVldhSGZvU3F1WVUxMGZDV3F5R1RvCkpmVXNwVTE4RTAxSTNybUJobmIx
            YWE3LzlqQytoM0I4Sk5NVHNQV24vYUUKLS0tIGtmR0JSY0s3NEFZNXgycGhLN29j
            RDBTcnR0RUdzTDFaRVhsMkJXczNFeDAKkunOleE/gVeJ1/m9JVenjaAKz+EdMZF/
            vGWg0yuM8WpClX3fPLL8lqbRW0q6+0EiqeqZ6wNhfFpXEj2qgSynhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-21T16:07:52Z"
    mac: ENC[AES256_GCM,data:qhV+M6P0m2sWsHRJNmmzjMuVPPDX0bKnWTRyxeOKHbXUBXWuNXbEUcnxDpbfnG53Ezfup+UKNiTECKHYnTkRWYRh4cM/In+3Wn1Qwl4LxRHNnw3oG4+Q5A1ISqcJwwJqpyLUFBesfpS1ywscr5Iaodwmx8nkFHkbPt46Xy093NU=,iv:b4CwuvsxrvlBc1IPy4ljqhV06f4h6Vry/e0jZu/K1hQ=,tag:sGXqgEbByDheTYxhA1UTOA==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
