apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: ext-galabau
data:
    tunnel-token: ENC[AES256_GCM,data:a7BgFmY+ZE0igMxNeb1gTbTS6mhqzMunZOjXp7+bNh6AyXmqbNwX3r/yRXMtKXTcutTHaR/dXn2tb3CrZO54r9/k7IHG5kw2DOba7qddWAy/IUROpsbznDw1XOeTuWJmV0lsPjNRAK9iaKJ+o5CV/ayrQ3LWnCtM3qcrGIhpCfElyKHPEKdjnGI+pwLInGo/tsJSHDf1KImZMwPhCn4Ya5v4D/EpDrZnhziLDbRLnTG9csAhTiSf/OjAocigCTb4Myr9N9pohj8LEin9tRZB/fEFrMQLPeq8evs77R75y/7qhuNAUEswGm2yiMUETPxzuNnxoYI0AY8=,iv:JdZRh2PGfJS2dhnET4DA+l002/YIsko0+DafQAwha2E=,tag:wtQ2TaFclLAQALQ2zIKcZQ==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwY2VudkFZa3lkSFJaenR5
            RFlJdlBUMXc5dmJVZ0ZoTDdKdWhkNHA0NTBvCi9acG9wNGpWQ2l1ZDVKUW9vVy9F
            WUhaTER3OTUxcnpBSXpjYU1JbDlHbEEKLS0tIFROSTVoeDVyamg4NUFIYW5Pb1Bu
            ckpKcEE3S1NETnFWclN3cndhK0ZBZXcKFg//GHD9jH45snpk52syKDgvSwgxEvaQ
            /sxjqhXp9enDv+JQ/DX9LEVYnhVJTogD5Cm9Kx8csduECSe+3GmHkQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IFJTSlJydyBBc0lUTDJD
            dzB3VENhQXpyODBxWFJRSmlhS0w0KzdLVmNHc0ZLbWM5UjBCYgo4d3V2L1A5WXNI
            YnlBcnJ5OTZZTkt0VUU0V01iR2hGSEE1dWFrbWlPbGEwCi0tLSBsRjVFTFhrYkdm
            dnVwYnIrNEtjZ2psbGZkbEZseE8xeHJWMXQra1ptR1NBCsUjZ9in2rKKIBR+ksuw
            ARstEyU/Dj1/Xdjheh0pxUl7yyadi8KB4Lm/K7ixWObQRejgSXy2w8MErVzv+OhI
            ZUY=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qgn7ll64pzy4wd64h85xxq386cexa98676zw4raej9rvxl822p782xrjn5z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDY0dUwvQSBBbDI1Sy9w
            Vk5yaEhORkRxNjQ4NUxJU1poRi9BTHhqRW9NSTd1OVM2K3lINwpTVHEwL2ZYUDV5
            RjZSdWFTaEJwWlJReTNFNlBsNXB1enZ5TkZMSitLQ0xzCi0tLSBYeTlUcXdHN25G
            KzhUNEVUOG9IejVVUGU0RFRkZFU5L3JGQUdBaSs4QVdNCnkwLLzDnN6tt5pTogyS
            IxkXODf0KeGQ3+RN7rdv9tftbBr2EwhPZu4hrhbh60a5lgqIPjDVHpUAnEZdXqf0
            stY=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtvpgtvl83qxn5kferysjnzrt0zs2svfygeuvqznlupmvtepcwv37v7pace
    encrypted_regex: ^(data)$
    lastmodified: "2025-09-09T11:13:36Z"
    mac: ENC[AES256_GCM,data:3c5kX9hFXyxBCuUXB/y/PAd1F78Xz16ohBYdprYxTD6NKDMtuTXQMvknUJB8e2jHM4og/Dqlm3yogaoFPDuM+h8Li9xP/g5FKT+ue5SG9xPS6LHPLMeAFl3XtFw4Zzj+iwMF8vRd9aw7sUnaqQzQysdDy7cQ0XBxw4FVfdIfwKE=,iv:HnBmTvQ3gMWnkL88tzT1GzQeYAXH5M7QsxyBbheWScY=,tag:34bCJ2qg7wooEr5M/PTdRQ==,type:str]
    version: 3.9.0
