apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-sso
    namespace: vaultwarden
type: Opaque
stringData:
    SSO_CLIENT_ID: ENC[AES256_GCM,data:yXbwJu1IqEKMaC8Vc61bd18vNwFgasZ48w1tMAlOdmNEecmrWgiOmQ==,iv:Hp16DTcx+mx7bOaNyHFwwNtrjLRo78HT/czfCDsPiBQ=,tag:kwAaoYJEPlNfwYbkGPvASA==,type:str]
    SSO_CLIENT_SECRET: ENC[AES256_GCM,data:X3ij0buohGBTg/hkYHjQbP2pPQFOCdluDjs3msPuvOO5QQBJx8LxutoPhLzZI8U/9VWh6CkWw3n4aMV0d2vT2eZ2tl9SHBmuock8KcocUkSZABByiu/3z1dno7YorP3X75Bazap/mGyvh/RD/jb5pgCKStMraqY2SygX65yplbQ=,iv:WNQbwPq5EAgiS7kt9ax3G6nnWQfGIbGdPst+vpfvgQk=,tag:1/m4RuCMl2O0ie8Y8AQUrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdEwrNFdMSEtZcmJrK05n
            U1FMaE1SS0czTWxlNVBCNmJRQ3BodUtqZ0NRClByYVRPL0ZhdmVvMEVPSmpwR0tD
            UkN1RDBQLzhLa1BHZDBULzh0eHlzYXMKLS0tIGg1QXg0RWlIeG1sUllHU1dPNkND
            RUl0MDgxUm9OWkM1M1U5dmUxa1lOUzQKHkkKjo+rTwYI8rMImMSvrbznKuAK7FLN
            Qvp+ny+hEnX+gBQitK007JhMT9QQ112I7oeG9/uO4M1HkehEW0EHqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-07T00:31:13Z"
    mac: ENC[AES256_GCM,data:kwfn7YMB0mt+vfYs2OsU7xBm4VB4RMsawFsXFt7t78iitW7+XGNvAygbuzaQwy2/l1EgymaQ8BFj19qHT9HZMtpiP65zMzQYm57RpNLSmKuaoeYwjxbKKliwp3x5wcvFvKfwHTWf8afmPqM2q9f7UCvUVnPniVZaY7Zs96BSnFM=,iv:YLA5ZOI6TmOOhO5txAL6XL/w7DvLVAYzlWCIhVGF2dE=,tag:LwQTW1ldlc4Gev+voSOTcw==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
