apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-sso
    namespace: vaultwarden
type: Opaque
stringData:
    SSO_CLIENT_ID: ENC[AES256_GCM,data:yXbwJu1IqEKMaC8Vc61bd18vNwFgasZ48w1tMAlOdmNEecmrWgiOmQ==,iv:Hp16DTcx+mx7bOaNyHFwwNtrjLRo78HT/czfCDsPiBQ=,tag:kwAaoYJEPlNfwYbkGPvASA==,type:str]
    SSO_CLIENT_SECRET: ENC[AES256_GCM,data:X3ij0buohGBTg/hkYHjQbP2pPQFOCdluDjs3msPuvOO5QQBJx8LxutoPhLzZI8U/9VWh6CkWw3n4aMV0d2vT2eZ2tl9SHBmuock8KcocUkSZABByiu/3z1dno7YorP3X75Bazap/mGyvh/RD/jb5pgCKStMraqY2SygX65yplbQ=,iv:WNQbwPq5EAgiS7kt9ax3G6nnWQfGIbGdPst+vpfvgQk=,tag:1/m4RuCMl2O0ie8Y8AQUrA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKM2ZFL2FpY3UxUEFqNGFV
            cWoraUI4T3o1bzVMNGhHNTRQeDlkd2RIZlQwClJSWmgzYkgwandqam44NEJPVFl5
            UVlTeHNOVHhtR1pNMFpYcU45UzhvTlkKLS0tIFBteW92WVAzT1h5TGhleTZ6SWxi
            VlYwWDdRdWtDRmdpWVd0ajhVVWJITWMKesKnDKcSI7AceeUED2TaNdcSWO05u2xB
            HGN5wY6U+kAh+3JKfhJrsJAPK6iBVKrrJCf9cd7nSjNb3ewhaB+KWQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IFJTSlJydyBBMFNHblpB
            Qk0zU1FkM0pWVFRxTFRINkJ5K0FzdjZBcTl6UUtLZ0dwNkppVApPYWhUSmNqZkFa
            MG9wRVdldVBuVk1PdzNUM3Y1QitGZ0lWS0lSTWhOQzFzCi0tLSB6MElZY1lsejd6
            aWdHZzhPRlB4YlpKNExwMlNmT2FncUlYOVBEQVgzL3hvCneyir7sdYZvMLN5VFMk
            ap6x/Xcz+r3DiibGZi1i4FxACMtu1BH+Se1BsIYayk9xE5KQt3aM0cBS9mPorblC
            XeU=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qgn7ll64pzy4wd64h85xxq386cexa98676zw4raej9rvxl822p782xrjn5z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDY0dUwvQSBBM3VIamFL
            SlZQWWJON3E3QnNnVGNQUURoK2dHWU1nMGUzRzFTeVVmSlQzagpWNGhVMHhoRUE2
            NkFQR1FpbklhZ0FIVXhSc1k2QWpEVGJ6OVdWRHdCMDdVCi0tLSBVeEhiWk1JUTk2
            WlRCbGdOL1g0M04zT0NCK1YzREJTS29hUExmQkhvS2hVCgXa+Y9UT+WRM6BZ3q7f
            nD6F479/TVUpQ9M4l2GVcQglIryQYSIYPFWF9hOhkGWh2iul0ufeATg+NwreZBX5
            SkM=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtvpgtvl83qxn5kferysjnzrt0zs2svfygeuvqznlupmvtepcwv37v7pace
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-07T00:31:13Z"
    mac: ENC[AES256_GCM,data:kwfn7YMB0mt+vfYs2OsU7xBm4VB4RMsawFsXFt7t78iitW7+XGNvAygbuzaQwy2/l1EgymaQ8BFj19qHT9HZMtpiP65zMzQYm57RpNLSmKuaoeYwjxbKKliwp3x5wcvFvKfwHTWf8afmPqM2q9f7UCvUVnPniVZaY7Zs96BSnFM=,iv:YLA5ZOI6TmOOhO5txAL6XL/w7DvLVAYzlWCIhVGF2dE=,tag:LwQTW1ldlc4Gev+voSOTcw==,type:str]
    version: 3.9.0
