---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secret.yaml
  - secret-tunnel.yaml
  - configmap.yaml
  - pvc.yaml
  - redis.yaml
  - otel-redis-sidecar.yaml
  - otel-postgres-sidecar.yaml
  - otel-sdk-config.yaml
  - postgres.yaml
  - mastodon-web.yaml
  - mastodon-streaming.yaml
  - mastodon-sidekiq.yaml
  - mastodon-setup.yaml
  - httproute.yaml
  - servicemonitor.yaml
