apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: mastodon
stringData:
    tunnel-token: ENC[AES256_GCM,data:CQzQNBPMbfpA4ke2quY7PeDd9L8ASK3hlfHi6lPcJ2rZVaeYyOCxpggzHy6JkLx1fvZ3qOR6D/BIlMzuSbYl0frVCUC0kpWlAfMYTQpkgXvv8s2seyqOyh1a3pk2+am45crKzfvl5HWUoSK26DQRcaZJlr/ZLbFBapv8nXwJ8lSg84Fv5ZmZsDdzmRJ11j/HgEgpoeFrcLiVu+w9l5+y6QCU5uBcWhqO13jtUn3ozIHaWUtLgTWEow==,iv:cN7sMuW7PHc40xvgyOu327vmrB6f9YtEvvDDzYhjWMs=,tag:iKjZzu4gpgsHM3huL20d1g==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwYmU0U1F1eE1kTzJ0VCtU
            aDhxOWxxRTExRXQ2RVJaR3VvaFZKRUk0L2tNCnBGeUZMb0hBaHM0cTAyWjlwWWI2
            eUg5K0NMUTFLTGZNQlZLd1dsZnpTN2cKLS0tIEc4SGFSVmYxL0VDTzdsVG5ObSsz
            ai9wN0VpNGREZWtJbFdMSFdFTW1CNVEK3B7tgiKbGQ/IsL7wDwEj1gu+bkZ88opm
            /zunRAEGfk/5YjOvmj3sCWZkAyZJK4GVVnrLYmJ4rlEIhZ20NnCNZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-03T10:23:20Z"
    mac: ENC[AES256_GCM,data:ValKCIKmUHNiC4nz/L4MJMFJ9ncYuDgH0lCRUITIRUIEyl/daNsk7IwltwISTlhmFwVbTciJkgX1iKIn+I2Wx96v1ln7EcDEpnYMljsQebEld2MDQ8rOPyI7vCIBvFj615n9EL1MlVlPm55LBC8pbeuEcgrtpizP/W+lLTOsCj4=,iv:6W6xJ+6IL9yirY63JYZXAMC7XOqSUCkFqZAJR6+gLzQ=,tag:16W+2kJOMysVq1Xz8J73Mw==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
