apiVersion: v1
kind: Secret
metadata:
    name: mastodon-secrets
    namespace: mastodon
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:xLGSts81Y1A=,iv:51ypzUWsSw5jbqEVfNTIl64TGAJ/Ilnm52Va6uBOer0=,tag:RuGZFZ4yHBDkwu9Ae50fEw==,type:str]
    password: ENC[AES256_GCM,data:mxxclh8Ufdwph8fYkJuxyeVImVzU+6QA2RrHlCEy7U8=,iv:q6N6ogc2OMvqGSedlFT4PVwzoVfw/RR4j7DXskE26bQ=,tag:ST4vDRkqeIy9ZvgRbzOy6w==,type:str]
    dbname: ENC[AES256_GCM,data:irgjkBd53ig=,iv:0I0maiX+0WZr5LwHuKUBjbBqLKOb8ScpRFjCBqZ/W6U=,tag:Y37AC5SFHDk+mlnnmXxMjQ==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:1zzCfg7u19KufOvFQOK3eVdn4jVw12VMskSzv03vVWke4qp5+PapbaenGO9DKUJW95dQ4e7wgl8Em73gp7jUUxTiEwItOmJOH6lCQfF5pJvow/Y3ZqwGgVADKMx+AcKe3a5mMK8IsKE5lZmgpdFX6Uo8Xu7xJoNe58R1QvJjElM=,iv:uqZlYE2SymFtaonjqEckis21NNgbLMFFe4h7LO+erIw=,tag:vNtyd9KPtgyunZd1aZAXWw==,type:str]
    OTP_SECRET: ENC[AES256_GCM,data:tyibTz3RcacFEVfBVjoPJ2G3gtupXzeHddMYoPeE/T3uTwdtfvJv8SQgDaVpCsobvdJ3q9Gyeulohxq4t/JZ4CQPAI1kQwxjQYogfv3+z0Li3K4r2mdtiC12bz3+90fzB0rHw0ZoMu8w3TrLpSJXgtd1yY5egCGzH+9Jww5se8Q=,iv:uxuh6DplyEj+Xcda+KvPcJhlTmfPnTA+6qNL8oadlVk=,tag:xvilR6sbOn4lB3MXORVIvw==,type:str]
    VAPID_PRIVATE_KEY: ENC[AES256_GCM,data:RHduzmoqQv9Rpdtks092N9K3Ph+Wgvu19CRN/8cxO4JdR94iO9qt+svgDg==,iv:UMV01JKyXUONz3PvXKhFF1fVHifx+urxu2KJzepcjVw=,tag:lqFyi+QQuXVQ65ssUWJtWw==,type:str]
    VAPID_PUBLIC_KEY: ENC[AES256_GCM,data:zgv5Zh6q1XuIqBILeLMSauRRwdUjlBhutZ9L+T1LoDdMm5+ly/ty9fay1bFvAZ8hM/SGMmXp6Lt8favWa6bhgTdUkzTWO+k9h5/V3j2feo/vX/yI8mAb,iv:DXrQDaxGA7HpLfpOGnGyuZ4S3IfCLjVNDaECFWRBdaY=,tag:XjGRpGH4rP8WiGjiFhLd0g==,type:str]
    ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY: ENC[AES256_GCM,data:0QwIVdiFp8uefbP9k+xR0Yyt7s45kgdNeGMKYW6jPIpyocWMIBov97r7KR8=,iv:kZCDG2Lu0rxm26nXyrgFbRgwd1C8S0Xuy4KYKoAkWJk=,tag:5VafGqzl1XkeUx2dHJ+CPQ==,type:str]
    ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY: ENC[AES256_GCM,data:jGlYOR/g3aJq7z9oF9hVOqCR7oZnmLCRBZLxP6MyRe57yCBSUY5fSATAdV4=,iv:2xDCh2Pkct+lxT/E5CLuUoQWE1IWt+jau8eI8Qp9xO8=,tag:/Egy85foBQNhiULlSXZa/A==,type:str]
    ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT: ENC[AES256_GCM,data:+oc3OZ1Z/wk5W1OXX7gs0kuQ722rKuQkBJvE1wni1uzzXJ3QsdhelnELkH0=,iv:x+otMNNLLtP/4m5akodl6Ha7SZlxc6YtVC5zjJVL7v0=,tag:F2k9KAEkS9ngZQ1bqI8vSA==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:NiEBnr50WAqMFmEJWcyblOOpi8Q8uunm163ItWuKKhRB6xLAtEA+sQ==,iv:cLNpMMg7w2bjdd7y1szZ3GqNAZ6C/fCkaJRB9qBRS68=,tag:UFIWH08Z+rIQLNGMu1vuLA==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:3+90BCkNcBDSfGWlxisNWH9lqgXeyRkPxVdRv9o6lRPJwXi59TjhTygviuKTFDajYG2fzJmv4yVJ9sS88X80bgLMHW/EryYXHAoNeJFUrppffDsrbN8/R2rpe2fzfU3ojrjLpRkNggkriSCcFKXBotZZ5LUQBVJ2GTwXP1vdub8=,iv:yvqaUrqKYS9QMyM8Hdztq6Y91bENBY+lztJ4Pleexjw=,tag:QLY97PUpgncQ+mk/yu9Stw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlaWFlQVFxWDQ2L1poVFFW
            Z3JSR2xUVStxMktkOHpZYkpaS0M0K1dGeFFjCnZRM3VkRGYxR0cweHBzNHJhRDdL
            RnRFMWJZQzdPOEJOdkQzMlppbEdyZkEKLS0tIEtMOXVaeFFRaG8raXYwK3p6a0Na
            SmxWMGhYdlZxR0QyV2RkcnBSU2xoVzAKTyg63Yew+yIxcA8Z9PvjcaiS1GUF12+x
            UeojB6qGrvdyDg8jU8G7yYySlb9LKCarSgR4joRxiw/5THrE7PpFKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-03T10:23:25Z"
    mac: ENC[AES256_GCM,data:SxOiLa2LtALnueasKTAhPdcTZCRPCYaebeBmE6VnKuBlUaUNXqqkD7YBt20tqPaBQDpnW1jjZNGAxROxNWrc17mZC9yEO2PsgGjBQpJzJHCESJHIGvwxiNvq/ockJ96z7fGA57E2uLQg+ITr/5wSza9d6pTF/WR3ErAXD3eh81k=,iv:Jw3indrXPCRigTUpji/DzQFSgPTb8e/XZ8Hcts3lE1c=,tag:fxHMWNLAmZL/3wCMWU0Igg==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
