---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama32-3b
  namespace: llm
  labels:
    app: llama32-3b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llama32-3b
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-sdk: "true"
      labels:
        app: llama32-3b
    spec:
      containers:
      - args:
        - --model
        - meta-llama/Llama-3.2-3B-Instruct
        - --enable-auto-tool-choice
        - --chat-template
        - /app/tool_chat_template_llama3.2_json.jinja
        - --tool-call-parser
        - llama3_json
        - --port
        - "8000"
        env:
        - name: VLLM_PORT
          value: "8000"
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              key: HF_TOKEN
              name: huggingface-secret
        image: vllm/vllm-openai:v0.8.5
        name: llama32-3b
        ports:
        - containerPort: 8000
          protocol: TCP
        resources:
          limits:
            gpu.intel.com/i915: 1
        volumeMounts:
        - mountPath: /.cache
          name: hf-cache
        - mountPath: /.triton
          name: triton
        - mountPath: /app
          name: chat-template
        - mountPath: /.config
          name: config
      volumes:
      - emptyDir: {}
        name: hf-cache
      - emptyDir: {}
        name: triton
      - configMap:
          defaultMode: 420
          name: llama32-3b-template
        name: chat-template
      - emptyDir: {}
        name: config
