---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: libretranslate-data
  namespace: translate
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-cache
  resources:
    requests:
      storage: 3Gi
