---
apiVersion: v1
kind: Service
metadata:
  name: libretranslate
  namespace: translate
spec:
  selector:
    app: libretranslate
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  type: ClusterIP
