apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
    annotations:
        meta.helm.sh/release-name: tailscale-operator
        meta.helm.sh/release-namespace: tailscale
    labels:
        app.kubernetes.io/managed-by: Helm
        helm.toolkit.fluxcd.io/name: tailscale-operator
        helm.toolkit.fluxcd.io/namespace: tailscale
type: Opaque
data:
    client_id: ENC[AES256_GCM,data:UWYIir3yeTqV4g8G2NEkNWfAEoktt9o0,iv:Y/vzpZ88uY4RvDop+6gZFDRwnPIM6BD2qx7HLlL5PYI=,tag:nsAv4J6ZDFAganAcuIy8Fw==,type:str]
    client_secret: ENC[AES256_GCM,data:z/5eMAFStvaB6SvEhID3ouo9RybffAsiQOMllLsMuamxXVhExXUHitk/h1CEBAZla2tZDV9O1KNerD6XtayjU3z46k3Vr0sXl6JpwZFRt3yYwLT9C2wJHg==,iv:ACqLkNtGR4OS8m+XcCQRT8wI+rjphBUQ+MWV5mK9mNc=,tag:AhpFOyBQma0PoS4y51PKdg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVHhNckd2TEoxSUU0ZGFm
            bkNJWG95L3Izd1ZWa0kvOWtPV2w3NUs3M2ljCjdZL1dtRDVERkhoT1pIbzc1ZEIr
            bzQ0OFNXMHY3VGc1c3ZDZ0NTS3lmNncKLS0tIHBqK3NVaDd0c0ZaS2NNLzZ5ZXpl
            OGZrUUlENnRRb0JxZlUxR282bVNuY2cKvROYCZf5cQl0cWK1UNjFTcrd4eyVjWGY
            W7KMLusht0JX14n4kOmin+uF+FlT4Wo+u9ua3V8+a/Vdm02KiC7LgQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IFJTSlJydyBBNmprd2Jx
            ZjZ3ZkkyOGltWXdrY2FGcjBpdk5YM0k2dGJ0WlNJLzZKUjhLOApqZWtJb2NCV1RN
            Y2ovakdlUVFZdGQ2c1k5SFg4V3RnQmh3VWM4VllqMEUwCi0tLSBwWE1mUEtrRGdC
            dnVjWjZOTVhSWjFIYzVpbnc4ckM3RHI0aVB0ZWc3ZTlRCnfv9s4tFiYEjxLbwBk/
            Z6AMe0HZmtI2vXyBhuqNbY3Rt64uagRKVdwxjlKwuple+Y8pZQFJAEMM4Wz0Gpzi
            xII=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qgn7ll64pzy4wd64h85xxq386cexa98676zw4raej9rvxl822p782xrjn5z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDY0dUwvQSBBODErQ0E2
            TXF4NndjejZPTktLZGRUb0dHVVc1aEVEeWJOS1JUZFJLZXh3ZAorVTlSbndadWhp
            OGcwdFFSR1NhcTFpZjZTLzFxZDZ0OFUyNXRiZnBpc0NrCi0tLSBIWHpDaXNKSDhT
            amNHVmpsYmxESlNoK2ppUGRWMGU5TlFlUFozUnExK01VCh8AK7+r8l/ol7xuv3ST
            uW3lbYTDgQFUDhsNmjigLpc+0adzC5btr9TxEwHlHATg5AyciixkFglboGhe5CNK
            moA=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtvpgtvl83qxn5kferysjnzrt0zs2svfygeuvqznlupmvtepcwv37v7pace
    encrypted_regex: ^(data)$
    lastmodified: "2025-02-26T08:59:15Z"
    mac: ENC[AES256_GCM,data:Ykz7wtREj9s7hiwmVWmV7UmoqjbyhqgmWBmKY7F65wu+oXdcI6kbe09/S2nk49YtdwvXFPqSmtfVYYk5Hh5e3MeaPjEr1omDZ467zT9/p2YVmazg/ums6xwJdNl7L5VjQiB+psxSo4mKsCxtYKc/65Ud5krazcyrNqPgwd68fjY=,iv:n1zCaez94StnaeYcLQUNz8/uYEfAYldPeYnIpCHReeA=,tag:ab8tUHn/FzalNhc9JLz1pw==,type:str]
    version: 3.9.0
