---
apiVersion: rhtas.redhat.com/v1alpha1
kind: ModelValidation
metadata:
  name: demo
  namespace: llm
spec:
  config:
    sigstoreConfig:
      certificateIdentity: "nolear@redhat.com"
      certificateOidcIssuer: "https://accounts.google.com"
  model:
    path: /root/.cache/huggingface/hub/models--ibm-granite--granite-3.3-2b-instruct/blobs
    signaturePath: /root/.cache/huggingface/hub/models--ibm-granite--granite-3.3-2b-instruct/model.sig
