---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm
  namespace: llm
  labels:
    app: vllm
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: vllm
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-sdk: "true"
      labels:
        app: vllm
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "gpu.intel.com/device-id.0300-56a0.present"
                operator: "In"
                values:
                - "true"
      containers:
      - command:
          - /bin/sh
          - -c
          - |
            chmod +x /llm/start-vllm-service.sh
            /llm/start-vllm-service.sh
        env:
        - name: VLLM_PORT
          value: "8000"
        - name: MODEL_PATH
          value: "ibm-granite/granite-3.3-2b-instruct"
        - name: SERVED_MODEL_NAME
          value: "vllm"
        - name: TENSOR_PARALLEL_SIZE
          value: "1"
        - name: MAX_NUM_SEQS
          value: "4"
        - name: MAX_NUM_BATCHED_TOKENS
          value: "4000"
        - name: MAX_MODEL_LEN
          value: "2048"
        - name: LOAD_IN_LOW_BIT
          value: "woq_int4"
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              key: HF_TOKEN
              name: huggingface-secret
        image: intelanalytics/ipex-llm-serving-xpu:2.5.0-SNAPSHOT
        # image: vllm/vllm-openai:v0.8.4
        name: vllm
        ports:
        - containerPort: 8000
          protocol: TCP
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8000
        #     scheme: HTTP
        #   initialDelaySeconds: 120
        #   periodSeconds: 30
        #   timeoutSeconds: 5
        #   failureThreshold: 30
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8000
        #     scheme: HTTP
        #   initialDelaySeconds: 120
        #   periodSeconds: 30
        #   timeoutSeconds: 5
        #   failureThreshold: 30
        resources:
          requests:
            cpu: "50m"
            memory: "1Gi"
            gpu.intel.com/i915: 1
          limits:
            cpu: "2500m"
            memory: "12Gi"
            gpu.intel.com/i915: 1
        volumeMounts:
        - mountPath: /root/.cache
          name: hf-cache
        - mountPath: /root/.triton
          name: triton
        # - mountPath: /app
        #   name: chat-template
        - mountPath: /.config
          name: config
      volumes:
      - name: hf-cache
        persistentVolumeClaim:
          claimName: model-cache
      - emptyDir: {}
        name: triton
      # - configMap:
      #     defaultMode: 420
      #     name: granite-3-3-2b-template
      #   name: chat-template
      - emptyDir: {}
        name: config
