---
apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-config
  namespace: paperless
data:
  PAPERLESS_DBHOST: database-rw
  PAPERLESS_DBPORT: "5432"
  PAPERLESS_REDIS: "redis://redis:6379"
  PAPERLESS_URL: "https://paperless.klimlive.de"
  PAPERLESS_TIME_ZONE: "Europe/Berlin"
  PAPERLESS_OCR_LANGUAGE: "deu+eng"
  PAPERLESS_APPS: "allauth.socialaccount.providers.openid_connect"
  PAPERLESS_SOCIAL_AUTO_SIGNUP: "true"
  PAPERLESS_SOCIALACCOUNT_ALLOW_SIGNUPS: "true"
  PAPERLESS_REDIRECT_LOGIN_TO_SSO: "true"
  PAPERLESS_SOCIAL_ACCOUNT_SYNC_GROUPS: "true"
  PAPERLESS_LOGOUT_REDIRECT_URL: "https://auth.klimlive.de/application/o/paperless/end-session/"
