---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: redis-sidecar
  namespace: paperless
spec:
  mode: sidecar
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.150.1
  config:
    receivers:
      redis:
        endpoint: localhost:6379
        collection_interval: 30s
    processors:
      resource:
        attributes:
          - key: host.name
            value: redis-paperless
            action: upsert
    exporters:
      otlphttp:
        endpoint: http://backend.observability.svc.cluster.local:4318
    service:
      pipelines:
        metrics:
          receivers: [redis]
          processors: [resource]
          exporters: [otlphttp]
