apiVersion: v1
kind: Secret
metadata:
    name: paperless-secrets
    namespace: paperless
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:5hTwsLxpZy4+,iv:n7ZxQYzYS5vbVQKmOivsz7114lIYCkS5zeXIwdjNEII=,tag:ch/ZVil6mXSb3mp7IzhNGg==,type:str]
    password: ENC[AES256_GCM,data:5ycFk3CRI3lz5xmjahOt1qpOUSVDwCM4dVo4ArPoZjA=,iv:fgRJdn4d1l26iszi6rlCya2k31r4XK7ERzVZ5GxFlDU=,tag:ty7zxyUosjGO4mcCcg0gYw==,type:str]
    dbname: ENC[AES256_GCM,data:SWeoXHClez/j,iv:zzINdbhX3gLJouOXlRxhYlJak577Bh62+I2XgFuJezw=,tag:zUqi5AdLxS0z9eB3aPbiSQ==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:UgeuZ1DaBzbDKb25Of85qwvWoptcACVlIioj+bxB7sc=,iv:P5lMxwVsW5xFFOYccy6keHUnuHNZu813veb9zGLukuA=,tag:2PGAsTTZ5hiWzzDrY9GCUg==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:uKLC05l2Lw==,iv:LSlyBx1D5uewFcUrupGZ2n6flJLYNkzZv5dEDjRkEcs=,tag:qhOdkfqxHTISv+VqjKRkOQ==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:4DeFOdYweYBdRmYNI5LSLu8u670NQ4StWGiq3/GMtfY=,iv:KB/4JGRMT4TqLtQcWuZEfd86IlhwfvyMAoxuzmARTaQ=,tag:MfNFe3cUz03KGyfwaerNUQ==,type:str]
    PAPERLESS_AI_API_TOKEN: ENC[AES256_GCM,data:om5OtLuKjN49ZguomsE4fcW+wd6oH67/tpJqfxSw7V5zwunBHDEa/g==,iv:3zfPvg2SDSbRWlr3g57Cpqa6msR8zZ607A+B7gboOyI=,tag:pYOvG4ZF7d3nvka6Olfffg==,type:str]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:swvWZl73Vqx08aoN2J6XEVZtPg3I0HzW/18dNIewIEqMBKh+ZtdXzIVYPoajg0MAFFrtEYlwZe25KbpZ6xHajzz8tTQukxbpl92ckmHes4plYdsTZbhNgaKwYd2zwcljfTJaSzgS1j3f45BYSQvhXmW8Grqu6bS7r+PM3S9VqM79kuL2B/VrYBgTmrWUx7mtQoG5QQ++2cJnDCCRfPMrPwm60FKDo8pDuUlzLWe0dBGmTgvnlupllqDdJW2oiYYOCUmuBllPb4F2ghhmo3JKN2dOLnICuTLwUiA/oFB1/E1cJsSFKSF8Bv+2qfmMyYFcGmSmOJvinv7Eazvj24sj5c9tte/Gb+QAfaujyHBFzXaeovqYmhj/r92LKYgHPVBwjob2dbD3p/Z67+7uQdM5XmrfV7T6vnSh6lQO7XJEsM7fVK9R1ZWxlNptvEdFHDVcCTHk+X5yuUMct5XkhsQsIbevjFqUmeAX+yifda6GVtWBo6f6ikYFhlrHztifFK0pmXEZeM+oo8BhEDEc7WdB0LLbsMjiOD4eSD8fmzFYCy8yinr1Qy8czLMWoEOqyGxVtwLMLzevmGVw9z4TFRFM3KSORJuhgefynLExkwAwBgwtTvpW8PMjQX1bdg==,iv:RCvdAyIO7Cd4xn9udREXt34mD+vO+QgfMgg5kqAiLCQ=,tag:W/8ckJ6/nWwoFkGqMecRXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdlYwNGtZeUZvOUc5bnJ0
            bGJhQzluYTVabng5VmNlbUZYaitBOUJEM1g4CnRjVWhMOG1FcjNyOUNMS0g5RldT
            V1ZWSHBOdTgyVkMzZE9YOWlIa01kRkUKLS0tIGltcUVabGRka1NxRjFaSlhEdzZv
            dy9UUDFnZnFFY0ltc1pOUHZmNjRjTGMKa34DUfkYI+G4zaAypXCEGCzM0V7xERDl
            PTJud8WIbeK+zOG0ieCAcSVfbIA+zyWhHVfD7RaN3RyoZnJiKIQSPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T12:05:51Z"
    mac: ENC[AES256_GCM,data:DMLlM6x0U22ObdMN0eCgLts/H9sRUNaNS8vCONUZJQgCmvsPxbSgRABzYm2g4ZwsOsjsYf0j1LKajsZBEu82XmBdEm9HPfrPUiqx557dxnfR2vfRuE7QlYnDTj0zOaGrMINsd45JlZBRQPxKIavJkBhak3p39igsn6D7LJFJWlQ=,iv:T7rhghCLaOSEMtXnSHQKKdUpKaQbW2dJrZRiDftQU5g=,tag:l+iVM8BPBOY2EFMKE5DuYQ==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
