apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token
    namespace: cert-manager
stringData:
    token: ENC[AES256_GCM,data:FtvP8R4JLCKpl/Tryj4dt2ZzEwC2FjzcNO4QmUBRGmLMuwPguIpp/Q==,iv:Azl0rYQr8+qgkUl65tHoj1oAGelVe0e18fyT50BdWxo=,tag:Uny7+ZZcHyfaG/YsCN3Q8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4L2I1OHVNdTd2czlMUWkv
            YmtyS0dBVjRzNDJHN2JSNEhDVjBoRnVRcHhVClczR1ZOWU1lY24xWHNZNzl1T1VB
            ZXE5dGlzWEFqTzJJRzhpMVZ1TmtWRDAKLS0tIDgrQ25GT2s1NEZUMVZWUXdpTUZY
            ZzZPc3FhSEdBVThBc0ZKTUJmUDRWWmsKemN7UxZaVEIyuuc8Yzs/833KfOGqo5Nx
            C133I8t9d1tV9Bv1zrfT3QLf7NyUud93nT6f3qxAF7CsUAeN4u3vxw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IFJTSlJydyBBczlaN0Vp
            MTZIeXNYenljZmd3a3l2Z0dBZ2pWemd0NmFUZGkxOTVLZ21hTwpiZE5mcjc3Y0h3
            ZStKWmlPcjR0MmthNmhzVDZSbFRqYnVMeHBzOXQ5RDZvCi0tLSB0NkFKQm9UYlJv
            L2dDbmNXNG51T0RJYjU0cm0raGJucGcrOHNXN0x2UUgwCggTRCWYIRk88SAymsRd
            rGjgHbMV0lXMsjSWejI3CWIVx9vlBFlZ2+AM/h3jOCT9/m++JeadQtGgubBSBP7p
            fQU=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qgn7ll64pzy4wd64h85xxq386cexa98676zw4raej9rvxl822p782xrjn5z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDY0dUwvQSBBcjY5RlRN
            V1ZscWI3Nmo0SmlteTVsY0ZUUGJwNGxmdHhaNmRlNXJ1KzZFOApFQnFKVjhyaGNv
            cDNXSXlsdWM1aldUdzhqZnZXU0xQN09WTm9pRTFVZEVrCi0tLSA5UVUvUys3aEtO
            Tmg4YUdnQTZPUU83OWdUTzZSb2VNeWwzcXNLUGs2eGFRCp/p6e8lFg/xTKrx3gtY
            q2IUJe0du34BVtQPl0BxDN3Bae0CgFbVFvbgGKFuykaMVOasqTkVci7GghocsLyO
            igE=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtvpgtvl83qxn5kferysjnzrt0zs2svfygeuvqznlupmvtepcwv37v7pace
    encrypted_regex: ^(stringData)$
    lastmodified: "2025-03-22T19:36:49Z"
    mac: ENC[AES256_GCM,data:DNhVW2fFLcoaJun1rvTLqTTr2tqA7ylqDoxTo37Vhxag8cz/2hrfwi/Ail+DxRMFJehU+6yizwMr6t1ShPQJJ/t/WPknB9lIow3FwfMBNxbZf2AM0EMUNqNtQkUi4c1eT9/2WLhZvKuj97cT+cdCiEY5lQ5rBSZ+X8o2nVJLWXM=,iv:WhiwUjQcCU6VStOmYV1zEjRxNhKbIfiHgSmKd+NoPug=,tag:T2Zx17Ksk216oH7hartPOw==,type:str]
    version: 3.9.0
