apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: ext-fewo
data:
    tunnel-token: ENC[AES256_GCM,data:wg0O+JHc+mAXfo/yGih3BkgUYqMcaGT6QHypy39cNnI5VMj845oe1OYKi1Njt4s+cl85ArkDsTfxD8vvrsd/rrU9g6oR09sB6WP6pM+TgcdDiVEjg/PqDc/mbDHFR0j7RQrdNX9EnDGdZmyBK0xRig19eEBoYdVKcGEiROr09BOhneqRwFvekg/udVNG1rMFHYcTjfqDLWps/aCJXRQ/DKTDQS3jROEHW1r2ke3VAczxrWeOYpUzvPyFEtUMY9OleQsEQlkxslNq+cPjwzp4Q7jqJLC0JRhqZjvvql7iWWByGpm3eG9VDq45iU/nIIGcSYpb/gh7E/M=,iv:xMmES81rWbOrbNJvoiuvhTlfJBMePzIzUA40aVHPbCE=,tag:HbcmRuuD7G8wfOOwCf7aCQ==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHY1dVdmFYcWRRcUIvQWt2
            cktNN1MxRUxqK203bFQrazRNZk1sOW1UY0Y4CktLL3dsZnBOYkg5RlpHNlI0NE14
            MDRBTk1XNXE4MmRyRXhJd21mbzhuZUUKLS0tIDk3VWdLajE4RnZPdXA0anFIajVx
            SFdvamdvL25PVE4waTZjOGY5WjF2amsKBXMUISbXTcxHWD3tl8JTUnuF53G5fYb2
            r5+HP1d4JLifN3pL/9q3cVAE8AspSryU713fXwmYWJW9bCtOX37pOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IFJTSlJydyBBc24raTZT
            anJBNXRmMmplK2xnVU9iTFFxMVpCWHpQVGFxcnE5QitmL3lTeQo3b2RjWUNHTnFx
            VnllT0I1NVBueCtPeGpSYU9vM2tHUFVWR3Y4THVrNXhZCi0tLSBjTWJjV0xDdndG
            T2ZhZGRsd2w3ZVZDbldGZCtxM2pGUzlTNmJ0aTFhK1ZNCvEtuB02Ig+Rl4bJ9h4O
            K5MjpfbhBdXPl0JDLXkHoz8phsQdxE95BTYTjTu57+1LQfJJvwOE1LGuA8AOd0FU
            GJA=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qgn7ll64pzy4wd64h85xxq386cexa98676zw4raej9rvxl822p782xrjn5z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDY0dUwvQSBBd3BxTDM4
            R2Zld00zYkUvZllVUHo0S1ZVRk5vZ1pGd2VnN1NTcExyelRZRApLQ2h3QzVkaFdp
            UXZxME1sQytIMHlucm12U3Q1b1NuNTNwdEh5QUE2aVFnCi0tLSBIQSsyaXpESGlN
            eTJacmxMUFcvbksyUENJMTVGL08zM256d09aeXoxT0RZCnryiHUGoa6hKiA1QWTG
            tdwcWvTddBgDb7SmcbD6h2NjA1/ruqzC425C7+MKtEJdNVAyLHq/nd4/5kkl+i9f
            kaI=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtvpgtvl83qxn5kferysjnzrt0zs2svfygeuvqznlupmvtepcwv37v7pace
    encrypted_regex: ^(data)$
    lastmodified: "2025-05-28T06:59:43Z"
    mac: ENC[AES256_GCM,data:xKgyvJZ83NS7v9ARruJNXYCJn482CGdzhVYhAV9I7mnQS9yP0nhgn7NyVAQ71dCdZ421vkJI7UtD3WTmrQ+Dh09Y4Qis4WBVi888ZH2V6VIZlMJeR4385VmhLAyFFGte4Q2MU25V8QhrAx2omQfrBxJzraBW8NkPGZzmpbT8c5I=,iv:fnjOlH2B46dqmdV7oke+a1EH6MjrUNO9YeSHXkV2IPM=,tag:0s+ykfdzjeL041Uf2V75iQ==,type:str]
    version: 3.9.0
