---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fewo-cloudflared
  namespace: ext-fewo
spec:
  selector:
    matchLabels:
      app: fewo
  namespaceSelector:
    matchNames:
    - fewo
  endpoints:
  - port: http-metrics
    path: /metrics
    interval: 15s
