apiVersion: v1
kind: Secret
metadata:
    name: tailscale-auth
    namespace: flightctl
type: Opaque
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:4ny9KCOIfb5ehQ==,iv:veKR1IPI6FXLTWS1klsFW0E9DeIUIAmG5R4LMogOc80=,tag:htDxjxLziODq6RKphyE54Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0TG5PUE1UL2pIeGJSUU43
            N0tNajhicjlPWDdVSlpLdStSN0QrT3BHRzFNCmZZdTJtbnBxOE9UczRQRk1uYzNS
            Y1dsclBmaFlPZ0Y4NHp0VE9vcXNmc00KLS0tIFhjVFNWMkc3L3JGamhneXZ5UzNq
            N0l4eEhRM0ViamdEbksvM2xOL084U28K9a2ipKx1A9o7YeQDqwbE5oEhIr+scXU8
            vGg97uZCZ4ud63ZQI0olM29HaofMGOhQ/cbeOeBYgoKVS0/sKQgyeg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IFJTSlJydyBBMnlrY2VM
            WEIzdGNJVmtYQm56QmxnUkZackxVdHUwM3NhWi8yUWNNaFJvZAp1alFIRW9ORzJI
            TC9tZnhQYWMzUStYaS9kNk80OEJaZE5MTmJwZGxtOUVRCi0tLSAzOW5VQkViSVhR
            VVh3dmplNUkwK21Fc2h3cGFjVW5tc25TRmlSK252NkZRClSMEtKgoZvvO9TklU8d
            KsyQHimQe50z5gXC7N90TFUWOzaFWh75ZYsMgdhSP5G4FHy5m2h1HKKlsiRvihPl
            2MI=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qgn7ll64pzy4wd64h85xxq386cexa98676zw4raej9rvxl822p782xrjn5z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDY0dUwvQSBBb2xZdGtu
            NytUcWRXY3JxNmgwbTVhT0xNd1Fwb3pFTjF2TkptUjZzNGo5NQpHTjFaSWxUTXdm
            OEZ5NjM1d0d1TDdTV0Jzd1JkYXhTMmE3bWdRQStsVVNFCi0tLSAyWVQrUlV6ZzJC
            RkR3SVVaaER4aFhqL3lTc0hiMmFJUTkwYjFmME92eUtjCiw27wN9PgXC/S9tFzei
            8RPBfZZ2im6RdoHtxuvqdjkvuWF9nYXw1v9DQA+Jk7JWIueTSRlylP4g/KwifAR5
            T6w=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtvpgtvl83qxn5kferysjnzrt0zs2svfygeuvqznlupmvtepcwv37v7pace
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-06-23T21:53:33Z"
    mac: ENC[AES256_GCM,data:rYLsT3lLDEH7BJWuLx5/oTVM/EWHIDPptV+l05Y7A1qeYHzzHN+hG2OA8OnQaJFB4fyVgZQqHQiAFUlKR3GKDsVHp+NZjpAwhw0hF1J6kANOxUsJ3Fdo+cYZawBBrVyjy2vXlnA2gn1nZ6+JjQiiZqKkamh7zIJ7TUOKjuJdKJA=,iv:nvHhhY4w+u5pzVcum/XX+uddPoH8hb4YoXSGdP8V+Mo=,tag:w4RN2h/8efd8N9Wak2K2TA==,type:str]
    version: 3.9.0
