apiVersion: v1
kind: Secret
metadata:
    name: tailscale-auth
    namespace: flightctl
type: Opaque
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:4ny9KCOIfb5ehQ==,iv:veKR1IPI6FXLTWS1klsFW0E9DeIUIAmG5R4LMogOc80=,tag:htDxjxLziODq6RKphyE54Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3L2NUWVk2OTR1WGZyRnl6
            N2grWFlucWlRNC9NdEsxbitXM1phWWJQeWxjCnk1VHc0K3QrZUxGdkpuS3VQYW5E
            SWdOcXRMTkg2VHpHWVRQdWVxcjdYRjAKLS0tIEZLT2hxbS9pbHpqOUZyMnFWTHk0
            Y0dYUUNnRVNMekkycExNYzREN1NKMncK6MRl3IQLfk0z80y6niUf6if+CYQVshLE
            9szhGJu2Sl6t54HblBLSY6Asa+ks543v81U2fLId437GjzS995R8lQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-23T21:53:33Z"
    mac: ENC[AES256_GCM,data:rYLsT3lLDEH7BJWuLx5/oTVM/EWHIDPptV+l05Y7A1qeYHzzHN+hG2OA8OnQaJFB4fyVgZQqHQiAFUlKR3GKDsVHp+NZjpAwhw0hF1J6kANOxUsJ3Fdo+cYZawBBrVyjy2vXlnA2gn1nZ6+JjQiiZqKkamh7zIJ7TUOKjuJdKJA=,iv:nvHhhY4w+u5pzVcum/XX+uddPoH8hb4YoXSGdP8V+Mo=,tag:w4RN2h/8efd8N9Wak2K2TA==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
