apiVersion: ENC[AES256_GCM,data:Yr8=,iv:xBIpP2AVFRaLK7ei5zTR5mIbmAx166PqDYpMuwsTTS4=,tag:O2we10rpo3l5p1ezsmIG4A==,type:str]
kind: ENC[AES256_GCM,data:+bamwW7I,iv:sIAXG8i9LbQ0oq8Btd9KHS/KFAPmgjGcv7GG4bBUBq0=,tag:A6X3wTfG1joXVUrdcRRSxA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:x22oncNvaaReGewMdExvTWA6,iv:EZCNhwk1extU5AqiSzjpK8FPZ0qdSJfU7MaLrw23wZI=,tag:JYqjgP+GTah67DFTkzbYww==,type:str]
    namespace: ENC[AES256_GCM,data:I8XlR6k=,iv:B9Fuh8b1bZAZRGCTuDKhVF2KYmGdkSd6DhXimNYvbB8=,tag:hxanitNjM/YmLbF3oCIpAw==,type:str]
type: ENC[AES256_GCM,data:udHIkog6,iv:AX+b2up0qlWN5QW82o6Bp8IiYSS7saZuzrd2ubPVPBw=,tag:pA8YOC783OyAxY/dohiYMQ==,type:str]
stringData:
    tunnel-token: ENC[AES256_GCM,data:3OVO6jHMmRS74EnT3Cls8Mql/Z0axO6Y+v9mPxmpB6S9Xbuz2ilKs6W9BJiCyVpmjrWGH2WPUMHGimot2mIkBAs/VLZW5TRBzZfHxO21i9a1nnyKQOG7lvKgiHOnwFReDcZq2zKxCJuJ1Vrg0kziOLtTLw4U4msJZ0evmoGVSdv/1kwE9q1M9bNbDlvVZxbMxrgkll4x8rR+kYMcgcHUA67ek5TIkRlTGWXNekkG/bgmgtNgUgHKiw==,iv:IAlXMeYZJr8/CI6FnfONWmU4a3avgDsF1rmCHmmj+nM=,tag:u+UBDqxzb3DukQ9QzairEg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YU1NV0NTcVNJOWtYL0Fv
            T3l1cDJDaVNpNlNnZlZGbi9Hbmx6TkVzQWhnCjY2SjZ4RExzSHFWOEV2TUQ2c1BO
            UEJrTk8zQk4vdFpVdFVJTUEyNG0xZzAKLS0tIG5FR3ZRZHphWUFTWURFeGViWklo
            RW5tN0R1d09Ha3BKUzQwd1NsL1RneWcK19UotSgaPmslsPGpfjzELcoAXBPwVUA8
            z7lSvb3ZbkREMzGbA9yrDsvnX0GQ45M0FzDt6+N2drIVdUoBGdpmIQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IFJTSlJydyBBdmtwSHFY
            TFZQWEg2endIelNXQWZoZWlQSEFObXI2bTI4L2xXVnNOYlRGdAp4S1RkeWRHSlZ0
            L3FhTG5GR3BEN3RSQTE4eEFqbkpJRFA5TG12bzllNjBJCi0tLSBCdW9vZllXcTl3
            YVJ5WUZCcUN1ZWptVVN1TTdvU29YSDhiTEoxY0FsNzlNCtLUkXdzkBwMdoCK2AYo
            sPx6A4g02BaXvLs43p/SEErtBcrdwN696pTdpvyTyB3wA3EQB5eZs4ZbjvOq62bJ
            hj4=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qgn7ll64pzy4wd64h85xxq386cexa98676zw4raej9rvxl822p782xrjn5z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDY0dUwvQSBBOG1STDVz
            dEdKYmR3NGs0RndWcTk0Mi9rWENTdzZUbTBLUEhoaFRZZlo2OApGbGkvMTd4QkN5
            OE53Ung2N1haaE42dHNsTGdnRVNaOE1JUWxEQWZJRzA0Ci0tLSBldXZqeDdJRUZx
            b29JWWdhQTNzMEZEbXBPSGVqcmZQUXV1YUxaYWdZaGQwClNxNtehruQRQA4dXNsx
            JpUz/QlC094wzL+fIjtgZ/8PKMDmKP7PFzA2oE8+L6wUt5r1yTCri+R7GcDPT0mV
            +sQ=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtvpgtvl83qxn5kferysjnzrt0zs2svfygeuvqznlupmvtepcwv37v7pace
    lastmodified: "2026-09-02T10:21:52Z"
    mac: ENC[AES256_GCM,data:3oxx4i06wPSP+6cRs5BT6unQSVGWe+AeIk9ux4UbejBte+bOB1eUJCzfTp0UIQ1nxariB6XuunLfDeg5HivA3QhbUhFebXH7pZ3eNI+69cwt0aH9Hh4ywC/Qt0EC115fVaqE85TtmAbHf05/2CVFkAp8QcQIQnn5LyNHXDQXmoI=,iv:dkdmueZ7V04aHrdZzShb/n8+6WUPdZ/dKYxl99X9nnM=,tag:zW0ZmElJrbE556O0EhUTxA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
