---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret-mastodon.yaml
  - task-blog-content-build.yaml
  - task-blog-sync-build.yaml
  - cronjob-blog-content-build.yaml
  - cronjob-blog-sync-build.yaml
