apiVersion: v1
kind: Secret
metadata:
    name: mastodon-api-token
    namespace: cicd-builds
type: Opaque
stringData:
    access-token: ENC[AES256_GCM,data:iXEeWNS+t+tfEf0kwqQ3vWfjmG1Lkh7yt7gNDImj4dS4GBY262xBhptd/A==,iv:pCfv32ieE31/LeyRtbBjINfVv7xbD+cY/ZrjPiNIjpg=,tag:ALKlaHcmLd+BfJVmEbTd+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZXYwUk42cU4xMUhUR3hV
            SXM2QWF4dzVnVEp1RlQxL2NPOXlNUEJJRTFNCkF1KzdZVVh0SVUyRU1OVi9HSFNu
            eVZHaCtYSjduTy9uUlNOb0ROUnVxY3cKLS0tIDZJanloaFJQNXF3NGVtQzM2WXdk
            THhsVWhla0JFT2ZiY1JWVXIwUjV3UzQKW2kbYIVNLw4AYWLtcgDIP44eCmeI6/CU
            UWvK+s0sahaHZMTo/OGwPf5BDokFR4n7HWsIIqc3Z2OHKotwa9pkhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-07T00:03:01Z"
    mac: ENC[AES256_GCM,data:nBqF8QUirCDjY/6V78RUKHYlgfT2ejP/dsbBeENhl8bvdFe3V+PPoWZLCv7//uQD/iBgivTsuhqzFlc7aJxAelXpr2SmqNJ5YIDqkLed7nfdzR7BS3mpifNuzBXlapuvWaAIOVVvz1Js2M3RP/+KnfAQd7wY19VxbIsGdNnud9A=,iv:cya7DCPvN/fA7+do/yW0w1EMJoRd+oV+3YeOSwlIjXk=,tag:fMDfYaErRZ2KcyqY/5tgJw==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
