apiVersion: v1
kind: Secret
metadata:
    name: mastodon-api-token
    namespace: cicd-builds
type: Opaque
stringData:
    access-token: ENC[AES256_GCM,data:iXEeWNS+t+tfEf0kwqQ3vWfjmG1Lkh7yt7gNDImj4dS4GBY262xBhptd/A==,iv:pCfv32ieE31/LeyRtbBjINfVv7xbD+cY/ZrjPiNIjpg=,tag:ALKlaHcmLd+BfJVmEbTd+Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQzFiSUpJSEV4Q0t3dENL
            MVlUYTBzYkg0MUF0QzZGWVlNUDZ5bXhUYkZjCjdpWXJWUUxpcW44Wk5sWmhkTEpF
            VnlpK3hRek9BQVNicUNURE9Ia3R1K00KLS0tIEQ1aUZlV20vYWJGVlRlK3ZaaGxk
            clpXU1JUZGpOckM3SjFmSXFjaGk4S2sK9Pr0FmTTYZaGA0Jp2FDIwHOZWcr+tqoV
            s35vcBIKcyhynHOnhH4hD5+YQrJn4uRg4RRa9FoIEdtJ0s6d1nPFsA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IFJTSlJydyBBKys2ejJW
            SWJJV1NsOE15YXFtcUxLQ3NBeDQvc1JTZFFpWE1IWmV2Mml2TwpKQ3c4bU9jV1k1
            Y0FoK0xoS2h6czVhVEh3alVpNENHMU9zdVpJRmhBQjM4Ci0tLSA1S1JxcEZLRHl0
            SUJPS0hOckk1UU8rMTVqZThJbWIwbVVDY2dWc0dBYmxZCol4ZRHEHTsOb/1jtlFE
            L5LNqsWX9w39gY1G5Dsf0BMThHCfJCdspfQ56QIHlmG7S5G0czDhjyqi9UxNyae+
            Pq8=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qgn7ll64pzy4wd64h85xxq386cexa98676zw4raej9rvxl822p782xrjn5z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDY0dUwvQSBBbDhVYWhq
            S2JMRzdsTTViclY4dkRRMHFvVEEzUXNIWjRSUjBSS2F3WXM3NQoxWXJQYWlqdHpZ
            bFR5dFJNbjV2SytVRFdvME1obU1XaWkwM01pQWQzYkhBCi0tLSBhdXJUTlVubGw4
            aCs3U3M4WXRyNngxVm9LdklNWGdVbHNTNy9ZNHNpbkxZCtOfSL/fpWiWEP9nUHFW
            g8XcXBoMFe6aZUtHi58Mei1tj3pmnB+gP7r+b+CjewsQ1N1ysPxmnd9BUVNLXlOT
            HMk=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtvpgtvl83qxn5kferysjnzrt0zs2svfygeuvqznlupmvtepcwv37v7pace
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-07T00:03:01Z"
    mac: ENC[AES256_GCM,data:nBqF8QUirCDjY/6V78RUKHYlgfT2ejP/dsbBeENhl8bvdFe3V+PPoWZLCv7//uQD/iBgivTsuhqzFlc7aJxAelXpr2SmqNJ5YIDqkLed7nfdzR7BS3mpifNuzBXlapuvWaAIOVVvz1Js2M3RP/+KnfAQd7wY19VxbIsGdNnud9A=,iv:cya7DCPvN/fA7+do/yW0w1EMJoRd+oV+3YeOSwlIjXk=,tag:fMDfYaErRZ2KcyqY/5tgJw==,type:str]
    version: 3.9.0
