---
apiVersion: batch/v1
kind: Job
metadata:
  name: mastodon-db-migrate
  namespace: ext-mastodon
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
        runAsUser: 991
        runAsGroup: 991
        fsGroup: 991
      containers:
        - name: migrate
          image: ghcr.io/mastodon/mastodon:v4.3.6
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          command: ["bundle", "exec", "rails", "db:migrate"]
          envFrom:
            - configMapRef:
                name: mastodon-config
          env:
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mastodon-secrets
                  key: password
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: mastodon-secrets
                  key: SECRET_KEY_BASE
            - name: OTP_SECRET
              valueFrom:
                secretKeyRef:
                  name: mastodon-secrets
                  key: OTP_SECRET
            - name: ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY
              valueFrom:
                secretKeyRef:
                  name: mastodon-secrets
                  key: ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY
            - name: ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY
              valueFrom:
                secretKeyRef:
                  name: mastodon-secrets
                  key: ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY
            - name: ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT
              valueFrom:
                secretKeyRef:
                  name: mastodon-secrets
                  key: ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: app-tmp
              mountPath: /opt/mastodon/tmp
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: tmp
          emptyDir:
            medium: Memory
        - name: app-tmp
          emptyDir:
            medium: Memory
