apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: database
  namespace: ext-mastodon
spec:
  instances: 1

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist

  storage:
    size: 10Gi
    storageClass: openebs-crucial

  superuserSecret:
    name: mastodon-secrets

  bootstrap:
    initdb:
      database: mastodon
      owner: mastodon
      secret:
        name: mastodon-secrets
