---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mastodon-data
  namespace: ext-mastodon
  labels:
    k8up.io/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-crucial
  resources:
    requests:
      storage: 20Gi
