apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: ext-mastodon
stringData:
    tunnel-token: ENC[AES256_GCM,data:2XotKVJ0VR9efrwtOc0HIRk5KzIuhqGna9VDQwQRQzI3dKTIsml/g9OekHRMdHZLQr68hpcgw2wxOhc/+5tOPC2dRAhFCCkDii6iFPy9AN1FSS5/Nz88t2sdErDzdmA6XWMlmER7STfw0aaqXTa9cAOQjwy7d+obb9MKkEHJa6esBK3zTt5U1LDsNjzn8a87x4Szc4yjegyGdzJHMjagkELbI56SX41drvvdCgQgJ3fohOwqEkwwlg==,iv:xXtqJOFdEE/63NmmMD1rWAEo7FibrjqcP/IhT2fVOEQ=,tag:ug+DniGr5k+SQDJN9xysQA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCQ3pEUnlNRGo4b2s2bHJT
            blIwTktFaHZHeXJtbHQzeU1kRnJoTlNjMDBBCjVkS1VxVnQ2dXNQVnVFRGhxWkp4
            U2JNc1BpdXI5RjZQWmRLbHZmN2tmT1UKLS0tIForYXZkNEswUVd5a0VMKzMxT3Q3
            U2x4SjgzSktIZnFTekFLRmN6U0V4akEKnbtP4eJ87fputZs4gY9csZQy9uqT0TkZ
            rqmCmsOTvDgdG1vKKaRET2U8nECfbc0RlYtcM0bYWLyEmjWuew1auQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IFJTSlJydyBBelVTdUwx
            L3lpL2piSlY2UUhiRDdLSWlZeHZEMk1WU2t2T1NTZUxjWEQ0dQpCdk8wclg1aWdC
            VlNmOWI2SHVtMElkK3dibUsvRlphM1N2QkRYSlhJbUtJCi0tLSBLSWRQVUtocHJj
            NVprOXJLZExSU0VEMFFjZkZjenpKbXpybWNQMnpmYnBBCl7Fj6TPPEltkC29wikN
            7/VB7r5GBsFRiHu88CpTX4jnonLzPhoQVyv2gmrEGv+8dUU148UXddFLJaI/lfr7
            xh0=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qgn7ll64pzy4wd64h85xxq386cexa98676zw4raej9rvxl822p782xrjn5z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDY0dUwvQSBBckh5UmZG
            Z3FVc3B0clphZkFJby8yQ2w5aDdyUkFuMzNxbm83eTdYNTVUegpsVUx5TEFQRDJE
            dUU2bGROOUpOaGpaK2wvYzNuc0drWldXOVBIYUxnSlZ3Ci0tLSBZaEV3YU9lL3Qy
            SXAvSHNQcjBDQ0lEV09LMlVGTXl2dHFCUk8zenNZclhjCmaCcKAkXhDX35+qlJJq
            TtM638MuLTNaZc8Vrk6u6wJoT8UiQuoBfUz/6vLS43Z59dN16qpgMKMDfivWlBM3
            Kfw=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtvpgtvl83qxn5kferysjnzrt0zs2svfygeuvqznlupmvtepcwv37v7pace
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-03T13:28:09Z"
    mac: ENC[AES256_GCM,data:WqRNam+mJznPoEBS5Kk/wdeVbwTpzogGzqhg73lIthNizRFiAdqwaWoUkHZAgGSaFcq1Cvc2OooyZjj2BLrTaXn4oPljv7fSNL/IZTSqouG3n98EeR1lt63tZ82wDYVJk7s+MET3U+R7A5OfYJSggYTygKDIjDFbO/AwuJnga30=,iv:ytFWirYwfb3aG4tzBKvkbTsFfdpVHVH5idVQqM92Ckk=,tag:V4quJDFgYU5lDyWd9Mxvuw==,type:str]
    version: 3.9.0
