apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: ext-mastodon
stringData:
    tunnel-token: ENC[AES256_GCM,data:2XotKVJ0VR9efrwtOc0HIRk5KzIuhqGna9VDQwQRQzI3dKTIsml/g9OekHRMdHZLQr68hpcgw2wxOhc/+5tOPC2dRAhFCCkDii6iFPy9AN1FSS5/Nz88t2sdErDzdmA6XWMlmER7STfw0aaqXTa9cAOQjwy7d+obb9MKkEHJa6esBK3zTt5U1LDsNjzn8a87x4Szc4yjegyGdzJHMjagkELbI56SX41drvvdCgQgJ3fohOwqEkwwlg==,iv:xXtqJOFdEE/63NmmMD1rWAEo7FibrjqcP/IhT2fVOEQ=,tag:ug+DniGr5k+SQDJN9xysQA==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTFk4UWhDUnk3K0lqMmpG
            NkcyTzUraTZ4L25sTHNTaHNyT2g0U2E3bzNJCmZtdkk3NVYwY2UzQzJ0QUUrazdJ
            Q1doN1RrUW5RcmNHeDl4a0RPSFQwaVUKLS0tIEdQSllrRUYxSGM5WjUwQ1ArWDMv
            VW0rZ0hISExoNE9SVkN4eThrTkpnUk0KACkoNNFilW1hKVvhTOU6I9FIXEwas8Ih
            ohRojpFUoQoM9+AOjk7sjf6H/bRXcfqEEzyOsg8TmPAzgYMKfpfycg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-03T13:28:09Z"
    mac: ENC[AES256_GCM,data:WqRNam+mJznPoEBS5Kk/wdeVbwTpzogGzqhg73lIthNizRFiAdqwaWoUkHZAgGSaFcq1Cvc2OooyZjj2BLrTaXn4oPljv7fSNL/IZTSqouG3n98EeR1lt63tZ82wDYVJk7s+MET3U+R7A5OfYJSggYTygKDIjDFbO/AwuJnga30=,iv:ytFWirYwfb3aG4tzBKvkbTsFfdpVHVH5idVQqM92Ckk=,tag:V4quJDFgYU5lDyWd9Mxvuw==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
