apiVersion: v1
kind: Secret
metadata:
    name: mastodon-secrets
    namespace: ext-mastodon
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:pI5Arz5Ed2w=,iv:m7m9MS7oLi2hun8amyr+1Ox+Dzz9DYbhMKenRZBLVCg=,tag:e4V8MW8QTxtLnhbKVsp6+g==,type:str]
    password: ENC[AES256_GCM,data:WVQkZpi7Y7TfoZ/TpbOFnPnxu3mSxYmXupZvrLlmZ74=,iv:Lm8i2RjUfmb+3o/19Kn0AfHAec5+SMdZFedNWL580rA=,tag:ROM5bP/AUWLK17xeRlpGfg==,type:str]
    dbname: ENC[AES256_GCM,data:Bc6xS0j8XdU=,iv:Lpb8R2ZmOM5J6uJf9j9zhZMXgo6IRPbbuI1DNFCghrs=,tag:aJHQMZQQ21SkMOTccvRLeQ==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:SKE3zlxiJTpT1ylVkhssYukWLZUHsJZAH2kx6LYdNF+Y0h8EyMJGMvC7lvk5TpcrrfDnK29iGzAdTu4NhfNSY7hbuivEwRRi+MOp/mO8TrDjy6E1UMn/QPQ+kUFkPgdlHhOiatTmLM+AGJroieSzHNfCKzFFvWNPHqozBh3oGIo=,iv:nPE8SQiEbDMyZx/QwweF5UGRA/KOVhqioUhm7LLoPGo=,tag:kfgv0PeAuD5miMYjb5RKzw==,type:str]
    OTP_SECRET: ENC[AES256_GCM,data:qW5hRVMk5+HEwCFkfexE57Ure+ZdSQSB7AZp/3bH55D7ClmXjD/UQB22vL7HlHGHHe/hDFaeblH+gGI7p9txlNsKoboaNXyF9SNRgUBH4svQ3PUNB7FUFa7L6Ds2Iq6gXd3DDr9KellZUSG+sk6pl/7dLvm7ddCyQsGkMKJp/bQ=,iv:A/LJU80cpT8BA/4TyqmO4CaI81WP8CyNav7KWV+jiYo=,tag:8yA4fX8pOOKWUUqI8tOslQ==,type:str]
    VAPID_PRIVATE_KEY: ENC[AES256_GCM,data:nf7tbIiUIMEwIyqlmXyVTcBKW87dh/RO6q42D/OIyFcsmg0Ikr8+WK1DDQ==,iv:7smlsg/e83dvapvVhE6lJpwW+b4P/+XoMUS56hDHDMc=,tag:aAriDrAkTLOsSBELZKIWlw==,type:str]
    VAPID_PUBLIC_KEY: ENC[AES256_GCM,data:cA7bd485qmBOP30vy8ygyYT4xpyjqhC9tSfBWeo1n5YY8EwwlIw6npdudYdB//xIWOUkCq0DZw0SsTC+/f7cd4cpKX+wtt1qWECspTDXYZvONcJCt5ZC,iv:CUbmGB95xcfY8RZzrbBdxadB7dZf8yQ/pvQyc/QSqws=,tag:b67k1mFG0c3d1BKDGnBL9Q==,type:str]
    ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY: ENC[AES256_GCM,data:GLLPnTcyghwxxdLMZdDZ9DuyE2gtrBWS/sAOxd+EgNfdYpZa/CYfJoSRhzM=,iv:QkAJ+AKDPIwrb1egLLkWfAP2psCgkMjW1Jlw/er/bhg=,tag:DSZtpvOOb7XqF7K7K0M8pA==,type:str]
    ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY: ENC[AES256_GCM,data:DwBo17qXsj7kbN+oCZ3+iuvdF3r9vPQChlQ72+LXF0gU7ffkCrWWjaMWZbw=,iv:+hJO74zryDIWJvCsoOJo2PuMa4wUL9AXQ0DgLKup4cs=,tag:RhqWOe0Fdl9EUCUXSI+8hw==,type:str]
    ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT: ENC[AES256_GCM,data:JNy5qK5fqUATTF1o/Ic5b0zz+gPm6Kb7cngGAWGXs5/vUxZfGcLmcXjxzkY=,iv:CdDYs9YMrJNsjVxXDWzHTb1Dp+qJWL1PgXXPGo1LJVA=,tag:KnPRL28gHywJmRgHhP03zg==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:aSLG4CNQ8GoKRpxDz1RZZTohwdDcq6CxSdatBxueiqgOBSCEWQ+XFg==,iv:uSLI261XH6V2kcoTrtSA4lRVbZJLrQPmWPJiIizfSVo=,tag:iJ3+Xh0/PJbWitqS3GGhDg==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:rTah8OWAtp+OftCZ0vwQzOaFkFqbNfwtL9IoldvowA5xqgaZVjrgc3ex3dhNes9exXrOybPpipeBE62dDsgRkwrj4QazBs4Vwrm9/ruWYqc4RdNBoZ3FnKT4nFaWJjQb+4m4atBQIx3KTTQfZIrswZwrqhmJRc1UQSOmKZeHcIE=,iv:j4z+Cnht8WlCSqtHWN3dvccDK0kUWcORtNS+FJiiFD8=,tag:jAXEhEf++yGwcJ5JW1B97Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSUkrZVJPdmN2OFFHcGE3
            Z2IyaTNEV052Mm5TeFNxZEwxQVRPejFMV0FRCnh0ZVhaOHZkcTVXR1dTZUkxTjZr
            VHdYOUlSZmdwMXpqVDB0SXJLb0F2aVEKLS0tIGhDRHNWakJRTWJYMTNMRUF2TVZC
            RWJrN091UnNuS1BXSUVZbmdaYU9zTDQKGMkIFRgQSDhShgurPPUm2K0QMLCI35ya
            CmVrqJcZEjPui5Bwk9OUYA/XsEwjCdH95SuWvG5wogppq4osys9bjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-03T13:28:09Z"
    mac: ENC[AES256_GCM,data:KriVpFNrhczXZJlpl6O+WRnIaOaAx9KnKwnR02jEcagntLQ7KYCN4P9LkNfnMaToZKnWcHkWhEswV4Ey3eyT7WDEgGOoh/Ot11QuJyHyxSpOXgskP0uAPAEuuGVbSixdIhBFUzNgOUEMiSgjZ2m6TjfBBhQiTY1CCBUxL5RgE7M=,iv:Iw1oP42/iKmTMvjiPMt6J/CPXPHYuiP1V72IA3xjvNA=,tag:DMDBbAnvdFg+E2RZ3sFfsw==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
