---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mastodon-cloudflared
  namespace: ext-mastodon
spec:
  selector:
    matchLabels:
      app: mastodon-web
  namespaceSelector:
    matchNames:
    - ext-mastodon
  endpoints:
  - port: http-metrics
    path: /metrics
    interval: 15s
