apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: database
  namespace: auth
spec:
  instances: 1

  storage:
    size: 2Gi
    storageClass: openebs-crucial

  superuserSecret:
    name: auth-secrets

  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: auth-secrets
