apiVersion: v1
kind: Secret
metadata:
    name: auth-secrets
    namespace: auth
type: Opaque
stringData:
    authentik_secret_key: ENC[AES256_GCM,data:E7s1yOBy4Jo5VZCLhvurf8hznZCeBN5DY7uQj6q9G1QCUYh7vuEH7p2p/Hf6qS7Tquzu3jhnUJ8Z73LB3BEfmMv0tS8eOJIQZiLQTwYGoVI=,iv:T7rp3puJRqS90JZxqPrNhvMFpkfv5t/s5LyPOZQaI80=,tag:CiQi72ks91lmQtc71vH4/A==,type:str]
    username: ENC[AES256_GCM,data:SMufHH4Eil6+,iv:10BBfMiD4Dk3ErnjJnpVYx9U1qAEUGowdudgBvit5x0=,tag:eph5Vd89+Jcjx3Q/GQvFxw==,type:str]
    password: ENC[AES256_GCM,data:z4MtO3JCn3Lm0bDPRnVdng==,iv:PUZYfwZaaR2I8w8gA10Fvx/4dowIO74BE1bvpGkGCYs=,tag:14WLfMbRN89gcLY2ikoDoA==,type:str]
    dbname: ENC[AES256_GCM,data:3s+urQbojxMK,iv:pc6v0uCS8jPfSJjmzuf8GZM0f1tkxjqaGFey38XciPU=,tag:zMJHBeiN41N0Ln8eOLaLyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZDUra1NobWxiZUFPaVkz
            YXVVZEk2c09DaEZ4WWtiNU9IdzhuWW1vbUhJCklDVmJlT29yMWV1LzREL2dCN0N1
            R0JBYmNvRzJYZDNzV0VVRU9keHFNS1UKLS0tIEJOR2pVS3BERnp4akw0NzVhQ084
            WExjbHhBMmRsY3BpWDNaRlRiSHNBRTAK+ocrMmKic+uqez4VHlue42/S8QYuwynH
            4GsM8GOq0o/VO3/vb47AkuFsfpIdlHm8PDklYWClVDcPKljRCglU+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-13T08:21:48Z"
    mac: ENC[AES256_GCM,data:J/cL04SegCyXlrRGZEJ8ZKVFC5FvkMq+xhCskANIp+zlUq0wFWo5ZsWTieWGv/gCXcxnUPuibMzLjAPyV5r5VhRR37T99uKrZ72u1zWnzJze6aCyLnhspPrQgq7bHV/v/FSbTtvxttlgUzKigjOk2iUdQ0wawABTmuyZBuvKc28=,iv:o2TDBbFnnjPvnWBVwUz4vFeD8H/6Ke81kW4mZ4/AeDQ=,tag:5MeHr/JEbDT+rWO0SE2l+A==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
