apiVersion: v1
kind: Secret
metadata:
    name: auth-secrets
    namespace: auth
type: Opaque
stringData:
    authentik_secret_key: ENC[AES256_GCM,data:E7s1yOBy4Jo5VZCLhvurf8hznZCeBN5DY7uQj6q9G1QCUYh7vuEH7p2p/Hf6qS7Tquzu3jhnUJ8Z73LB3BEfmMv0tS8eOJIQZiLQTwYGoVI=,iv:T7rp3puJRqS90JZxqPrNhvMFpkfv5t/s5LyPOZQaI80=,tag:CiQi72ks91lmQtc71vH4/A==,type:str]
    username: ENC[AES256_GCM,data:SMufHH4Eil6+,iv:10BBfMiD4Dk3ErnjJnpVYx9U1qAEUGowdudgBvit5x0=,tag:eph5Vd89+Jcjx3Q/GQvFxw==,type:str]
    password: ENC[AES256_GCM,data:z4MtO3JCn3Lm0bDPRnVdng==,iv:PUZYfwZaaR2I8w8gA10Fvx/4dowIO74BE1bvpGkGCYs=,tag:14WLfMbRN89gcLY2ikoDoA==,type:str]
    dbname: ENC[AES256_GCM,data:3s+urQbojxMK,iv:pc6v0uCS8jPfSJjmzuf8GZM0f1tkxjqaGFey38XciPU=,tag:zMJHBeiN41N0Ln8eOLaLyQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrN1R1TmtjeVpmS0piU3ZG
            Nnpzdm1td2N3S29aZUY0NjhnWlNjdkJQTlhBCmhMRGFDRWg0eUpFTmtzaEtBNVdr
            OCt2YS9ZTlJKZ09aSGcyMTAzZ3djWUkKLS0tIHdjVFFoOGt4c3lsc0FNeER4UjRR
            VFRZMXRMMzFnWlVHTEVTcGVXQmFsZ2cKLit5FlqK2gJ5G2Ax0T+iGPm7E7c4ZfOF
            4Do36dB8Njb6r4e8VR87oZaLQzou3U4iDZyFLNy2ibj7XtAEtcVnfQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IFJTSlJydyBBLzIwKzFr
            REZMeW5Id2lKUU1tTld0eE1nd3I0ZUlDK3B6Q3Vac0N3eE1BUgpJbjBsRGlJY2tt
            eDNsZXdpM3A5aGlUS1N4aFBCanNZUnVHaTlna3BjNUMwCi0tLSBRV3dtYWVEbkZi
            MUtIR1lhV3k1bEdvbDdPRVdpSWp5UXRFV0o4bldIL2RzCouDY+hnvH4SSU1VRqJL
            H9QsDT4u6HIWR12j5yN67jPg8d0++jY31Oi481HfPWRhqesyW1aKop6Stvr4ztPt
            7EI=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qgn7ll64pzy4wd64h85xxq386cexa98676zw4raej9rvxl822p782xrjn5z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDY0dUwvQSBBaUlGWW9m
            c1hjRzBWMGc5cWFIbDdETFNzbXZoRGJLcVVrS25qc2l6ejJOYgpaTHpsaVhmTzcv
            Y3JoKzA3VFk2aHdzbDlBdm1qQVhHTEZOY05BQzVhZ0ZZCi0tLSBwQ0JqQVlVRzZT
            eUdkMnNXSnNyR2JMZXZrWWx1MldHVkVtNkpzUFB4YWRFClta7CEpONyrHhgFvQb0
            QGdZShcPXo7BeTh0SKEpVI6t5zhkMltI3ANP7W4ivisWGV2EmZQiyTwaxah+kUoX
            v5M=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtvpgtvl83qxn5kferysjnzrt0zs2svfygeuvqznlupmvtepcwv37v7pace
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-13T08:21:48Z"
    mac: ENC[AES256_GCM,data:J/cL04SegCyXlrRGZEJ8ZKVFC5FvkMq+xhCskANIp+zlUq0wFWo5ZsWTieWGv/gCXcxnUPuibMzLjAPyV5r5VhRR37T99uKrZ72u1zWnzJze6aCyLnhspPrQgq7bHV/v/FSbTtvxttlgUzKigjOk2iUdQ0wawABTmuyZBuvKc28=,iv:o2TDBbFnnjPvnWBVwUz4vFeD8H/6Ke81kW4mZ4/AeDQ=,tag:5MeHr/JEbDT+rWO0SE2l+A==,type:str]
    version: 3.9.0
