apiVersion: v1
kind: Secret
metadata:
    name: auth-secrets
    namespace: auth
type: Opaque
stringData:
    authentik_secret_key: ENC[AES256_GCM,data:533jUg==,iv:3QLAs2uw1bayu4bhV1nDj78UD2NGu0fkjCBbTNlVYHE=,tag:bytK5k5X0rJO/SYACzjUdw==,type:str]
    username: ENC[AES256_GCM,data:GW0FS46FdUe1,iv:b1t1wIwHwnoy9VFuIfpw9NkBdLB3eUK7wfDZWpMZBVM=,tag:gu2aBUd/ppGrhb4Os8nAtg==,type:str]
    password: ENC[AES256_GCM,data:uvYafgSf97uQ9QOJOKrqcw==,iv:3k4/Ph3RmFXlwuyCuoxvBR37CijPpHALiAp05F6oL8k=,tag:B55r+ofMGF/RrITgzo9IMA==,type:str]
    dbname: ENC[AES256_GCM,data:F5kYTgFqYe6b,iv:b4iIsqu4qLsAy+1gDtMI0bezW4YY7lwSsVh3dsbWNu8=,tag:yAelnxYfgzsjHeEuQr9VoQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSWR2N2diaHQwQmlqaFZl
            bTZoVkU5dmJINTl6c0gwbWJILzl2N2VzaldRCmNuSkwyN0ZvcUNFZTVYbGN2Rk1Z
            OXRkNWROMlJKK1pnc0x1RUFtZEh2YXMKLS0tIFE0eFpUbk1WbXdTZk1hb2crdXl4
            T2xYenZEM21NNFBKc1MxbXVHN2ZzTUUK8Q2J3aBYBsUXHoDtFLCe73mqB4LO2bIG
            MAeH3m4k26EoQMgvxVSk+TUUAKin+3+V8spRTyw8CBWQxVthRUBr/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T22:38:43Z"
    mac: ENC[AES256_GCM,data:knqpIfqS7O80tZRRK3mimq/64polk5oePAGa6Pn03oTKkgR/Vjqa41HCRK3Hke4P4Ftd/ksngyQVGoGuFsDITU/dVFhJ9T99JRcWpagHdMn8aAtwFi1URHy5ein3u53w1IVFcD+ichYWQtm8UCJ+zshE6PhN8QlNo6/9Bxio7jc=,iv:pPXt+fEm/BxlYrkh35URsf7Gv1CbcdLB56penXwvWRQ=,tag:uldTIyTbYtzs1VZInB8iZg==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
