apiVersion: v1
kind: Secret
metadata:
    name: kube-etcd-backup-credentials
    namespace: kube-system
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:3EWMve0tvzAd9g==,iv:/yAU1UzTwvx6B8T8nG9EA49/nRvo06Pa+MdDOCnXs7U=,tag:ZhzA9TXBdeo3D2Se9b1bwA==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:+hYIYLggq4KW3Q==,iv:G1AIM3NtEGPnG198pxD6I2Me/itQOksuHCAO6Gh34xg=,tag:JIBwXklHni6V0ADOLBiC0g==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:piYGrOG6hvnQAQ==,iv:0WTFeui4D/3EHKmmcsaGw84+ZKdIMxa4I6KhtuDQJ48=,tag:drHkgVB2b87/cMji6ZAaAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPaitpWWpyOXJxMThqRmxY
            UG1kTGhkcFJjQnVOWUhUMXVxTU8vZ0greERrCmN2M2RPYkd5cUZwOCtDbTh1L1NM
            cmpMOU1oTzRqNE82UG90ZzVRQ0pPdmcKLS0tIEVjOVJJZFBCQk1SSmc5NkJEbUpx
            QXdvUU51cTRZOHFjaWJacnlCZThaZjgK7q1CQfJnuTSlIWSoTWUdlu21ZGrJdpJs
            qJn0H6Bm3/P1Pd02tN6nTdCg2CdgvcnVJ4u2ViPMA8jJ3SdFy6ADpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-21T16:52:58Z"
    mac: ENC[AES256_GCM,data:F4sxNEENtP/2pjkaudUXvsZHzbYup03A6HgbNr1zSqbVseuWMCa8q/m+ghdR1KmUBl0vCvcQPtifraBkADmPD3MhG8XLks4lhCMzYdNil3Uj6LfXKdPTOudPKTDjwuBENgjj/ID1o7lpTsmhxkcOKc+0ly21ymNKC92OScTlJoE=,iv:jGJmpRnxLad2i+uETC0i5jaB12+NAZCHdzvMQBrV+jE=,tag:jYSorHpcoFElheVZeF8Cvg==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
