apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: ext-klimlive
data:
    tunnel-token: ENC[AES256_GCM,data:150trPN1XoUzBSHcni6Bq2mwMRoykI42P82u86qEHi0/i70KbfK+z8yIMb49bIn4NpkgxIGtabT+jfVXp48vSWQcokAOLxu3wWcnMzn7ugKEjZGr4Cetc/t05rNKlw9FwcCfGLO4Vqcg9D0UnAb3Wt3omcQEZm11hfB0xFADLayxZK2Exj2VD+0sQGgOlG5rm2Gc3CbFp4QsbHHT7QLPDWmt2dUlozr2cctZZpGj4TSRl7BeRQ9Yk/N6UgdBaVc7VSf0XxlxTrYm0uuKqEtDfXzOz5fhmbPrB/Et1gOTg+/SsJSTu3KjHjPQv++3kpWal6EwjsAL6Xg=,iv:vvdDj7ki4l3irhR+p+TLyfYp2upPpBHQRhH+HxNnj1g=,tag:H7PRkGcQZFIH+R0wsECLTg==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzam5URGZUUHhEWEEyNlY5
            Wlp2RVBDRTlpNnZhVmR3NjJhK3h6MTRhcEVRCktjaGVLREFPUThSOTNHT29iMUcz
            TEpoZC9GRTArdW1BTk0vTGk1QUVITW8KLS0tIHlMWkI4SHhjcUN5MXdUUmpuRmZw
            eGpUL1A2Ky9SRTZTb0lXWFRLemV2TVkKoSZyXhJnHg+2zcgEMXvRc6yFGBHj4XNR
            IiHzl8ZlgO2gdVMJx/sVbm7/ZRFI46azSRDl1+jONBeNnKFcAH/vBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IFJTSlJydyBBaDNRVDQ2
            bHZwNDVtODVRbXd2WVdVb2dIMUU3T0Z5aC9sVnlyemdDbWFlZApVOFNBSjVYWWJP
            VnFoaXRBb3dLV3U3WjZiTVJJVmVqTVBqRDI2aC9mWWtzCi0tLSBEK0VrdmNodVA3
            UFlOLytBTm1zL1pLQ0dKcUxYeHBBckxndW8vZDE1aS9FCjy6DWKbZGCoqFz4WpuW
            8x7vYJemCHHRtU+CDPXMR4W4N5TxUV6kwVvbFIHh0mjdcCWFvU1tHV9iOp+Yi/FJ
            bKk=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qgn7ll64pzy4wd64h85xxq386cexa98676zw4raej9rvxl822p782xrjn5z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDY0dUwvQSBBdGtCWHVt
            M2VVU3M1RHplOHlPKzBFY1RIQzdaUVRFUWRJa2lJRSsxL3JuQgoxRWtQYW1JRUhr
            RTBjcURUaVpPa1FhWCtvUXpHVGcvT0dkR1psZHIxYzdvCi0tLSBiNEZlWFM2ZWFr
            Q0FQa3hTR3VES1BVZnZqWkRYdEdlWHlZNFNkYktDQXRNCqd7iYisbdSPo0Lh794B
            2vYOp4D8gNI7T+COrVK86X7pVBAhLEfHPB6/X8EbldwDfe/UVXyTnp5MQzfvtbhP
            JHY=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtvpgtvl83qxn5kferysjnzrt0zs2svfygeuvqznlupmvtepcwv37v7pace
    encrypted_regex: ^(data)$
    lastmodified: "2025-05-27T20:19:13Z"
    mac: ENC[AES256_GCM,data:HUpdAfyQR/HRE0VLX9a14nVF3V0tx+OFmgIWv7G4hgJECY6lwljnGQW3MUtDwKn1bxxfFrBdEYiyDTzHlYK8lDJHZYPA3+7vNYiI6vOPx+MEO1kPYs8g/oxZfsFARkuCz/akd5PqBrUxkGyd6OSzdJWaV7WXMnED22Zofd+N3TQ=,iv:0n6BIWMrmnjB4jNdVXxh9I+lF0mq8eUHjYtb2iCMbyI=,tag:fVU1A/IpIMXgZyhmM4Jo1g==,type:str]
    version: 3.9.0
