---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: klimlive-cloudflared
  namespace: ext-klimlive
spec:
  selector:
    matchLabels:
      app: klimlive
  namespaceSelector:
    matchNames:
    - ext-klimlive
  endpoints:
  - port: http-metrics
    path: /metrics
    interval: 15s
