---
apiVersion: v1
kind: Service
metadata:
  name: klimlive
  namespace: ext-klimlive
spec:
  selector:
    app: klimlive
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: klimlive-monitoring
  namespace: ext-klimlive
spec:
  selector:
    app: klimlive
  ports:
    - name: http-metrics
      protocol: TCP
      port: 2000
      targetPort: 2000
  type: ClusterIP
