---
apiVersion: v1
kind: Pod
metadata:
  name: garmin-exporter-frzifus-debug
  namespace: garmin
spec:
  securityContext:
    runAsUser: 65534
    runAsGroup: 65534
    fsGroup: 65534
  containers:
    - name: debug
      image: busybox:latest
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: garmin-exporter-frzifus
