apiVersion: v1
kind: Secret
metadata:
    name: garmin-exporter-frzifus
    namespace: garmin
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:UJkdR80fCzVrxLEVGK2CdffVJAo=,iv:p6ct+S8g4QhXfhbjJYdc5kf2yqBow6QcRBjrv2sydB4=,tag:DYlLSB2BmFuLgH4UMwpmYg==,type:str]
    password: ENC[AES256_GCM,data:/jXDs0l4sZkNqpvSSfSQaywxVO+24II4SVk3,iv:HsA9QlApQJ30ketRAAmvawj5/JEHDy1Pk+E2sb2hMm0=,tag:5w/yoKQk2ze2x1coTYZIpg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOYTJNNGgvUGRKWkFqcytj
            ckZGdXRaS01WeDBNd2JqNDBReTNIUnFWRXpjCnE3ZHBxUWtmSjRwTkh0Q1dxRWZk
            VEh4b1Q3MmJhYVZEck1FRTVWUURQZjQKLS0tIGxGRUJiY2RweExxMXVRRzNwWURD
            MGxPTFAzS3dzeVk5ckx2K2NUd2NJK0kKIVjqUZDwIM1c1ynAbOAIXCMsynAPaUrL
            lNlEgIs+t81NeiLRzA7KXKTVSr0x74UeJ+KFJ/XoFmY1OzPiLHqCzg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IFJTSlJydyBBN1FxWmJq
            TmhZTCtNSVN5OWJDdDFsMHJieGRxaHZRdmhmZ3BYcW9WWTFNNwphNlhSNHl1UXIz
            TC83NVJUNlhYaDZ5cW8yMEtqK2c4Z2ZLdGtKTWltT2g4Ci0tLSBvTEhjTWczbGxi
            RzJzK3UzTzcyU3R2RWM4U1hGd20wSVp0T0l3akpxOERvCmzVn+cCMJ+9kyrD1rkN
            XFmJLAnuIuirjvs57FM4hWTx36h5+bINj/+VdFyk4S7AcNazo8jMvbs6m8snkD1t
            54c=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qgn7ll64pzy4wd64h85xxq386cexa98676zw4raej9rvxl822p782xrjn5z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDY0dUwvQSBBeXVhTEZy
            QzduNHR0WjdlOThaRitWeVA5UFdPTFUrUnNTbkhLL2o3S2pocgpUVERYZTl1TzBH
            RmpmMlRKRkEvZCtVOThXaHQ1YzFXL0I1TXNZMFlrckc0Ci0tLSA2MHZRVjN1d2FH
            bjFCcUpYRnkxQmlUblpRZlZzZkh5U0dYTW5ma2pkZjVNCuslR19PmeLsl6zrLlNk
            SGJ+3/NYHfgPq8Z4pq/clFMffaqOD7LOoNZo9ifaw8sVsqfqAK4/vzrpybPuUe3Y
            loA=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtvpgtvl83qxn5kferysjnzrt0zs2svfygeuvqznlupmvtepcwv37v7pace
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-05-28T23:22:19Z"
    mac: ENC[AES256_GCM,data:oHwv3QOq8QpUAH2EFHmR3gIe1LKjMyEZSCsugL41psQhAe9dSdmmKxYErvC0FQOOEzJ7XNXogaTt24yMaPdVwD470ugkgP1YC4QziJ59Vji0YvQuELH+o/JLxW5l6D6YYjOOC51GRP7cqORHSxxevQTwX+jIgcLvx67jRqSI2qE=,iv:8e03mB49VjGhrPz7hG1ytqZirCco1tWpl4CPTCh6FaA=,tag:86RDIS4CVJ6h5TllegzW/w==,type:str]
    version: 3.9.0
