apiVersion: v1
kind: Secret
metadata:
    name: garmin-exporter-frzifus
    namespace: garmin
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:UJkdR80fCzVrxLEVGK2CdffVJAo=,iv:p6ct+S8g4QhXfhbjJYdc5kf2yqBow6QcRBjrv2sydB4=,tag:DYlLSB2BmFuLgH4UMwpmYg==,type:str]
    password: ENC[AES256_GCM,data:/jXDs0l4sZkNqpvSSfSQaywxVO+24II4SVk3,iv:HsA9QlApQJ30ketRAAmvawj5/JEHDy1Pk+E2sb2hMm0=,tag:5w/yoKQk2ze2x1coTYZIpg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtK1lWRkE3UEZwUFk2SXBp
            dnYweHFJc0Q4MWNSdzI1Z01vb29OaDZOM0Y0CnVaM2hEcE9qNW9jOER3WXRQTnRV
            UnlEaWVSRDgwcnRYMmtOWEQwR21VdmsKLS0tIC82NUJwa3ZDNmhTdk9qKzBETFJq
            MGRleTFHdk4xUzRTbVdTdFd1QkthYmsKyTWtcuZeePgMiVNgx4dck4CBYRpAJimc
            CngNgs9HEUJm0RvWcGhd37exv4r8wB3O/tLJzj076/BqQu7vpPU0/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-28T23:22:19Z"
    mac: ENC[AES256_GCM,data:oHwv3QOq8QpUAH2EFHmR3gIe1LKjMyEZSCsugL41psQhAe9dSdmmKxYErvC0FQOOEzJ7XNXogaTt24yMaPdVwD470ugkgP1YC4QziJ59Vji0YvQuELH+o/JLxW5l6D6YYjOOC51GRP7cqORHSxxevQTwX+jIgcLvx67jRqSI2qE=,iv:8e03mB49VjGhrPz7hG1ytqZirCco1tWpl4CPTCh6FaA=,tag:86RDIS4CVJ6h5TllegzW/w==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
