apiVersion: v1
kind: Secret
metadata:
    name: garmin-exporter-miyunari
    namespace: garmin
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:5pRF+5XIdADOrg==,iv:MdEsx4ZNmA/ShoX/3DMTjfhBPxl3F8UhHqw6Ix1rxxM=,tag:oltR3ywqIv7LZplXm9XgtQ==,type:str]
    password: ENC[AES256_GCM,data:tCUmaiymGfWVBQ==,iv:zxicFrDwCCpfEP/sPr98vRWU1mvuBzcVuSi80yv3was=,tag:OIhqAkuZMFKiD3mX74udmg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNWU9MTGtZbERMVnl2Mmh1
            dmxHdGVkUGJjK095VHZSZ013cXlYakI3YnowClhVbWI1Vm15K2RFTmtxTW9la0ZM
            ZUxBNHg2VmczeVMyUG54ZmtLa21UQjgKLS0tICtsVzdmTEsybUsvaHlWT0tYM1BH
            N1J5dTNsa0cwRi8xNzZZdjRTeDFQVkkKgR8l+t50IASdoEb7+MGvsmS2dWYa05f+
            Xg6wmVmfqCBhVTn17/6+uroLtrsSJj75FAisq0hHVkA7A2lAuGk5vQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-15T12:20:48Z"
    mac: ENC[AES256_GCM,data:jOREfFG0kg4B2MX6o0tvmv+j5KqB7UQjlB+UJQ1fAtDaS1pWK+uF4nuC6jesy+FtgJ9RixGDOsDRmdKRlvIQ+UL0kW17WPbzhGvHl52lrIVjSt/bYrZcXhQfzRCRTC5FCW2YBz+bP8w4IiW1TgPtJbgOZ/RoE+BN1JF/tkBnSi8=,iv:Gi0KV15xIRnqFO21URtOPiq8J6EM/PeT5oYowYfRR18=,tag:9cmUh1T5RvnyvAu8r34k5A==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
