apiVersion: v1
kind: Secret
metadata:
    name: garmin-exporter-miyunari
    namespace: garmin
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:5pRF+5XIdADOrg==,iv:MdEsx4ZNmA/ShoX/3DMTjfhBPxl3F8UhHqw6Ix1rxxM=,tag:oltR3ywqIv7LZplXm9XgtQ==,type:str]
    password: ENC[AES256_GCM,data:tCUmaiymGfWVBQ==,iv:zxicFrDwCCpfEP/sPr98vRWU1mvuBzcVuSi80yv3was=,tag:OIhqAkuZMFKiD3mX74udmg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RDhuUlJ5SW1ick9Xdzcy
            OFJVREdia3Z0eEl4SUg4azNHTEV1dVpIZVRRCjRGRkZ4RE9JZWc0M3RTUTExOXJ5
            UUNaOEpnb0tHcDlPQ2FVMjB0S2x4S2MKLS0tIHBNaFhjKzRxdDRMTitzNDhPcGxM
            MUVnYmQxMDVGdHlHUnNEL2NkM2NSNjAK09OKNb3emADYJtAFKwjBq8o2HUJ1qjRG
            CoW9CWgSxHDqn3NrYSw/J+6F+iJl4BuhWFB1DS8qIj5ybGUH8Hzb4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IFJTSlJydyBBaFEzRVYr
            MTZtaFMvd2dqWGlBcHdtc3lFNitBZFlrRHZENTFFSmpQbmxaTgpJd0d6WHlJRFFt
            djZ5VXVOR2lZWWRhS1pqUmRsMk8vM2ZHSnFpdTFMSjNRCi0tLSBuckpvUkQ3eHNq
            MjJuVHhqYTVqUllwZEFERjFQbENLNjN6MlJhbGJ2QWQ4CoOzJ522fTyQAuLneaHC
            +EAx+ByXQTWjGu1+zzInyKgsunn5wWsTHJHWW9HczAAsbuX72rYwAPHJVR1Yl4Um
            fVM=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qgn7ll64pzy4wd64h85xxq386cexa98676zw4raej9rvxl822p782xrjn5z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDY0dUwvQSBBOUM4RWpu
            bW4vWXl0ZnVleUk2TFo2YUFjQVlRRGN1Uysxa2R5dzUvbXZ5RgpjWnBhQkZBWjh5
            Y2QvV1Vob1RkK3dHTTI3N0YzU202OXlUTWdtZlI2RHZzCi0tLSArZkp3ZTB6aVBK
            SWYvLzdxcGg5YmF6MXFFcDIxYlFMMnU3LzZHQVc0Y2RJCvKqNBiet+YjypNl5qsh
            r1K3P8IPv6pXGWjefDPOrve+G/VW2jTOqD7tQG3wRejH2uR5CMQD/zdlOwcgpsvI
            y8w=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtvpgtvl83qxn5kferysjnzrt0zs2svfygeuvqznlupmvtepcwv37v7pace
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-15T12:20:48Z"
    mac: ENC[AES256_GCM,data:jOREfFG0kg4B2MX6o0tvmv+j5KqB7UQjlB+UJQ1fAtDaS1pWK+uF4nuC6jesy+FtgJ9RixGDOsDRmdKRlvIQ+UL0kW17WPbzhGvHl52lrIVjSt/bYrZcXhQfzRCRTC5FCW2YBz+bP8w4IiW1TgPtJbgOZ/RoE+BN1JF/tkBnSi8=,iv:Gi0KV15xIRnqFO21URtOPiq8J6EM/PeT5oYowYfRR18=,tag:9cmUh1T5RvnyvAu8r34k5A==,type:str]
    version: 3.9.0
