---
apiVersion: k8up.io/v1
kind: PreBackupPod
metadata:
  name: mastodon-db-dump
  namespace: ext-mastodon
spec:
  backupCommand: "pg_dump -U mastodon -h database-rw -d mastodon --format=custom"
  pod:
    spec:
      containers:
        - name: pg-dump
          image: ghcr.io/cloudnative-pg/postgresql:18
          command: ["sleep", "infinity"]
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mastodon-secrets
                  key: password
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
        runAsUser: 26
        runAsGroup: 26
        fsGroup: 26
---
apiVersion: k8up.io/v1
kind: PodConfig
metadata:
  name: backup-pod-config
  namespace: ext-mastodon
  annotations:
    kubernetes.io/ingress-bandwidth: "20M"
    kubernetes.io/egress-bandwidth: "20M"
spec:
  template:
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: mastodon-web
              topologyKey: kubernetes.io/hostname
      securityContext:
        runAsNonRoot: true
        runAsUser: 10000
        runAsGroup: 10000
        fsGroup: 10000
      containers:
        - name: k8up
          securityContext:
            allowPrivilegeEscalation: false
---
apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: mastodon-backup
  namespace: ext-mastodon
spec:
  backend:
    repoPasswordSecretRef:
      name: backup-credentials
      key: RESTIC_PASSWORD
    s3:
      endpoint: https://s3.us-west-000.backblazeb2.com
      bucket: 2e9e1fa8-4bd9-4117-b318-9811a922fff1-mastodon-bucket
      accessKeyIDSecretRef:
        name: backup-credentials
        key: ACCESS_KEY_ID
      secretAccessKeySecretRef:
        name: backup-credentials
        key: SECRET_ACCESS_KEY
  backup:
    schedule: "0 3 * * 1"
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 3
    labelSelectors:
      - matchExpressions:
          - key: k8up.io/backup
            operator: In
            values:
              - "true"
    podConfigRef:
      name: backup-pod-config
  check:
    schedule: "0 3 * * 2"
  prune:
    schedule: "0 2 * * 3"
    retention:
      keepLast: 6
      keepWeekly: 6
