apiVersion: v1
kind: Secret
metadata:
    name: backup-credentials
    namespace: ext-mastodon
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:Bj0tZ3TnhYk=,iv:2wvcc2i6Ar5gsNPv8pf5cvN1khpSXP9Kg5LuKBBUjSc=,tag:bECJLqJ4CeaEK3iYRslGWg==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:dEXeXfm9xco=,iv:s/Fvu2EpRSr28UcBoXEbRha+QBIZVhQBOllEhVa6mnc=,tag:tuBi6anirb3QIh9aAFJ5jg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:YTXJX/TdUm0=,iv:lloP8WWuDs1v2/aPm1MDA9mqyEY0UoGgo2bpThsxYvI=,tag:46NhnQ+iPUKRs1od7KmIVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1L09QNkc1WHhzWklwUXRr
            TFVINWhKaHZhYU0xQzVXa3dPSHhjUUZhL3dRClE0bCtkelhTTitaK1UzTDhLc2ZN
            WHcyRzc5SDBuRTJBYThlM3B1MC9XTXMKLS0tIFhHWXFkMkx2WjRhTDRWY014cWhv
            dDI2QkJ2aTdaZkZIK1JtMG9rdW1zdlkKhjk7LVUGRmn74d276vs4RtGP/eKeSx/r
            tN5Wyi9Ak2Y+ST7X4AnQ695Oigj88JFFli0SZmna1No6B3TdLM0u/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-03T14:29:23Z"
    mac: ENC[AES256_GCM,data:HQ5PghzGSqCz0SKVLpgyT9Y0lf+2x8QBiQk5up32/rq4NN7NH1yt7hYDdpu1k5EfBescfikpUE2iv9I0XRdC9q5zgJFaXf/YSsRhE+H32YvE5pbiuMK1mZFhtGevod1BD1+wMS4uW6pr5VirAQ0EXV7f0OWrBstp3KoZph0xlaQ=,iv:YRWFNY2IOa8U+BMutqPPVUPOLyrst94qNhXr0ql5Kzk=,tag:x5auh3StSMN1NVBwhF7GJA==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
