apiVersion: v1
kind: Secret
metadata:
    name: backup-credentials
    namespace: ext-mastodon
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:Bj0tZ3TnhYk=,iv:2wvcc2i6Ar5gsNPv8pf5cvN1khpSXP9Kg5LuKBBUjSc=,tag:bECJLqJ4CeaEK3iYRslGWg==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:dEXeXfm9xco=,iv:s/Fvu2EpRSr28UcBoXEbRha+QBIZVhQBOllEhVa6mnc=,tag:tuBi6anirb3QIh9aAFJ5jg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:YTXJX/TdUm0=,iv:lloP8WWuDs1v2/aPm1MDA9mqyEY0UoGgo2bpThsxYvI=,tag:46NhnQ+iPUKRs1od7KmIVw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKY0lpcXJ6U3NmQit1V2Jp
            TDNDekVSa3NmUU16ZXJRc1hBMVFpNE1PU1hnCm42VnZuWlBabWhDN0NDMldiK0hN
            bzdpNXhXZHc2ait6NFcyc1kwMi9USE0KLS0tIENycXdCbVpZUXhOWktFcXNOUTJ6
            LzMzZ1ExN2tGamNDb3RhMWZYdXV5bVUKH4ATMzmI+5Ff4xLShRbqGHTKpTkyqaba
            IPzXxgEX2+4KJ1qqD42QntkPNbIwcf5MgwKQ3yjGK/srtPpSTWdbZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IFJTSlJydyBBc3duSjl4
            V3J2WUlidDdPdFZReUppTGVVK2VidVJJVVFNVVRTY01ySlJ5cQpmR3pUNmRIUnA3
            clAvMHJvcDlsQkVscFptUG1tbHIwakpLdmdyY0dvN2dNCi0tLSA4MWpMMU05SlJ4
            eHBCbHAreWlrNENCYm94VjZiTUZ0OXFHcXdhV0lERURrCkKD9E3j8UjmR6DA9sKA
            3S8riH1UPmo4yf+EMC9xZPBXBYPTOcXvpdRx6LnSudxEFja6gUbl/widjNffK8yi
            Qhc=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qgn7ll64pzy4wd64h85xxq386cexa98676zw4raej9rvxl822p782xrjn5z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDY0dUwvQSBBMDBENlFu
            S0JWbS96UkIrZTdCdC9CcEYxOHNPczhpRlFHV25YQTJ3M3JpUwpsZEVnMVVVdXd4
            bHM0SVhQUGFjVlhXeDd6dzVRY3ZURituVW5JUmNrVE5FCi0tLSBreVg1aTBldjd5
            TzNBTzdPRHROTXY1Uzdjbm9hMnl3SkFtOCtHbWdxdTR3CjvJe49jqjwE1tKQ5cmY
            PP3ix9gJ3HkLI+HuDyPj60jGVObcjZHe4OKpZxyhX30T05+oZyyEuNOWBtJBer7B
            yks=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtvpgtvl83qxn5kferysjnzrt0zs2svfygeuvqznlupmvtepcwv37v7pace
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-03T14:29:23Z"
    mac: ENC[AES256_GCM,data:HQ5PghzGSqCz0SKVLpgyT9Y0lf+2x8QBiQk5up32/rq4NN7NH1yt7hYDdpu1k5EfBescfikpUE2iv9I0XRdC9q5zgJFaXf/YSsRhE+H32YvE5pbiuMK1mZFhtGevod1BD1+wMS4uW6pr5VirAQ0EXV7f0OWrBstp3KoZph0xlaQ=,iv:YRWFNY2IOa8U+BMutqPPVUPOLyrst94qNhXr0ql5Kzk=,tag:x5auh3StSMN1NVBwhF7GJA==,type:str]
    version: 3.9.0
