---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secret-tunnel.yaml
  - nginx-conf.yaml
  - deployment.yaml
  - svc.yaml
  - network.yaml
  - servicemonitor.yaml
