---
apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-klimlive-nginx-conf
  namespace: ext-blog-klimlive
data:
  default.conf: |
    server {
        listen 8080;
        server_name _;
        root /usr/share/nginx/html/content;
        index index.html;

        location / {
            try_files $uri $uri/ =404;
        }

        error_page 404 /404.html;
    }
