apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: ext-blog-klimlive
type: Opaque
stringData:
    tunnel-token: ENC[AES256_GCM,data:zyt3GqHh82VsosaYenKIwY9ih3xcmBoKLRO3ot8Vu6y1nymrgDuFh66Y/pojwf9fTP0xf2quX2tzDRR7oUe2hisomiSxR1M4uXQja2YpQmty4xADlOyDzuuZay24+ZsWe0GOA3uOBVJ7/+BtlNqb53800OByhLgXWiK/BKpTV+M7qJAKjR/VbBSVPVADht3ecgcs7EjnurSdm95NjbR3bL2vsr0K4raeal+KTFvs+Qvoc5xZhHzgcg==,iv:7W7qMzNnj4ryJjhwcaQRmVLPAOxjT7pq3L1xIsXKQko=,tag:yzx1RsgctXw5S6bTe5JvHg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RWJFMkNuMnorV3FPTm01
            bEViU3FvQUNhTWtvTGpwVzlMU0Z3MllsT0FBCkU0TVBMcHg3N0VYa3VSclA4RG4z
            ZzZJRHVHM2J4TFVON0prRDVkQkZtUXMKLS0tIEgrTnlkT3psZnRTWWFnU0NCSlBT
            aGtZL2EwdW9YcDJqNHVGM2d4dXBkODAKMvnVaj9/xyZ/ffTUXznBpGRm0vfMF11P
            G7PPKXhK4JNAlXEEOWsbpFAouJ9+A05TzzaVRzWq/g3Yoknrn+Z/TA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IFJTSlJydyBBeS9IeExT
            VGRmVER4NWZWTldxVit5YzBLa1AzVk9HeG1iNDAyZEIvQmFXRwpCV3B0bU15NlNT
            cDYxUURqOTA0UWpSTnIxenVKRGd1YWE2SlRzbHhWT0lzCi0tLSBOb0Rlb2d3bGZB
            MmVSN2pvdTgyWVpnR2h5Nzl0OGs2TERkeTE3enFjdkRRCuMoN5nMC1mtLWjTlvwX
            GhcZl0m0CdA8VGYCXlK/35acO6ED5MK3fiAyOYF5RlAUPhNhn75r43YbYLYfWTZ5
            mes=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qgn7ll64pzy4wd64h85xxq386cexa98676zw4raej9rvxl822p782xrjn5z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDY0dUwvQSBBd0xrcUFq
            OHFaSWk1MDM2ekYyakIvMmRjRE9mbTJjaVgwNS96L2ZjTVdSNwpwRlNNcGZlYWFn
            ZytLUWtwTFZuMi93bTRzUURmNVdNOHVNb0hpNzZqbUpzCi0tLSBWbUtaRjJmYjZi
            cnZUS0JFWE5PTGtOYVlYQ1BsdnhoUjJ1NktSNWpGNE9vChmszCxlKXAPoTz/IXe8
            c/NFO+mRToNeGbenZ2WTLreXxgflau90i5YsF0WavWrpueThDNQOOaxL/KeLUVmE
            u7I=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtvpgtvl83qxn5kferysjnzrt0zs2svfygeuvqznlupmvtepcwv37v7pace
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-11T22:02:31Z"
    mac: ENC[AES256_GCM,data:poay6/DoEHYVnqEcjWhYU8eBknsZHTOTdUmB47OPN5dpCV8Ulc4jPn3gONUtpKE2RBgJpgBboM23fV+NvRLRTe3Zb43qHf5tzsz0ykXZXS218JLVPXUv5otpJuJCh272MRWIj/XKACgWtNyp1WGRZ/CYnYH1oBesBBNgbdIFmJk=,iv:1C8+OENcRXGqp5PSYTShH0mui90Aco87CUqwxJF/z7A=,tag:9rIH6ZhJ042Q34kGCFqUww==,type:str]
    version: 3.9.0
