apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: ext-blog-klimlive
type: Opaque
stringData:
    tunnel-token: ENC[AES256_GCM,data:zyt3GqHh82VsosaYenKIwY9ih3xcmBoKLRO3ot8Vu6y1nymrgDuFh66Y/pojwf9fTP0xf2quX2tzDRR7oUe2hisomiSxR1M4uXQja2YpQmty4xADlOyDzuuZay24+ZsWe0GOA3uOBVJ7/+BtlNqb53800OByhLgXWiK/BKpTV+M7qJAKjR/VbBSVPVADht3ecgcs7EjnurSdm95NjbR3bL2vsr0K4raeal+KTFvs+Qvoc5xZhHzgcg==,iv:7W7qMzNnj4ryJjhwcaQRmVLPAOxjT7pq3L1xIsXKQko=,tag:yzx1RsgctXw5S6bTe5JvHg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZC9ROUkwU3V4N2l4T0V4
            UXFZcnNLMnRVdVp3MS82REE5Nm9OT0x3K0JNCm84SHlYTTR2Q1F2ZU1lTjNBTUZ6
            V3p1S1dmVEZLQjZZekJiZHFqamlUbHcKLS0tIFI4c0FNRm5YV2JnUXRDdEkxb093
            NkhFR09YRkxVOEwwV3dFZmxIaGllZzgKGT48xRdbWz5BAy7OmOlCj12J4fMsLKuA
            xoE/YURvSHfNc3kgJYA92tgp3DlKLVgC3APyBIUlVzg692WWR6ZSew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-11T22:02:31Z"
    mac: ENC[AES256_GCM,data:poay6/DoEHYVnqEcjWhYU8eBknsZHTOTdUmB47OPN5dpCV8Ulc4jPn3gONUtpKE2RBgJpgBboM23fV+NvRLRTe3Zb43qHf5tzsz0ykXZXS218JLVPXUv5otpJuJCh272MRWIj/XKACgWtNyp1WGRZ/CYnYH1oBesBBNgbdIFmJk=,iv:1C8+OENcRXGqp5PSYTShH0mui90Aco87CUqwxJF/z7A=,tag:9rIH6ZhJ042Q34kGCFqUww==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
