---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blog-klimlive-cloudflared
  namespace: ext-blog-klimlive
spec:
  selector:
    matchLabels:
      app: blog-klimlive
  namespaceSelector:
    matchNames:
      - ext-blog-klimlive
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 15s
