apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: database
  namespace: excalidash
spec:
  instances: 1

  storage:
    size: 5Gi
    storageClass: openebs-crucial

  superuserSecret:
    name: excalidash-secrets

  bootstrap:
    initdb:
      database: excalidash
      owner: excalidash
      secret:
        name: excalidash-secrets
