apiVersion: v1
kind: Secret
metadata:
    name: excalidash-secrets
    namespace: excalidash
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:xStrQGizRHgPsA==,iv:oJQjiY9CezUW38I0KGuRutTPuRKMrKEbiPEJ3esdBtQ=,tag:qOU0MssBbu82glFLLd+Xmw==,type:str]
    password: ENC[AES256_GCM,data:O0gazU2676Pi3dK595nojMg4JW2HGW7mOSoGKP9cbGfr/bRCi9YIXhsQ29k=,iv:0MIQVsseE2O8Axn/jvl+K/u4vjdt+vqPO5s6jVd+IOY=,tag:+zV5Q0fUJL9NVt6ZVuA6ig==,type:str]
    dbname: ENC[AES256_GCM,data:5rVA1hsgQ4L+Gg==,iv:2wNE5Soyj8377t3MCgQZvGG8pXa2AJzXDy/QOgHlCvY=,tag:5lwgdOxEerjVWThiCM34xg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:hah+94s2QP3AQyFK9+Pu3HWEl23/TqFSA2EkzpXcm+5nIUlpGi04MpQ9lyc=,iv:SpMKiZnq91lLRSbmCSqI9ry+wzhUmqkkzo3X+H2+IAA=,tag:ZCCGBzR5uDFT6y9L3E8IVQ==,type:str]
    CSRF_SECRET: ENC[AES256_GCM,data:M4EL4U8dYMG67wKjKyZkI7yNqIjnAKrfzWJKlsYezCOO9y4w/u65Z8PAXOM=,iv:W/qGnEl6fl9OrzsDWsbiRvtn4lrl7pq/6HN70PS014M=,tag:HeMj3jpxA1EttmQrL6HEug==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:mWPaIaiAljZbfFr4IrijhOM5Za/mH3IZG/05+Pydkv8uaUy2jFBapA==,iv:etZA6NgDyRPmBjU3YVztQ7457SXE2nIdtZAhuRwdlbY=,tag:aqSO0Vbmtr6HK3mu4crELw==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:UpSKw6ku21xC7EODwtPdpnkCuyyTrFxtS/O6L7ytu9opEFXGh6zK9i8pDvlFzsPRRFgsAA27crmSIGQhHA4LMeRi2Q5cG71ABnLGxhEA2KCMQ7JLCCXWmWyP/C5Utw1hKI9xpCNMiLUFzU80HVDpE3i5u+ipiU2aEED4RNQJmSs=,iv:M3tcbAaK5jongzub0uUkQFU44dxRvp8IYdfybErhVMQ=,tag:dBf4gp735RUoqjie3Ih0zQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZFhXL01taGlTcmlib0hO
            SEV6c0pTZFU2UW5FTU9rNjBXdGFjLzZJZFJBClZDcU1mUUhDSUJ3LzQ2aEpmd1Fp
            N09vVUVaRjFPV0Nqb290L050cXI0WFUKLS0tIFlPdVV3cTZDMnJVY2xiTXB6ZEc1
            cWx2N1FRbG5senFqUVBoeHBITmxNR2cKQJlt8MTFXmu+vpMCV4oQm7qVS/YTPX9m
            DBMbRr9xLD25Srq9iV9WXZ27KnIRBrnF30qLQhWTFwxntsbZM6tz0g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IFJTSlJydyBBbGNaVnAy
            VmFkbGpGVXd5dnc1bjQwVm5laWFXYXoweGlHVWIzK3VwY1JSWAp4T3NtUnRodTVu
            SXNkTXkvQXR4M1V2c0tPR0p6QktnUEczeFFKakVESkFzCi0tLSBBVmdJSnk3TEUw
            YW5jZDI2MzdheXRBZmhJVFR2bUdPaExiZy9JQ0lqRTNvCrFsY6aUhXtLXrJdPmud
            PfcySGBsQFgpKTgkGfR40l8BcYj2AvfQzsiof064hULKUmAlyfRflLSm3WPgzbww
            Tlk=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qgn7ll64pzy4wd64h85xxq386cexa98676zw4raej9rvxl822p782xrjn5z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDY0dUwvQSBBc3ZMRkVN
            OVlaaUpaM1VoRVdmaUczY3N0R1hGTVQxTStHU25lWjdoS2hEcwo0aFpRT2Q5dXdD
            eHo5RE1vejZ2bDZEQkxUVUZaNVNtbjdYdW9CVHA3S3pJCi0tLSA4SDVZL3dyS09W
            a1luNURDUW1tMWlNaGc4YVd3Y1lXc2xvL0tTRWxuMkxZConuFKAWq6Bav8YEIXVg
            CR0OEM6nP3qXwCW0Wn1SCPp0F9xXqkze25vNztGn+W1o8ERYnRBd5NI4Uv7EDrru
            Q88=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtvpgtvl83qxn5kferysjnzrt0zs2svfygeuvqznlupmvtepcwv37v7pace
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-31T10:36:38Z"
    mac: ENC[AES256_GCM,data:M6S4ALZCsYaEu2HEVTIlhKsrVSXteCM7qlrPOCp10y6mXc/oVyNIodoTfeB3bP/QYbO6QkwSLAiJl7a7eCqqYKXBETVQP/krXADBZYY28seqNzhRuYGn/N7xOhRTGHG0hDmwKujKN2/FmntyVjRRMFb0rWa1seMIrj07iDOWuQo=,iv:KA8jG6SM2fpil+PavqhpMBBROtgSXzzb3Odfy83AtpY=,tag:McBjLwkGfKaEOQfl+MNvFw==,type:str]
    version: 3.9.0
