apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-dir
  namespace: kube-system
data:
  authorized_keys: |
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDdiLXSA54np6HfOT218luR7ah9BLTNOL5b5b3Pf6TSfykQhNoWW8pxWxJcarrPgWXWQZ1t65ntD+QUHXQTitErvv26120S894NoHVfW9GZBJeog3QHu/9SMdyKO0ZL2NmllAxSxlDpMi7KAP/KsFkOTRTD96X1CX0ljVCYd2BrwfMo5UCt8SB005P9zc4DM+dM68Re0R0hqY3woM1BF6BzI0EOiHTByeGmse6pEqCYkgA/+u8RROfq60XuyrbmTmBf6al9RZNuF1/vo5Lgz2SpaEXAw+DGOZZpk7XaZ3dq17ovB+fbIKZ731HukhA0D5aUqEDyOPWemAICJ7kRFz8u5qLLz2EygYdxL4Ehjd9P+YhIGC85oGYx9mlAjj+rFd4Uvaq5co8OROdOdCAth07veFPG4KF0ZFB9KIMY/9fOQrNaS0Jg9DtyuNrS/JAFt63HWrF1QBQvhxZNabgd6C8icMH9vv6NxegpMyi8XDITLH+YGSyKZUB/758VpLgIjPUIsm6i4pD3JNMpuQRIM0HENs+cbINEG+8nfX8iwgvp/EPLxQ+aVIJV4hFrlNTeHH7oYZ7tMFJU16ZWpgymOzMf8LnbEWyXHeIl2CZklkjMVJQxNk0BK3R2j5e/fHH+E0YQCD5+ILoIrugFQh5jL672tYOSYpMRsPPyLS/xK2B7QQ==
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: sshd
  name: sshd
  namespace: kube-system
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: sshd
  template:
    metadata:
      labels:
        app: sshd
    spec:
      affinity: {}  # No affinity specified, so it will run on all nodes
      tolerations:  # Added tolerations to allow scheduling on tainted nodes
        - key: "role"
          operator: "Equal"
          value: "storage-node"
          effect: "NoSchedule"
      containers:
        - image: ghcr.io/aarnaud/talos-debug-tools:latest-6.6.29
          command: ["/bin/sh", "-c", "sleep 3600"]
          imagePullPolicy: IfNotPresent
          name: debug-container
          resources: {}
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              add:
                - SYS_ADMIN
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /run/containerd
              name: run-containerd
            - mountPath: /var/log/pods
              name: var-log-pods
            - mountPath: /root/.ssh/authorized_keys
              name: ssh-dir
              subPath: authorized_keys
            - mountPath: /var/lib/kubelet
              mountPropagation: Bidirectional
              name: kubelet-dir
            - mountPath: /lib/modules
              name: modules-dir
              readOnly: true
            - mountPath: /etc/localtime
              name: localtime
              readOnly: true
            - mountPath: /run/udev
              name: udev-data
            - mountPath: /host
              mountPropagation: Bidirectional
              name: host-dir
            - mountPath: /sys
              name: sys-dir
            - mountPath: /dev
              name: dev-dir
            - mountPath: /sys/firmware/efi/efivars
              name: efivars
      dnsPolicy: ClusterFirstWithHostNet
      hostIPC: true
      hostPID: true
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: false
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /
            type: ""
          name: hostfs
        - hostPath:
            path: /run/containerd
            type: ""
          name: run-containerd
        - hostPath:
            path: /var/lib/kubelet/plugins
            type: Directory
          name: plugins-dir
        - hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
          name: registration-dir
        - hostPath:
            path: /var/lib/kubelet
            type: Directory
          name: kubelet-dir
        - hostPath:
            path: /dev
            type: Directory
          name: dev-dir
        - hostPath:
            path: /lib/modules
            type: ""
          name: modules-dir
        - hostPath:
            path: /etc/localtime
            type: ""
          name: localtime
        - hostPath:
            path: /run/udev
            type: ""
          name: udev-data
        - hostPath:
            path: /sys
            type: Directory
          name: sys-dir
        - hostPath:
            path: /
            type: Directory
          name: host-dir
        - hostPath:
            path: /var/log/pods
            type: ""
          name: var-log-pods
        - hostPath:
            path: /sys/firmware/efi/efivars
            type: ""
          name: efivars
        - configMap:
            defaultMode: 448
            name: ssh-dir
          name: ssh-dir
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate

