apiVersion: v1
kind: Secret
metadata:
    name: nzbget-server-credentials
    namespace: jellyfin
type: Opaque
stringData:
    SERVER1_NAME: ENC[AES256_GCM,data:9DP8,iv:6OjcAsa26kXjw8yvhFeh2XokVj8q0GcecIaU8OJA2do=,tag:KYr6dP6dzimTr9QH6MzPyw==,type:str]
    SERVER1_HOST: ENC[AES256_GCM,data:Z8agcwKOzVHI33+wGRNNU6f/Qz2nDBk=,iv:o3IXOMhH6ZLgE+qys3DBWF5kBHqgxFuMjG2yRGEP0hg=,tag:jhGshf/PL3S9gJub8NUNdQ==,type:str]
    SERVER1_USERNAME: ENC[AES256_GCM,data:0yIcgznEbA==,iv:w3aSAbC9zglujKc2Vs/sTsKe/vi13LevLA4r87WL09M=,tag:oZHgiYPemwM2mpnJH2BHfA==,type:str]
    SERVER1_PASSWORD: ENC[AES256_GCM,data:VOi6msdA6juV8cI=,iv:4ZSiLpODAARH0UtMnrE+YwdS98eorsJRHDT86XnLyJM=,tag:72KLoS7Wj9ey7pjUkvlxqw==,type:str]
    SERVER2_NAME: ENC[AES256_GCM,data:r+H/02eSOhJiEogYXA==,iv:VL/+DW7W6PkdGgc9TuaMS7TxlpexgFIePJB3EjXMZDQ=,tag:Ja8Sl2xY89WFef2wgLOgCw==,type:str]
    SERVER2_HOST: ENC[AES256_GCM,data:/dadruCMUW8ovFT9lXHzfq7OTy9/,iv:Kfog82rseKK78IP9Jyg+1wSK5//Y7itjfdsaTHoRggk=,tag:wG/cROtLk+WlEntKIjDRkQ==,type:str]
    SERVER2_USERNAME: ENC[AES256_GCM,data:5o0XCnG7RA==,iv:ikuJe6wtZm7HxVn0iHEJdkgUlY4Jwo5aGaWAeBdfeC4=,tag:qMsf0Hax2kf72pkSDRWtCg==,type:str]
    SERVER2_PASSWORD: ENC[AES256_GCM,data:r98yGEmmUmhpSxM=,iv:oAWj3tKFd9mve13Bbj6YoSpirv33CxDnMSVPWNXG+DM=,tag:+2vw84HUgZPDFpILOgf49w==,type:str]
    SERVER3_NAME: ENC[AES256_GCM,data:XS2bNdHeVOUB,iv:i3cVE8oqdinhvElqNDxSdFzIYX3DQRw6yPtJxoDr2+Y=,tag:yelFn+x5i0tOZXbtqSAvfg==,type:str]
    SERVER3_HOST: ENC[AES256_GCM,data:gXooHBHtrWhcbldR2DDxb04=,iv:/beKTCW6IVq5SoKlAVGdFmQVMQNwfcJ7B0II156cq10=,tag:8X1p31NO7Bimte6/v5Ioyg==,type:str]
    SERVER3_USERNAME: ENC[AES256_GCM,data:n3LQbHKbLBZU,iv:8ggMUb7NAaUsP3X564hACY/kAyJI71UgdEZ7OGHTmKY=,tag:BPyOeAQn6BHNdUyOUXQTqQ==,type:str]
    SERVER3_PASSWORD: ENC[AES256_GCM,data:pRpwBPwl58SNFi+4,iv:cyPiSy34bm2mv6ecjvvLNLZpfNIr/mbCcIjasrET8vU=,tag:LNbTZNce4qteZypfdnDJCw==,type:str]
    FEED1_NAME: ENC[AES256_GCM,data:V8nwLU3KwdLBKiVP,iv:ayAkI5a/cC5QoyyDsx3JgPJgJR1Ld91hE8+spj3UBMY=,tag:iopeJdJBCkf9calrze5OCA==,type:str]
    FEED1_URL: ENC[AES256_GCM,data:DYYQ00LVP0b1JgoR9xrF9uDzQhcQF0vcT4EcjI6cAI2nIbBL0GTwFPtkZAG3NONd4ErWxtB+JC1qXJVEGak5kt5lj4CrHrbaq3pA+SvgpNKkEu1gfQ==,iv:+zpkupifvSvzL4g6WgKmYWt9FcCJ+lUxoQ6ZHDeMDIY=,tag:uyM0TwlV6tZsvWz/tkdTXw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSFdGODhyUVBxa202UmQ2
            ZjVNaEtMYTVLV1RqVHlySStuQTk4eG9ZVTBjCnlsWXBTZXRVVmlheHFOaG16V0xM
            RFVkV2lQdUJ6ZitIaUZDaTFDY2lRR1UKLS0tIEdzMVJpRDN6aTZhaGh0QVNUbXRt
            eHVRVDI0Y3pWNFovWW9ubmZUVFh3WVUKTL/d4+dvx/JHNAm2CRR6twPu/u0kJSA5
            /uB3hZmreVKLNkakxNhgq826tKhilbrVPX3YlIuHoNHZpYFvCNomng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-09T11:42:47Z"
    mac: ENC[AES256_GCM,data:6M9TK5NcuDmipmwQ0eY1v7aYPUBL/ZuhKbB9c6at0Eh+tUWZVHcgJyD2da6PR07uPRyPd4JzDAjMTaCIA5T/uVle+s8l/mMfUDfm7AHX2hlXfHt78Xl/lwo38Y3aYz8m1i8wFQjcbQeRnEh7PQ+4zkWeHfHqEea/yiMVhcVLZog=,iv:p796n0yeeMfQqRI8xCkewpdxfQjp6gxTRL2An4p8dVY=,tag:p16ZYJ2cFzYKq3keEiP1nQ==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
