apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-secret
    namespace: jellyfin
stringData:
    client-id: ENC[AES256_GCM,data:rdvB3cKPHJVmjx50B0TIE9XvOgza0IFOXgbLahIgjwEX+QKjhJgwVw==,iv:DRqH+nkY8sdUmSKrGQ6S8vmoHUx8i4on12U8AzTCGNw=,tag:nQGlZKZhTrS8GFX8o46hew==,type:str]
    client-secret: ENC[AES256_GCM,data:+4B8rxx+Azv9hP6Zd1lzjd5FVSLS24nrmByR0crHkvGywB7Qt9Pf0BVYgofKQXtZc2qa8PXPF+5nKFnO9Mx5edt3aevtQGLIJ5icSRTWGhsHRgQBFTL4HPANZU/yj25RmE9FB++7ecyR0i3gN2wk0Gk/0tDeiTSStzKaxwtvxnE=,iv:+2ZmycyhBFdSqeBliJLcdoTpe8FVXBPBWcIQ9SVo8xM=,tag:w81IM8aHE3tjMDpd/19lgA==,type:str]
    cookie-secret: ENC[AES256_GCM,data:QFBJOzEW45o4riVXFaPx18KGZTQ5yXl6T/VjLc3e6kk=,iv:E0NRO070mgBJDNtGtA7BLSmP++sJwP2/XJ3WktptFBk=,tag:VfeZ4xvrUFuvjgnrA/u14Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNzRaUHM1czkrRnA0a05F
            UHZteFlLZjJSdzBEWEYyLzBGRlhUZnlMVkZRCnpYWDhubWJSL05rM01rVk80bUlH
            MG5wZ3dRN2RmcTQzOHhPNVN0L0F2VjAKLS0tIGVsb1d0RWFYUXVZWU5SZkFTbFY5
            dDlvcFhvd2EvWlJoMTRNNnp1Z2l2bXcKNXyHoDTuRF+AwqlQsAHZNE0/P42Nksmw
            ii6f4oUqJ6MFzjJ5Qvw5Z5/TiT+OnLcuf4yxbKttXZO9HTm1piurYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IFJTSlJydyBBbjJCRXp2
            MGhJdjdpM0R1Nm1DanhzSHo1SVBFVit5UnhtQ0hhazBYZXpDVgpMaE5KamtnditB
            T0VWTUpDOEkwZ3hpaFJTQy91bWZOU3h3cjR2aWVSS3JBCi0tLSA1ZnlHU3pLeURr
            dTUxWEdrYWdiQWZOSnZxaDg5bkZHQ0Q3YVhoTVFLaGJ3CgBfrybD2U38bgBQGhD/
            oOYjQJBleQLm4LfzrE5ANdTJDTgY3xWSVcJqyJd4+rzY1lPWZQkx+ls/NnGvJ65k
            h40=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qgn7ll64pzy4wd64h85xxq386cexa98676zw4raej9rvxl822p782xrjn5z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDY0dUwvQSBBanZyU2F0
            am5MUEVaUjZKeFJnQUNzSjhUUXd6ZGNOZHRXRC90Ry9QdTRFMgpMYzRrZEdQKy8x
            WlZZVTNWZmtLR29naW9wQ0g4YlN0YTZrRHZUVUVUOWdZCi0tLSAvaXBXeHZ4ZmE3
            bEFxdTRST1BqNElEeHNxamg1Um1ET2t3bkpZRG9FL1ZrCg0p+9tdqn26i4WY09du
            W3ncwN1JcmAtK2gjprXP6n56h+o4DkJTkLAcAfX4ldXEb9PpsQtfcMnI4wXhC3Ye
            O+w=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtvpgtvl83qxn5kferysjnzrt0zs2svfygeuvqznlupmvtepcwv37v7pace
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-03-06T23:05:35Z"
    mac: ENC[AES256_GCM,data:c3c0gibS89h0iABUNB87yCx/K1ekNI9eBax93fhrNGofi6f2P4/2k3G0dNiRS9HUyd8adOZCiEO6HCv/wPOLcfmR2LOYL9QqhsQDNx/gvwmamuHK1DeHUdUQQIaTtwkwDkPxa2L1YYlAgJu5SbrCs8iTouMWKk+Vr2Q0KgSZ5+k=,iv:0dHkAwbfRxfrrtqaTUmRUUQpvuIfnKvGqvcLHG3RerE=,tag:rFio3CREinMrBBkMx6C3hg==,type:str]
    version: 3.9.0
