apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-secret
    namespace: jellyfin
stringData:
    client-id: ENC[AES256_GCM,data:rdvB3cKPHJVmjx50B0TIE9XvOgza0IFOXgbLahIgjwEX+QKjhJgwVw==,iv:DRqH+nkY8sdUmSKrGQ6S8vmoHUx8i4on12U8AzTCGNw=,tag:nQGlZKZhTrS8GFX8o46hew==,type:str]
    client-secret: ENC[AES256_GCM,data:+4B8rxx+Azv9hP6Zd1lzjd5FVSLS24nrmByR0crHkvGywB7Qt9Pf0BVYgofKQXtZc2qa8PXPF+5nKFnO9Mx5edt3aevtQGLIJ5icSRTWGhsHRgQBFTL4HPANZU/yj25RmE9FB++7ecyR0i3gN2wk0Gk/0tDeiTSStzKaxwtvxnE=,iv:+2ZmycyhBFdSqeBliJLcdoTpe8FVXBPBWcIQ9SVo8xM=,tag:w81IM8aHE3tjMDpd/19lgA==,type:str]
    cookie-secret: ENC[AES256_GCM,data:QFBJOzEW45o4riVXFaPx18KGZTQ5yXl6T/VjLc3e6kk=,iv:E0NRO070mgBJDNtGtA7BLSmP++sJwP2/XJ3WktptFBk=,tag:VfeZ4xvrUFuvjgnrA/u14Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZazdzNXpZMEFRU0RZS3ZM
            VVUrVlJQT1psMEFWNWlLa1RXY01iRlU3c0hvCkwvV0paa2pEdXN3aXZjU0dmK1Rr
            T0U1M1RIS0J6K01MZWFFN1Q5K1ZtSE0KLS0tIEVtTEhKOUJCRUJuem9zUEdHN3g3
            Y0traVNkUEhPaVdiYU5Tc1JLQWJpazAKWh5FehjWaavg6tguJcm0pAeiUyrxsEMK
            wnTcjqYdU/9qDGOafPBbvkdBYjlqoOFMasPaT+Ktl0ipCtcYwEJ0MA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T23:05:35Z"
    mac: ENC[AES256_GCM,data:c3c0gibS89h0iABUNB87yCx/K1ekNI9eBax93fhrNGofi6f2P4/2k3G0dNiRS9HUyd8adOZCiEO6HCv/wPOLcfmR2LOYL9QqhsQDNx/gvwmamuHK1DeHUdUQQIaTtwkwDkPxa2L1YYlAgJu5SbrCs8iTouMWKk+Vr2Q0KgSZ5+k=,iv:0dHkAwbfRxfrrtqaTUmRUUQpvuIfnKvGqvcLHG3RerE=,tag:rFio3CREinMrBBkMx6C3hg==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
