apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-transcode-cache
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem
  storageClassName: openebs-crucial # TODO: switch to cache
