apiVersion: v1
kind: Secret
metadata:
    name: vpn-secret
    namespace: jellyfin
data:
    DNS_ADDRESS: ENC[AES256_GCM,data:Fy1jFMdqlec3k4hz,iv:kr+XqDGXxDgUMBd5DRKOdTjXyzhVLtMpdRguHRlhHDc=,tag:gkfe2rePzUkr+uarHqU3QQ==,type:str]
    DOT: ENC[AES256_GCM,data:YACXxQ==,iv:iKkUynmf3vwunrKZ+VaG75WlMTS+hBsPXJp6CqcsIAc=,tag:RVc5otuGmVFaHj3nTuxoxQ==,type:str]
    SERVER_CITIES: ENC[AES256_GCM,data:uLOMyl7oVMbuwuNT,iv:rs9+0IFHGRp5YhKdfxVjyEdiKHGe7yP8so40jmFkOKM=,tag:5ZA6axEEX6ZfP5EYmwRquw==,type:str]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:Dr0ZMEUxf4BL8KpD,iv:lkhW1R4VXhNGUTuf2+uS0CzKjMzqUKaRWzUv/UbezEA=,tag:5FsQitrn/N7Xv9eK/KOuLQ==,type:str]
    FIREWALL_VPN_INPUT_PORTS: ENC[AES256_GCM,data:Poo8eEQSNo4=,iv:KflS6ncqP9XDhjK9vqO8GDZXSjiBiqrr7SvL3ruDNrE=,tag:5tJEsehtugJpdC8Kc4yUgg==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:PkiDzt/ACFD8MEZbWBhAA209MXA=,iv:4iS2Wy9g8lciJB2V+RaEuJeciAZsgByRdCJfTKYRkeo=,tag:sPoPjmMBrhLOmJKd8qBKow==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:hOsCSE9EzgbnmWnZ/Ezn8S6nT5meO0PsTU9iFTuUabjbnQgptcG5uvcSS6ph2kJT3p3dlCiqX9MDqJDQ,iv:z2jhz1ZEyjNEDwSqEHRe1AkGLl2Cq/gTptWIpbp1ywg=,tag:nX9abb5gI6g6qW2vvm+uEw==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWFZzMnBNa0dRSXVjZFI0
            cGNBY2FNN3BBMVJ6dnBrbDB2R0NIM1hvajJvCjR1YzFPN01FTU0xUHIrRURMb1E0
            RWxzd1dmQXVlS3VMQzgrYkJacDlmZUUKLS0tIFMxbTd2T1p3OXJ4bUNMQnFudlh0
            L2dPZVhRUnJjSi9hb3pYZTdDU041V00KtIGMdV0/WdGz4ATuKhu8pLMkTdntf5lu
            h5XLPvXLkIzoo66cW9MFWKbp9pRA30DgdgtsiCa+pcPwo4I/umRgkw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IFJTSlJydyBBelVoR2FX
            K25JN2pyMG9UZElGTWhRVkFQM2FyNW1DRXl3bnFJSk5RUkt6bQpodDluN01WSytx
            UkNEclJKaTZNcmpuMUZKUHAyckUrLzhZalM2dUlhR0pvCi0tLSBQaWN1OFhjYStT
            UXZQMEhKcGt1a3lrWmp3ZlpNdGxuUVJ4ekc2UzlVejhZCl/wK1/O6o59TYsb3ZQG
            5jVVChN3zTScTbxfEmw4AIoDcKs7c4ck3jvMa/HJdjC32K2D7DEYqSNhfhP9tgKH
            fUU=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qgn7ll64pzy4wd64h85xxq386cexa98676zw4raej9rvxl822p782xrjn5z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDY0dUwvQSBBeGlaUzRq
            MDJnWnZ6b1p0dlUxUVFRVlBwS3daYzcxcW4xcGtHRmJLa2xrTgpUSEY4Y2JES2tU
            aUxUdHdCWE1YbEM1Q21WY2dwV3RvbXc3YWJvUTN3MjU0Ci0tLSBUL3hGY1lDNFBK
            VCtJZmtobkxHUUNJS3orYmtXdnptZHg1SnhnVHpCVVJZCqsVl2E+qLA8WwpYjKa/
            5a1U3zkzCoMHGHna3ucKfzw5kPKTbQKsadkafZPulVOslDvMARojTWOJfztcZ/cS
            xNA=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtvpgtvl83qxn5kferysjnzrt0zs2svfygeuvqznlupmvtepcwv37v7pace
    encrypted_regex: ^(data)$
    lastmodified: "2025-04-22T02:36:48Z"
    mac: ENC[AES256_GCM,data:XY5DmvkMeaE+r0yAoktnl1Q0fwEBDgVtBKWAssjRnSAAsdWsc/qkjelqAorSKyzdujXLgTzVc1fH+Fti4ajO1n3+ND3CJryryKUWVqkmsqH0PKj+PJx3yHMMMpklcgDM94WkE1MD/SbR8mtc5fESlMeOQ2sc3oU9hrJ/0IyYjR8=,iv:jCSoZ/jk5YaSLzoka5MvoXBK8G4qVEUX/O+Z4KHqdfg=,tag:Gj2Ebz8KeLphbAu7tbWkHg==,type:str]
    version: 3.9.0
