---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-persist
  namespace: llm
spec:
  storageClassName: openebs-cache
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
