apiVersion: v1
kind: Secret
metadata:
    name: playit-agent
type: Opaque
stringData:
    #ENC[AES256_GCM,data:zpX8dAIwqi5WvTr6Es7cOr7fHdPx/+glWGrHALZnkTzQwToqDvh0ZwbAp3xIcu0yWE16FJfuZ33q,iv:sbIgthIIh8HjLQZOBt0KtKz+LLObENYVx207+0Y9wjQ=,tag:CyQ4G8Z3lgE0XgSLmGxfww==,type:comment]
    #ENC[AES256_GCM,data:X8CYRQUW7vUi5aMTzzXLlKtxfiDJHQaVrnImKeQsxsQQ8af6CpJublchrMZ2grtsXXTD7OYhdbBPxmGeS9TuzeZmeBhudEJeMG86e9w2g5df5G8jbAxlo53yxFU=,iv:J08FOqQn6IVUqd8xQN1vSrqXYjxqXK3BfCAj3ojKw8c=,tag:I+y1GYmCODJ3NQpgk4jbVA==,type:comment]
    agent-secret: ENC[AES256_GCM,data:fwijUb3rTObg,iv:XPBOKL4GmsxxFEFWpL2rW0llleDZvnD3LyCYzi15dY4=,tag:7yn3xUF+nGWJ2LeG1Z1kPg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkS1NMQ0NXYlJUY0NaYmha
            cVIrNGtPSk0vclNQWlczMXd1ZStkQW9kSkY0CnU0bG9Jd25ENGsyOGFOa2NMY0xQ
            VE1lL2VxdmgvT2FsSU01UEh1UkRoOE0KLS0tIGpzQTFhbWs2a2gvZmsyUFY2MlVB
            QWJWSUx2NXVSaHA5Y09lZFg5YlVqWTQK33hHWYfuMgOGwsJ8iXPWQhabNBzikkiQ
            sXAYobr2oALGgDJQt0n6sZjfiFDTBcDo8ANFdrYO1YNi9DWf896e3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T11:39:24Z"
    mac: ENC[AES256_GCM,data:bWQLrAfVZESr6cxXFelHlmN2EHcuMLsDe1PxeMhrF/eW/4ZfmuFSOJhQYo2UKSF0GKsSkQubY8eG2myTfYZ6gzKJ/Iq7UuspPf1H9DV9Ji/ai+6ZSOA/j7MmQ4wjTawxP1IQ8o2UdbEUUpCvJ/u38OtVwTsjFahM1DVfU3ozd+0=,iv:qQv4RLDNxCgn/G2hzeZh1tTWw+DTwXjSCiyv6+49agc=,tag:kX9i+D0DTQx8Pp0xW6ncyQ==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
