---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: enshrouded-state
  namespace: enshrouded
  labels:
    k8up.io/backup: "true"
    app: enshrouded-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: openebs-crucial

