apiVersion: v1
kind: Secret
metadata:
    name: enshrouded-server
type: Opaque
stringData:
    server-password: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLUzN3akFxTU1pejlqNE9h
            NlFTVVdNLzdzR1ZWMWZmK2tNMEJBVk9wMUNJCnJwVWx2YXRHclhJWW5MYnl2NnZD
            N29sekFQSUVFKzhvc3JERjdpWW52WncKLS0tIGxCTU1ORTRzOHR0aTl0aGZOR0FY
            MnZhNWlycW5xTVkwajl4bWlxa2pCWFkKyt7BqaSJDjBmxm7cmhuhMKoPv+s/RyS/
            vjeuIiFHwA80UG059VYBjkW22rQx9j6VwIFtfKbmPbAW3jPatRP0pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T15:57:54Z"
    mac: ENC[AES256_GCM,data:sl2fXtMkXjj9t1Cxw2rDtm7B+FSit3ewJ2g5K97Lv8xAupklU+rsGPGCl9WBBEJMCGHsj62CvtCepbXHXKbEdqReyztPv8b45q9Jjav/BZ+PdJD9iLSMr27BkYAo9M29d2sVxzXo5N/SpPG1vx+Z6sJJnJ9nqpEqzg7/GFDhNSg=,iv:jg0VKN0k7482m1dvgdXBj9cP5Sfh0MCOjrv6HZOlRNM=,tag:EFRPWEzoOznoms2D9F5LjA==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
