apiVersion: v1
kind: Secret
metadata:
    name: enshrouded-server
type: Opaque
stringData:
    server-password: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSm1Zd0JRczEyVWZHcmM4
            Um9wZU51N2hGZk51azJiVFlid3hsN2p3MEcwCmpaOHRGWGkvUnNxV2UwK3NOQU10
            cEUxZUFWUXpMRzFBZGp1YjArQmV3UlEKLS0tIEFENjFPRjk5ZkNoejNBL2s4MnM2
            RWlSMHdoZEFlVVBPektZTFluejltdFEKzBWVSp9Tc76+JC7YgHWoGpomtNZN2Gw8
            NOqhC2AmE3IBviVzxO09vZL7/JQkI7R2A5zZtfbRou4UZCQ4/Z6hZg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IFJTSlJydyBBdEgwcXVI
            UVJqRzBHaWd3Sm91K25lVmlLNnJZdU9hQnlJdkl0MFlkNWdMZApBNFFLM2w4c3Zt
            N1REcytyN0NObGQxTUFWaUYvOGtrQUpWNk5HRzc4V2F3Ci0tLSAxVTIyenl3Q0FT
            eTFPRTh4SzFQY1ZmbVVSRmlUSDlSMm5ENDQ4QW5WZ3FRCgv6Z5RthNuugkNXn/iM
            LDKyHtlQVA481RtgG2a1ZsV6SQfvRpxxxk3TCk5nAMQU2XupXOsWELpfUVIw8bsE
            PCI=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qgn7ll64pzy4wd64h85xxq386cexa98676zw4raej9rvxl822p782xrjn5z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDY0dUwvQSBBMjdTTC9v
            ZGViNmwxa2pJWjlQRmVVRHdRV2JxNnRMeDhsSlVZZDMyZDhabwplVXJ2WFIyY0tj
            blUyT2dLYjhWS2ZSSFZPK3RuT1pDM21BNlVHSldENENNCi0tLSBDSndReG43ZWxv
            UlhIc1pyNG9uZG4xK21YNE5nVERkb1lFblFUSXNXZlYwCpcBzDDIyZV/GYHxHE0N
            7rkfkWKTcIvVvbD5eogZmw4acdxKfRHVKIA6kRyR9EGpDclcWSwgYqIP9v/fRlS1
            dJY=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtvpgtvl83qxn5kferysjnzrt0zs2svfygeuvqznlupmvtepcwv37v7pace
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-03-15T15:57:54Z"
    mac: ENC[AES256_GCM,data:sl2fXtMkXjj9t1Cxw2rDtm7B+FSit3ewJ2g5K97Lv8xAupklU+rsGPGCl9WBBEJMCGHsj62CvtCepbXHXKbEdqReyztPv8b45q9Jjav/BZ+PdJD9iLSMr27BkYAo9M29d2sVxzXo5N/SpPG1vx+Z6sJJnJ9nqpEqzg7/GFDhNSg=,iv:jg0VKN0k7482m1dvgdXBj9cP5Sfh0MCOjrv6HZOlRNM=,tag:EFRPWEzoOznoms2D9F5LjA==,type:str]
    version: 3.9.0
