apiVersion: v1
kind: Secret
metadata:
    name: enshrouded-server
type: Opaque
stringData:
    server-password: ENC[AES256_GCM,data:J7O01ebTpgiJZQ==,iv:Ppyxm3Qjx27ZhKGXqIYAWDUd1AaBf8BaYcn5LzxvKYE=,tag:0Uo+F3PUuZAkBTlMvnj4hg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjSUFkdEsxZEtMWWszL3A2
            VXpRZHBuRmVOUndiWVBSUHA0TzJaalN3ZERVCm5HNnBPNlYwbytaR0lPcUVqWHNt
            SWNCU2lYSmcvc2RUamVMWUhLVDl3V1EKLS0tIGVwTHhhNUpPMU0ycWxudWhoNFJh
            T0xqU2FRMnQ3TEoydUtyTjVzd3ExaG8Kxm3qJMu9EYMlE5MC8jM5QzOOyr+qkiKi
            Q0woE66AHAXsoOh2S60QUvevQlpYBUMJuGjEtSLKoz91KRUDYkIjDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T11:34:46Z"
    mac: ENC[AES256_GCM,data:HX1B0Vgq+BXL8DSHDdTO1AQS0dybkmKIhL5j61GU4uMpQDf4vOfKRgm5sdZJFOoIHKt7o10s9pODF84r0qSe6MPqZD2mSsa7SF3H19ugAF9ya/3ADO+vxmiKuUYEYrIJqSRL24n7JOgVNDvxCToqL1lhFON9oom2M89kJKyRD/Q=,iv:PpN8ykcJP2vvZ7JzriyTEdzlKIRE6TZmEno9qAH9/Y8=,tag:vm+x7oap8kv1xuMFFUggYQ==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
