apiVersion: v1
kind: Secret
metadata:
    name: forgejo-mcp-token
    namespace: git
type: Opaque
stringData:
    FORGEJO_ACCESS_TOKEN: ENC[AES256_GCM,data:/dBFnQi89ZafxGi0aXaASyQT+q0PAYIJL7g92UURr4iVawez8F8MxA==,iv:223Zs7rqoh1u0fu+0B0tsQmKkhmVXKiNgdM/YAaFrZo=,tag:9UETDM4O0tqAJfQhuRR5Cg==,type:str]
    FORGEJO_URL: ENC[AES256_GCM,data:BnPyy59aQ8lwS54yY/P06XLegO5ztSIgBaJtmpCZKkJ/ivjSO3nXYw==,iv:i1KuzAdy3ZZ/v/YtX5hK36aHiUS1urR7Apk06YBYX6k=,tag:LxZyEM5NGUUVoiTy9SU7hw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRkhxZk80Q0dncnlpSHE3
            Y0ZKWVp3TmVnSkhFOENiSXZSSG1za0pYb1hVCkNIMEQ5Nmg4U3dGRkFxbXpVZCtB
            YmtZSWtEbnliVTVLdG5XMHliQXprRW8KLS0tIEdIajJkTlZDVWpzN0h6SUd2Rnhx
            aEhNaGFBK25HVU9rYktIOWJXamdvWHMK2/6DU/vN40qCOvwELCADcBa5U0QSLEV9
            r2A7KDGlmLGoPi+Kmr49V0Bwr6TwanHO55B5xHwxAQFpGeD7lF38HA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T14:45:08Z"
    mac: ENC[AES256_GCM,data:v116W85wg3mtSn5lUdzfZqX6XweYeyJJ0qIlITeOEEYCEBDrh03A+ttqVVY5173L5FkIHTWvBSKrdZkp20a9rliimIB0tdUZo0dCovrWQ5bx7Wr39a9jDdg1G6RwOq3SUyc+SqSZJQJbZ7BEMbONCafYbBUGIXgJKn4kZOXHbzY=,iv:Hwfp7T8VQvNBUO48Q0RFcatR8O9D7x9TckV1TN4CSLw=,tag:ksWiK3uzGcqlp/BNUPo9bQ==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
