apiVersion: v1
kind: Secret
metadata:
    name: forgejo-mcp-token
    namespace: git
type: Opaque
stringData:
    FORGEJO_ACCESS_TOKEN: ENC[AES256_GCM,data:/dBFnQi89ZafxGi0aXaASyQT+q0PAYIJL7g92UURr4iVawez8F8MxA==,iv:223Zs7rqoh1u0fu+0B0tsQmKkhmVXKiNgdM/YAaFrZo=,tag:9UETDM4O0tqAJfQhuRR5Cg==,type:str]
    FORGEJO_URL: ENC[AES256_GCM,data:BnPyy59aQ8lwS54yY/P06XLegO5ztSIgBaJtmpCZKkJ/ivjSO3nXYw==,iv:i1KuzAdy3ZZ/v/YtX5hK36aHiUS1urR7Apk06YBYX6k=,tag:LxZyEM5NGUUVoiTy9SU7hw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTSm1sSzEwY1NwVDF4YmM5
            eElVczhUSnRzZmsrU0YwbWxwNThvQzlOUlEwCjM0OVNYak93RnJXODk0bXVnc2U0
            WkhtZXZMYUh4ckJiTnVxTEVkcWpEelUKLS0tIE5OZEcrWTIwcm1jWGVMTE51UXFC
            Q0JCZ3JIZjgxb1UrczZ4NzJVNzFaQzAKLWPO1Sl785W2Lm/sLMF05m0z+j7ih3/0
            B3J/YEaOF1BflF31LomUc1+otVxU3vIU8PwucT2CV8dd1fr/USntmQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IFJTSlJydyBBblRkZCtG
            R2V1aUVLRTQrMXRCb1NyQmhmenJhd2x3c01DM2NOU1hWS0FNNApWcC9NVGFLeVB0
            YVQvd1A5YUJqYXlCbVpzM3lxRi91WkZTcnBmcTR3N3lVCi0tLSBtREErcVBHUkJx
            U2JGYktvZzE5ZS9HcGErY3NyNVFUVlpycW0yY2xEZXhJCuQ7ITbeXCgva4l02c6b
            tfEORK85eYPJsYVyIv8eHMy0JHJ2AL/tWyDKumJ33oNjp/AEkBmOGi+s4FIoNuiB
            eUQ=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qgn7ll64pzy4wd64h85xxq386cexa98676zw4raej9rvxl822p782xrjn5z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDY0dUwvQSBBK3FTN0Q1
            QktrZDE3ZVl1b25EaUlRUk1SM3pudldubzhrUy92c0lPSjBWeAp2ZVRPbnhSTElk
            elRMNE9Bd2lQaG1nTWdPaHE3VVdjNlJDbEEwWXFtMStVCi0tLSBZcVlmS1RyanpV
            eXZxNU1ZYUxVayszelZsSmJyQlVpYUFvV0hzQ3A1WDl3Ci2qsXt5RxZYGTdAuWky
            DuiBfQr2hPW1SCXR2tzsC9/ufA+gQKgtA1jCNdHfmoiHgXjORTe5msp/4y3MyWkn
            Nmg=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtvpgtvl83qxn5kferysjnzrt0zs2svfygeuvqznlupmvtepcwv37v7pace
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-04-09T14:45:08Z"
    mac: ENC[AES256_GCM,data:v116W85wg3mtSn5lUdzfZqX6XweYeyJJ0qIlITeOEEYCEBDrh03A+ttqVVY5173L5FkIHTWvBSKrdZkp20a9rliimIB0tdUZo0dCovrWQ5bx7Wr39a9jDdg1G6RwOq3SUyc+SqSZJQJbZ7BEMbONCafYbBUGIXgJKn4kZOXHbzY=,iv:Hwfp7T8VQvNBUO48Q0RFcatR8O9D7x9TckV1TN4CSLw=,tag:ksWiK3uzGcqlp/BNUPo9bQ==,type:str]
    version: 3.9.0
