apiVersion: v1
kind: Secret
metadata:
    name: forgejo-mcp-token
    namespace: llm
type: Opaque
stringData:
    FORGEJO_ACCESS_TOKEN: ENC[AES256_GCM,data:xNKibMPmVxMdkYhrnf6ss+FBc9f1H2qqIunvVchRkbVdHIfqxuLhnQ==,iv:qsWQIDsZvjq889JRLSvj7k9ByxiKSr21x8JQA6Orp5g=,tag:+Wdip5VhTxXcWWzChebIew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRGJLdHFrQU94eVVEcm1j
            OHRIZ0hOWVNOMXFBMkVJUnN3RStUejdFNXlRCmJ1Sm1jWVQ2SjM3a1JFOXdZSUI4
            NW1CNHllMkdreHdMQTFVNzJIKzFhZ0UKLS0tIGU2KzBmZnF2Q1V6eW1yQ01Pblg3
            c0V4TmsvTzczUTJ0N2MzeVQ2eUFCOW8KqEqIsW12QPB6biJJj/6eDhLDHe46YVc5
            LY93Za9d3sl/Ly4YTwumxbZSKRI0IxgBnKnoGvEU+AcvvGgKDjG47A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T14:45:01Z"
    mac: ENC[AES256_GCM,data:3fGhV8IZRYWgQLHR1VFurch6JqyP/rMiIFgh9VFzIcTKdUWSD/Kzguz7VxPJE/YVhnmz6PV11ExTj8T3uZ8lGn60nxB+EzoyPAnkPCmt+PuJYNtbGMTt/D+zuxDfLZbBAHOwe+8V2QcbwqnpFVFYQqJvZZOQ3eeS8p1lpjvlBGY=,iv:RkJ5P2UITK8hpjxnod3h9yct0/O49d19cxo5KSLat0A=,tag:tdTS6IA9Q5c1e4NY5jH4cg==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
