apiVersion: v1
kind: Secret
metadata:
    name: backup-credentials
    namespace: immich
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:kT3QYdRJTJY5PI92pHgzY207FOHigk1MlQ==,iv:hSBh6r7TRHBY78m094H5aVtJ5xLl/SpEzLULEey8ybI=,tag:rf7EHD98PChBTE7rX7zJxw==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:x0pVjVHpjm7kV4CuLppNJjJWsQfLy9mTFj6xqgDYhg==,iv:qk4UBZaBiPukQwUXxqRgKCzdjz8WQ0RMN0/3rfX9SOs=,tag:asO6HeObHzEghGTFkrpWEw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:DZXjttsCwwxgOLtwjYsNNjNaFVgxFZx1Jrs+sLPB,iv:k3jxPAeOpbR8E53laVlUzgLXGYlVRhGa+zFo5ieoiKc=,tag:EG1cep6Gx6kJspoWE8jRVQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0cEQzZHUvVkdzakZyMVBn
            NXdqd0FDU0J0aUIwQ0I0MGMxSmJQc2J3T2wwClhITDJ1bXVzRE1tVTB2VWtBcFlZ
            REkxejYxcHV4MlV5NUtWaWY0NVkveTAKLS0tIFVjS1RaOGtDVGFpSVZQQ2h2R0do
            SVNyK21pUUNwN2w1TFlrTVdVQXBMZjQK5J60kuPzVyuEH5p40LBAd6enZ2pk3DmF
            hEkm/XfMcvvNOfow7uj9aKqLWDgRXff9bbyAM1lsSvVKA8VPBV/V7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IFJTSlJydyBBck1KQTdN
            ZjE5OHNndVV6TDFhTE14cS81b1Z1c1EyVHdjTkJUVzI1VEpneQpia2tJMU9oM08v
            Ry90enJySU9TcTNiVVBDU0VTZHlod005MzdyeWh2QzJJCi0tLSBMNUp1YmtHak0v
            L2xYeW9mVUFka280c2syK2xKY0FRUzFGcFBLK2hUVXRnCvF0ACYfD80kiRCZy1V5
            ViGzpB2j0FcTcI8D8Ege+O0EhtVP6fN1bSIiFGkGG5hWzL3970L2toCci/sRPEdy
            SN0=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qgn7ll64pzy4wd64h85xxq386cexa98676zw4raej9rvxl822p782xrjn5z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDY0dUwvQSBBd3JkUVYy
            Z3Q2MUE2RnMzY1ZUYzNPbTRvRHRtZWFRTDlmZERaVW1KWEsvaQphOHRIbHFNUk0v
            dFczOG1WMG9KN0QxWjRVSDZ0TkhhSit0U2cvazJFeWhVCi0tLSBscGc4UzRzbUt1
            bGkralV3MlZSVDhyaEJrMnpySiswSS9uM24ycHZoeVM4CkssxmlmlUY1CAs+TVMX
            VjFE7ptHnNmHOK3hYrclSxOEdP+bWwgHWQvQKbsvqUpC1bKd9//PZo9XwiebW258
            J2g=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtvpgtvl83qxn5kferysjnzrt0zs2svfygeuvqznlupmvtepcwv37v7pace
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-05-24T09:52:39Z"
    mac: ENC[AES256_GCM,data:2GdicjldnRE9TBG1EcvLqWzmelduJ1fN882pbb0b5K648ppmTUpfSYoGju0FQz0PbG3koImOV0+I06KMuX4yQnAVD8VjrM/hrBLvH2w9nANEyf+6k6k0gJjCVQCP6Z6X1iNKwF7lWio4Hj2Wwb0MWS1aAnuf/NlBcT+nEaszU8s=,iv:0T0CvhVZ32/1ZwTACDoZ1gm2PGFf55N2tfjWPkXfVk0=,tag:luMvWdPyR3Zqdvsfa1jjag==,type:str]
    version: 3.9.0
