apiVersion: v1
kind: Secret
metadata:
    name: backup-credentials
    namespace: immich
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:kT3QYdRJTJY5PI92pHgzY207FOHigk1MlQ==,iv:hSBh6r7TRHBY78m094H5aVtJ5xLl/SpEzLULEey8ybI=,tag:rf7EHD98PChBTE7rX7zJxw==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:x0pVjVHpjm7kV4CuLppNJjJWsQfLy9mTFj6xqgDYhg==,iv:qk4UBZaBiPukQwUXxqRgKCzdjz8WQ0RMN0/3rfX9SOs=,tag:asO6HeObHzEghGTFkrpWEw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:DZXjttsCwwxgOLtwjYsNNjNaFVgxFZx1Jrs+sLPB,iv:k3jxPAeOpbR8E53laVlUzgLXGYlVRhGa+zFo5ieoiKc=,tag:EG1cep6Gx6kJspoWE8jRVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVY0RGL1lBMlhySWUwanlY
            aUZqUnhCYTcwcFg2QktTdlM1dVFXYTdHc1Y4CkJjZzhINWVYUmhUOUV1REtKYllX
            NGhPaThlWUJyNFJwVklkMzZBbkNCOTAKLS0tIGNIUmpCU2g1a1h1SVRVUXhKMGxY
            NWllK0JRYVJ4QVdoQnBYTjFNbHZQL1EKvInUOa8Ja9oH/j2W0HN6j4Bi3bCO695a
            f83guDsWXlRRNubvrd18t4Ajh6IUYC1gD0aVpy3TqcLpq1V4kFI4DA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-24T09:52:39Z"
    mac: ENC[AES256_GCM,data:2GdicjldnRE9TBG1EcvLqWzmelduJ1fN882pbb0b5K648ppmTUpfSYoGju0FQz0PbG3koImOV0+I06KMuX4yQnAVD8VjrM/hrBLvH2w9nANEyf+6k6k0gJjCVQCP6Z6X1iNKwF7lWio4Hj2Wwb0MWS1aAnuf/NlBcT+nEaszU8s=,iv:0T0CvhVZ32/1ZwTACDoZ1gm2PGFf55N2tfjWPkXfVk0=,tag:luMvWdPyR3Zqdvsfa1jjag==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
