apiVersion: v1
kind: Secret
metadata:
    name: huggingface-secret
    namespace: llm
data:
    HF_TOKEN: ENC[AES256_GCM,data:5whCjJMBSpU46EBg7HdX5KALPvGPwisq14mMLpgGV/WeO1oCMvkIRGZ96ikjpT5VVqMFmA==,iv:Tcb19/5s0FzBL9G4THWzvJibNiQfmkL7e1VIp2AOgyQ=,tag:diXa231fSJHcR5X4ylRDRg==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxVFJuSmlFZ3lFbElmZU1Z
            RDcwYmpPS1ZFOEdjVUYzRlpRL2tFSFh6RTEwClF4TkY1NjdLR3RzcG1Bb0FqMy8z
            QnVWR002QWdsTU9neFRhVWZxYXoxRzgKLS0tIER3YmhNNWNhSG9aRWJRMzFPRWJh
            TnZiWEUybnlUQWZ4aHJYeUhPeUh5QUkK7ihcAE1c2JMww9JtKBHX1xKuPd11OeXj
            zpoDia5tQ0djj6GAVO3xrIT6I0iu4qy6a8vUUJ/tcKX6JnsUsOROvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IFJTSlJydyBBaDh0ZlBL
            ellnUFh3YTFDaS9NbkRoVi9DNE1EMCttY1lsajBGaHkwMmlMVQpCTTBKdU45ZWRY
            TW5TMVFjUHlkOVM3WlovTnhEOExpOWRIR05UVVcyUTZNCi0tLSBwQWlhSHdqWTNx
            cGF3Mjl5Q3NSUGNXOTVaQ2NTQmhVODBKVDkrMzgrem1nCq72yhw2SiBRrEfL0NRv
            J8F3IlcK5zDJ1uugnB+ny94LgqCAywqWtsl/AI0z5I5KpFH29riVa+k9PYkqN4ZY
            OsY=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qgn7ll64pzy4wd64h85xxq386cexa98676zw4raej9rvxl822p782xrjn5z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDY0dUwvQSBBd2VQTTlk
            bmtuWVBGb2ZKa2VsdEtRMkZVUkk0ekQwY0RTQmNWRmJIdmlGaAp6aWlmWm4xeUJ3
            UXdDaFBrQnk1OHNWcmJBV2ExUU1KaGJacTVZREJndTJJCi0tLSB6Z3hjZGRTSkQ1
            dUJxSllrRUhSWmpsZDQrZk5WemZFNDBGTjBUOWxQVlMwCnF4+pU/vbwOJkQ9NyZt
            bCTkQ0Ge8+CjF4IyGw+cpb2aGpMiiMVEeZsVLwpATNbhd8NolebQvmou1yDGOnMh
            9A0=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtvpgtvl83qxn5kferysjnzrt0zs2svfygeuvqznlupmvtepcwv37v7pace
    encrypted_regex: ^(data)$
    lastmodified: "2025-04-30T09:35:35Z"
    mac: ENC[AES256_GCM,data:Y+pZM89Ge4LBSKkAH8Nc9Ul3Kc6lUJs7f7n4hPLbltTTz9pNUzXP9m79PIahzET6gEan5BOd8uPpCfPhu/O77Rb3+qIhXSQee0TSqzGeuXUCbPd0DosUC9hpmsqBKlwNjzJgHOfP2Lq4MUv0bEd2SVZ64WkAbRcxyj3fnhMYPcM=,iv:nt82yGz3rKvUC1SV+HMuageVaZPjVnhnm+Uw9cBDtJw=,tag:uUsZJk8O8Zyb/L5MIZm/DQ==,type:str]
    version: 3.9.0
