apiVersion: v1
kind: Secret
metadata:
    name: huggingface-secret
    namespace: llm
data:
    HF_TOKEN: ENC[AES256_GCM,data:5whCjJMBSpU46EBg7HdX5KALPvGPwisq14mMLpgGV/WeO1oCMvkIRGZ96ikjpT5VVqMFmA==,iv:Tcb19/5s0FzBL9G4THWzvJibNiQfmkL7e1VIp2AOgyQ=,tag:diXa231fSJHcR5X4ylRDRg==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0amZWdlN5WUhOY0dMYWR4
            NHB4Zmo2VG0ya1BKSm1QN1hXazI4a1FtMFhvCjNXR08rK09sWVVFT053Vzl1M01T
            UnJXZHc0MTNLM0RBOERZY1JzRVVxdzQKLS0tIEFJakJYNnVKMDM5KzEzV0k5QXpq
            MVhTZERWUkZNQW4wcGdka1N1eXpQVUEKY2Oq9+CCvmXdDvnEEtOYBhkcUYsw6JFB
            hYLsD4eBxy15e8ImUiiD9LNgVMZ9qe/3psG9IEiqZKk4bG0WRSC1gA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-30T09:35:35Z"
    mac: ENC[AES256_GCM,data:Y+pZM89Ge4LBSKkAH8Nc9Ul3Kc6lUJs7f7n4hPLbltTTz9pNUzXP9m79PIahzET6gEan5BOd8uPpCfPhu/O77Rb3+qIhXSQee0TSqzGeuXUCbPd0DosUC9hpmsqBKlwNjzJgHOfP2Lq4MUv0bEd2SVZ64WkAbRcxyj3fnhMYPcM=,iv:nt82yGz3rKvUC1SV+HMuageVaZPjVnhnm+Uw9cBDtJw=,tag:uUsZJk8O8Zyb/L5MIZm/DQ==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.0
