---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-data
  namespace: llm
spec:
  storageClassName: openebs-cache
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  namespace: llm
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-python: "true"
      labels:
        app: open-webui
    spec:
      containers:
        - name: open-webui
          image: ghcr.io/open-webui/open-webui:v0.9.2
          ports:
            - containerPort: 8080
          env:
            - name: OPENAI_API_BASE_URL
              value: "http://llamastack-proxy:8322/v1"
            - name: OPENAI_API_KEY
              value: "fake"
            - name: ENABLE_OTEL
              value: "true"
            - name: ENABLE_OTEL_METRICS
              value: "true"
            - name: OTEL_EXPORTER_OTLP_INSECURE
              value: "true"
            - name: AUDIO_TTS_ENGINE
              value: "openai"
            - name: AUDIO_TTS_MODEL
              value: "hexgrad/Kokoro-82M"
            - name: AUDIO_TTS_VOICE
              value: "af_sarah"
            - name: AUDIO_TTS_SPLIT_ON
              value: "punctuation"
            - name: AUDIO_TTS_API_KEY
              value: "fake"
            - name: AUDIO_TTS_OPENAI_API_BASE_URL
              value: "http://whisper-open-ai:8000/v1"
            - name: ENABLE_PERSISTENT_CONFIG
              value: "false"
            - name: ENABLE_OAUTH_PERSISTENT_CONFIG
              value: "false"
            - name: ENABLE_LOGIN_FORM
              value: "false"
            - name: ENABLE_SIGNUP
              value: "false"
            - name: ENABLE_OAUTH_SIGNUP
              value: "true"
            - name: DEFAULT_USER_ROLE
              value: "user"
            - name: OAUTH_MERGE_ACCOUNTS_BY_EMAIL
              value: "true"
            - name: OPENID_PROVIDER_URL
              value: "https://auth.klimlive.de/application/o/llm/.well-known/openid-configuration"
            - name: OAUTH_SCOPES
              valueFrom:
                secretKeyRef:
                  name: openwebui-secrets
                  key: OAUTH_SCOPES
            - name: OAUTH_PROVIDER_NAME
              valueFrom:
                secretKeyRef:
                  name: openwebui-secrets
                  key: OAUTH_PROVIDER_NAME
            - name: OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: openwebui-secrets
                  key: OAUTH_CLIENT_ID
            - name: OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: openwebui-secrets
                  key: OAUTH_CLIENT_SECRET
          volumeMounts:
            - mountPath: /app/backend/data
              name: open-webui-data
          resources:
            limits:
              cpu: "1"
              memory: "3Gi"
      volumes:
        - name: open-webui-data
          persistentVolumeClaim:
            claimName: open-webui-data
---
apiVersion: v1
kind: Service
metadata:
  name: open-webui
  namespace: llm
spec:
  selector:
    app: open-webui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 8080
  type: ClusterIP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: llm
  namespace: llm
  # labels:
  #   external-dns: "true"
spec:
  parentRefs:
    - name: services
      namespace: infra
      sectionName: main
  hostnames: [
    "llm.klimlive.de"
  ]
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: open-webui
          port: 3000
