---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secret.yaml
  - postgres-pvc.yaml
  - postgres.yaml
  - atuin-pvc.yaml
  - atuin.yaml
  - route.yaml
