apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: database
  name: database
  namespace: atuin
spec:
  storageClassName: openebs-crucial
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
