apiVersion: v1
kind: Secret
metadata:
    name: atuin-secrets
    namespace: atuin
type: Opaque
stringData:
    ATUIN_DB_USERNAME: ENC[AES256_GCM,data:nrI5MPg=,iv:hTdo7zXV/eldoQQMN6g9ESnYnUlIG3HnYc9csJFIiQY=,tag:XRudrCsd71yF7QBQglnDrQ==,type:str]
    ATUIN_DB_PASSWORD: ENC[AES256_GCM,data:KGbryIQb0miLjj2TKhje2BPX,iv:WNfCCRR9RNoAIyNCxS6bP85iZXz8p76oD+ixU0D7GHc=,tag:UlKWw2RBdLOYCMFc3opXzg==,type:str]
    ATUIN_DB_URI: ENC[AES256_GCM,data:RVLHrg0t0KAtpCOfj+LkbyEsya7Z1eYTJGN2C2dUUk3ftQTeYR6ljZC9Xd8azqLIaTI=,iv:9TpMWt6CEq/Efnt8em4Hp+jBgSTXYNDpCVLFN64bdaE=,tag:xJ148umpuy9dySFPrlvrJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWTVMrZzEzVjBqTWlxWlp5
            T28rRFk0WkN5Sk1aR1B0c0czM0hhWVlaMVI0CnJtam5NOGZsbmtNbHE0TEhTdmhx
            RVZ3ekhGeVBYdVBGbloySTllSDN2R28KLS0tIFE5MWlnQWw3aktjb2JUSS9SbzVv
            alVqWm54eURYenZsVHBDd0s1emJWcUUK1CSFOYmCA6f7hZ7q0A13gOlSxeGc0acV
            cKp4LivLYYMEDPGGvCx1ZZ1lx8i4k2cutPZOP3EXrrP0tDicjn7Ybg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-31T10:38:35Z"
    mac: ENC[AES256_GCM,data:tRLGRwUSAdxMqAz7XVQu/TiVqhxKjMM588XhjIBM1C8zkU+87ZsPLcXOgFZ2fYstA54R5Tiq9SMAkq6aKVlTPGs1M7yLDfC92OKLmXE8gbfo6eb+h56uAGaieJ+H1k4/HudCO2NqjhnL/qIzafwRA3NP8xiRwFnhN4KiGvJPozw=,iv:THvNUAf+eD6HYzT6TO7ZhFS7IW/yrNKZTkhigml6gic=,tag:vAz5JvbvsmGnVGbfXtkZrg==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
