apiVersion: v1
kind: Secret
metadata:
    name: atuin-secrets
    namespace: atuin
type: Opaque
stringData:
    ATUIN_DB_USERNAME: ENC[AES256_GCM,data:nrI5MPg=,iv:hTdo7zXV/eldoQQMN6g9ESnYnUlIG3HnYc9csJFIiQY=,tag:XRudrCsd71yF7QBQglnDrQ==,type:str]
    ATUIN_DB_PASSWORD: ENC[AES256_GCM,data:KGbryIQb0miLjj2TKhje2BPX,iv:WNfCCRR9RNoAIyNCxS6bP85iZXz8p76oD+ixU0D7GHc=,tag:UlKWw2RBdLOYCMFc3opXzg==,type:str]
    ATUIN_DB_URI: ENC[AES256_GCM,data:RVLHrg0t0KAtpCOfj+LkbyEsya7Z1eYTJGN2C2dUUk3ftQTeYR6ljZC9Xd8azqLIaTI=,iv:9TpMWt6CEq/Efnt8em4Hp+jBgSTXYNDpCVLFN64bdaE=,tag:xJ148umpuy9dySFPrlvrJQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhN0RzQVU0dkNIY04vUXZX
            ZEhHVlQycXo0U0h1Rkx1MlZWVGNsRE5SQ0VrCnJLekk3c3B6c2dETTQrMHpIZTg0
            M2lEMGt3LytHSUY0NTVVWW0vMXNvWDQKLS0tIEtkRlJCRWFQb010c0o5d01kMWRO
            Y0h1eTMvUHZYSzNYWG9pYUJEeEFWclkKR3aX3th/tV71a1foFOSPYJaRhrbpHrmE
            NTYduNWZR/in7dYxV/lv0r8swadqIaOpro5xkDa1Kb8QNebRtiVQtQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IFJTSlJydyBBb2kwL0E3
            WUVITFBjamhxWVA2cXMzVWtxZWRoTzhlb2dkOUI4WElhYjhYTwoyOWY5WFdTY0tF
            ZzIwL0xIZUZWMFNINllLRHlHYnA4WjBVR0dIbHpXZGVBCi0tLSBrdlBJTjQ0N1h0
            TzZrYVpyY0hOamJ6SWswR2V2Rk02RC9xNGNEQlc3bFlBCsXCBHmZRlceO+HTBQG9
            V295R73T4HeOHNlPlwtDDibdJbtCOrSyH8lp8nopcPm3ZHN4xBoFdwJTH4i4K2j7
            9NU=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qgn7ll64pzy4wd64h85xxq386cexa98676zw4raej9rvxl822p782xrjn5z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDY0dUwvQSBBNU8wWjJh
            Nyt4VDBTN3NpUjdrUThGZVNLVWhQU1JiMEcyaE55N0g3U0gvRwpaaEdZMU5OTWYw
            V3kxekxZYit1Rms3U2xJVHQxRS9TRXdrdVRUUXhaVVdRCi0tLSBYTi9taFU1UWp6
            UlNOMFdDNFBnQ0tmUDFva25hUzVHUGIxV0YyWk1KdFhvCp0RcxVtNUxFDFWff+3K
            Ohcb3w3MmjYWB99nHzVxlTPyRLjfFCjaKj6r8CGJDlK/vRnv5oTXL7QfMCY1It1n
            tFc=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtvpgtvl83qxn5kferysjnzrt0zs2svfygeuvqznlupmvtepcwv37v7pace
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-07-31T10:38:35Z"
    mac: ENC[AES256_GCM,data:tRLGRwUSAdxMqAz7XVQu/TiVqhxKjMM588XhjIBM1C8zkU+87ZsPLcXOgFZ2fYstA54R5Tiq9SMAkq6aKVlTPGs1M7yLDfC92OKLmXE8gbfo6eb+h56uAGaieJ+H1k4/HudCO2NqjhnL/qIzafwRA3NP8xiRwFnhN4KiGvJPozw=,iv:THvNUAf+eD6HYzT6TO7ZhFS7IW/yrNKZTkhigml6gic=,tag:vAz5JvbvsmGnVGbfXtkZrg==,type:str]
    version: 3.9.0
