apiVersion: v1
kind: Secret
metadata:
    name: bersch-secret
    namespace: ext-bersch
type: Opaque
stringData:
    tunnel-token: ENC[AES256_GCM,data:R+0yrj99wb/wGJ37iCfsN7gh25310qxqBdjSwDILmqOQGu4bjTCPz2pXpyWobWDN/R2JvmWRWkFF1RSF7zdgMX7wQ1DlDxyUtEhwkBL3qBH56ozijMoIrjMaY/MkFt+Ost6Lke1kn/gc8wLJ/whd7KXjgz/V/jbLX8hiiYF9L3fFf/tnHsrxRKb+P67Wkea8RsC8Ht0rFE4OiVjs2wPbA6d7rmKKnPS4dvzYskPxm5bS0oA1YSRgtg==,iv:iS/l3wLBQVmgUqLumwaqfC0eX+2que8ybmhTAm2eT68=,tag:z4rYoe9m8Ev0kD+AJf/x2Q==,type:str]
    secret-path: ENC[AES256_GCM,data:+W5aH97XiBxAE3rXfFLlj4bgXu4=,iv:/Q79SDuxqFlE70UiI3b1iSzOq6B67nUl2YRWGMMk/fc=,tag:9Puhsieb87+z7z8nC27pxg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzazZYY2p3RElnM0RiTjBo
            Q1BicTI4TE9zV0pwK2h4Wm1peVRKSXRTcFRvClB1SnNOR3RiRXN5R0dQOGxPSDVT
            QmYrK2NUK3FCTzc1RTV3VzdoUHBjL2MKLS0tIFZjeUxJV2FnTVRkK2ZyRkt4RmZ2
            RXlqcFJ6NlVVaHZmS2wxSXFwTEVIWXMKHv0RFC1wm2Q38PKPrmA5dfVInPObVWH7
            a6JcHMHLEyMDFlA0uDdBvLys3QoHkL0VNDfqGm129hAhoUbEt6+zmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-14T21:50:04Z"
    mac: ENC[AES256_GCM,data:w4SwRxbSIZJh+2Cxi0IjNiSLTVvn24bUd+wIWQMpPSSELlYl92x0AZu2AUdYaF/gYGx+s+KJReg5S/+smMzW99gLLizSLg5KBfOw63LyJi8BjCupA0mWWNQz2omYuYNAI695B015tzxnyxq5901tJI2tpY8p5+v8cYjQVfUEO6Q=,iv:Mv6YQcF85/Z9az7H22i1kW44Uar7BOIkPferayG5qKo=,tag:J9YD/PS7M6W0RCeW17qXOQ==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: bersch-pull-secret
    namespace: ext-bersch
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:vd59RruBQjb59f3+1bMvdl9tizCyWqQ6i330K/+LQbIJoE0lF3HshFAQXoywjPFbbGsXsngTPS3A/jApEoGqDgjB8Bo1xq4wtKy9Wr9cZjtvGbk7oti4EvQG8jW6W1a5qzS5V6rvYQZlHP//+sZgGI2cn+5EAJPdoky9qbI=,iv:o+uMe9CePuBRAO7urxjfk+Qnr3I2nRnLjHdk0p0K3c8=,tag:Db1Bus24qgwIPBPhlyrKNw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzazZYY2p3RElnM0RiTjBo
            Q1BicTI4TE9zV0pwK2h4Wm1peVRKSXRTcFRvClB1SnNOR3RiRXN5R0dQOGxPSDVT
            QmYrK2NUK3FCTzc1RTV3VzdoUHBjL2MKLS0tIFZjeUxJV2FnTVRkK2ZyRkt4RmZ2
            RXlqcFJ6NlVVaHZmS2wxSXFwTEVIWXMKHv0RFC1wm2Q38PKPrmA5dfVInPObVWH7
            a6JcHMHLEyMDFlA0uDdBvLys3QoHkL0VNDfqGm129hAhoUbEt6+zmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-14T21:50:04Z"
    mac: ENC[AES256_GCM,data:w4SwRxbSIZJh+2Cxi0IjNiSLTVvn24bUd+wIWQMpPSSELlYl92x0AZu2AUdYaF/gYGx+s+KJReg5S/+smMzW99gLLizSLg5KBfOw63LyJi8BjCupA0mWWNQz2omYuYNAI695B015tzxnyxq5901tJI2tpY8p5+v8cYjQVfUEO6Q=,iv:Mv6YQcF85/Z9az7H22i1kW44Uar7BOIkPferayG5qKo=,tag:J9YD/PS7M6W0RCeW17qXOQ==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
