apiVersion: v1
kind: Secret
metadata:
    name: bersch-secret
    namespace: ext-bersch
type: Opaque
stringData:
    tunnel-token: ENC[AES256_GCM,data:NiRqwpzf9B/Y2cKhFoyECasoTwOyHgd32CzudVmdZ2hv8XdlHf/9ZuQ7q1VmY1XEVolQb0g/Kp/9HSfcXQUWT53enaNcAww/ciqnUIOtDXjlWzTKUMhjTW6GajSgCjpC65ut0RZmpc5Lton3nVAVhzOqnQeezCNE2rV1zZvZoqBg04SH8IviJOoN9sQIutDevcjcFek0LmF5jvBkpCneSM098poI4eBq+laxkCdwXG2l3p0NwrN0Zg==,iv:iS/l3wLBQVmgUqLumwaqfC0eX+2que8ybmhTAm2eT68=,tag:y0QeYAgR6Jjk5nwV9SqXbQ==,type:str]
    secret-path: ENC[AES256_GCM,data:1NPBFG1iO2J/FQZ+mU8GnnXRrcQ=,iv:/Q79SDuxqFlE70UiI3b1iSzOq6B67nUl2YRWGMMk/fc=,tag:uemiwrocb+gMFESfY+jRAA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnM1N6Z3J0MmlWaDEvVWsx
            dks5RDJISnRRUmVLOHdNWmZNNVZpOUN0elNRCk9PeVQwRy8xNmtPekhDZkJvaEN0
            NG9oOG5UeXZ0SzBwYmRkSXlzRW5QV0EKLS0tIDBKQnlFRGJMeTV4ZWIrNEdWOWRZ
            dDZkeExZQnBnZnF4U1QyNFN0RE9zT2cK1TIsHCub3Vn3mBuC0L2wEPq61FaL7N69
            kn3YcwYGhqf5v0lr8Tv2/YjfWXkDMXWuebap8JLLO5qvT2+VB4JSeA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IFJTSlJydyBBb1JYdDNv
            ZGlrWmdaUEVlYUQyNGdYMW1tc3FnbGNORm5RSzFzaUxvNnRCbgo3SVplekdpSEIv
            VzFwZTh1aUJ6UzhsVVFDdkcxZ2h5UGJ4aHpWbm50V2N3Ci0tLSByTzlVclZxSUx3
            TWdTTWdyZ2pwYmtWUktXS29OR25MaUM5djY0T0RIcmFRCtHt95elmmFA0U0MF+us
            k8j9BtzFrM5ZM4zbl5RK1AQjdssKbbm+bzCbpaGeRb1XIeXT88YzBozG6FzPACIW
            c1w=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qgn7ll64pzy4wd64h85xxq386cexa98676zw4raej9rvxl822p782xrjn5z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDY0dUwvQSBBK3FTc1Jl
            UG5nU21OL1FodGFWS1RkRXlyYVZwcGphT2k0ZGMwYzlSUERnWApnZzVhM25IeHdF
            RzhhNUg1QnFGbitxeFE3bjRwcVdqTXppUVoySTZpdXNZCi0tLSBvdWlPdklJUWFn
            ekJ1SGl3cytwa3Njb1ozMFJBWUdWTUNjQWd0dzgwa1NBCvdUdmxMFnW9yjXR+00l
            GtlmKTV3/5trKory5dr43bn4an7AEXXXXDiFta+7GQyPSeI0ES9miDshznGpFi/U
            ONQ=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtvpgtvl83qxn5kferysjnzrt0zs2svfygeuvqznlupmvtepcwv37v7pace
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-02T12:25:17Z"
    mac: ENC[AES256_GCM,data:JshpKcA42s9U1iNmwvBbtQjyqHzN0zuhs1PdzjaNY0FWn3eLJcFFbN6gT/8SY+A+NQjNdQvH68x9D1hkTavz9z85x/E9nE+CiwL9e3WNqT01/VKyteL0B3cZW/1asIJ6FUAvrtYmYmblw+lzrHTCaD5KlzfnrsHOoUynIYqzEaQ=,iv:g9QoZ40+gpeMrV8mzm4UiRbPgWLIxtztaGUznNpdB3c=,tag:PamPAsvH914b8NRTB4XwPA==,type:str]
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: bersch-pull-secret
    namespace: ext-bersch
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:N+DdL69ART7moyo//V13kVoN8yMTclNXcNT9+3xRAXSqGlFQ8VPE7MWO3/do3m191wSeYbJECU71wQxuyONCcl8GOIEnJwxu+1rDSK4JdDvcEzwzySWv++KJh/Jz3GzlwNUGWv5IpEOFaxJdTw5CHXQSDmjIy0rxaH5MAmY=,iv:o+uMe9CePuBRAO7urxjfk+Qnr3I2nRnLjHdk0p0K3c8=,tag:yZ66/CcT4kzbq700EM5wVA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnM1N6Z3J0MmlWaDEvVWsx
            dks5RDJISnRRUmVLOHdNWmZNNVZpOUN0elNRCk9PeVQwRy8xNmtPekhDZkJvaEN0
            NG9oOG5UeXZ0SzBwYmRkSXlzRW5QV0EKLS0tIDBKQnlFRGJMeTV4ZWIrNEdWOWRZ
            dDZkeExZQnBnZnF4U1QyNFN0RE9zT2cK1TIsHCub3Vn3mBuC0L2wEPq61FaL7N69
            kn3YcwYGhqf5v0lr8Tv2/YjfWXkDMXWuebap8JLLO5qvT2+VB4JSeA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IFJTSlJydyBBb1JYdDNv
            ZGlrWmdaUEVlYUQyNGdYMW1tc3FnbGNORm5RSzFzaUxvNnRCbgo3SVplekdpSEIv
            VzFwZTh1aUJ6UzhsVVFDdkcxZ2h5UGJ4aHpWbm50V2N3Ci0tLSByTzlVclZxSUx3
            TWdTTWdyZ2pwYmtWUktXS29OR25MaUM5djY0T0RIcmFRCtHt95elmmFA0U0MF+us
            k8j9BtzFrM5ZM4zbl5RK1AQjdssKbbm+bzCbpaGeRb1XIeXT88YzBozG6FzPACIW
            c1w=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qgn7ll64pzy4wd64h85xxq386cexa98676zw4raej9rvxl822p782xrjn5z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDY0dUwvQSBBK3FTc1Jl
            UG5nU21OL1FodGFWS1RkRXlyYVZwcGphT2k0ZGMwYzlSUERnWApnZzVhM25IeHdF
            RzhhNUg1QnFGbitxeFE3bjRwcVdqTXppUVoySTZpdXNZCi0tLSBvdWlPdklJUWFn
            ekJ1SGl3cytwa3Njb1ozMFJBWUdWTUNjQWd0dzgwa1NBCvdUdmxMFnW9yjXR+00l
            GtlmKTV3/5trKory5dr43bn4an7AEXXXXDiFta+7GQyPSeI0ES9miDshznGpFi/U
            ONQ=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtvpgtvl83qxn5kferysjnzrt0zs2svfygeuvqznlupmvtepcwv37v7pace
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-09-02T12:25:17Z"
    mac: ENC[AES256_GCM,data:JshpKcA42s9U1iNmwvBbtQjyqHzN0zuhs1PdzjaNY0FWn3eLJcFFbN6gT/8SY+A+NQjNdQvH68x9D1hkTavz9z85x/E9nE+CiwL9e3WNqT01/VKyteL0B3cZW/1asIJ6FUAvrtYmYmblw+lzrHTCaD5KlzfnrsHOoUynIYqzEaQ=,iv:g9QoZ40+gpeMrV8mzm4UiRbPgWLIxtztaGUznNpdB3c=,tag:PamPAsvH914b8NRTB4XwPA==,type:str]
    version: 3.9.0
