---
apiVersion: v1
kind: Service
metadata:
  name: llamastack-agent
  namespace: llm
spec:
  selector:
    app: llamastack-agent
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
