---
apiVersion: v1
kind: Namespace
metadata:
  name: kepler
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kepler
  namespace: kepler
spec:
  url: https://sustainable-computing-io.github.io/kepler-helm-chart
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kepler
  namespace: kepler
spec:
  releaseName: kepler
  interval: 1h
  chart:
    spec:
      chart: kepler
      version: 0.5.14
      sourceRef:
        kind: HelmRepository
        name: kepler
        namespace: kepler
