---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - tailscale

resources:
  - cilium.yaml
  - metrics-server.yaml
  - kepler.yaml
  - cert-manager.yaml
  - envoy-gateway.yaml
  - storage/openebs.yaml
  - storage/disks.yaml
  - metallb/metallb.yaml
  - metallb/config.yaml
  - nginx-ingress.yaml
  - observability/operator.yaml
  #- observability/config.yaml
