---
apiVersion: v1
kind: Namespace
metadata:
  name: tekton-pipelines
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cdf
  namespace: flux-system
spec:
  url: https://cdfoundation.github.io/tekton-helm-chart/
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tekton-pipeline
  namespace: tekton-pipelines
spec:
  interval: 1h
  chart:
    spec:
      chart: tekton-pipeline
      sourceRef:
        kind: HelmRepository
        name: cdf
        namespace: flux-system
  install:
    createNamespace: true
  values: {}
