apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: immich
type: Opaque
stringData:
    tunnel-token: ENC[AES256_GCM,data:qYq3yH18YTWy0z9gOXKykjvbdUJc3hHPcdf/iHkqTr2nxEtM6yhz/h/+w944hk6ZMLLnY4Rkt57wfEmjzIXyKkirVOwMPzszvMHe+1H/4kUwGnVeG/emgUjIEkz7C4aSqS4qLHkzbwGm1uQXxDulZuUJem2mOPr3TAeInBsyWZ2n3B4JPlXi7aLSevwNDt2o82gUuSPPUVwwLF2Z2GnH4shgz0KdxnUfsiVzVg0/LCJ/uhy+bPutag==,iv:vosh0rZ2c1xgOCz0utaXpedO7MN7OUV9ZArBDML9LXM=,tag:9sn9e2Cu08QqBXcWEL26Fw==,type:str]
    public-base-url: ENC[AES256_GCM,data:yMXNAcErsdrmKE9AJfJfuecV8ovEGMGLiLp+tztN59jF,iv:XhwJhJXm52LeTaDkIDlMdDtSchnxNtl+brq9CS+dkRI=,tag:eogPKze580M14nL6FravAQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZFViUlVGWldJeHJ3QzZU
            V1pScENOYXZTSHNsMjdJVlhHTE5qdTlkclRBCmZFc3Z5RDBlcnRwVEc0bElYT1Z3
            QVBaV1Q0UlVoditieVBsaUwzNUVSRk0KLS0tIGtVOVNiZWJnNE5MdjNHWUlFZlNl
            aDd5UVhNVFFIRHVJb00rVGlTbzZUcXMK+twBh12tATCrZIymRKUgmyD40R0MFVTG
            muOWAYsiB2BTyUN8UEgq5DVM+OLEHS817RtjgHslSvpvrgwjySVEvg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IFJTSlJydyBBcG9XcWFF
            Q2s2SGwzM0ZjTlFrRFlaY0YrUVd0UTB6bFk1dFB6TFlmeklrUQp0ODBsRmt2aTdR
            MUV1bTRuc1IvNEh5NlhCdFhFUXcrNkYxWHFsVDZpL3ZnCi0tLSAxQ1haeUFuNWRN
            VzhZYU1BZW5nT0JqaVF1RFpUY21uZzlGRWtnZ05hZlRJCueQgyzD1HwdkstW6Pn1
            k4yUXP3guWNKD8kWP8LVPh9EG6BLqS3VWlGMdaYRbJo5gK9WcVuKt6ABfcEqfxtW
            KXE=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qgn7ll64pzy4wd64h85xxq386cexa98676zw4raej9rvxl822p782xrjn5z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDY0dUwvQSBBM3FmbDhy
            R3NmV25ZZlgyVUVXNWU2V0toRnJZZVBlbnFITHgvVWdQWEo0RgovdWNFQXIrZ1dC
            dndtdDlaVTdsY3daSjRBNVkrZTN1WE9FUnZ1c2Q1R0Z3Ci0tLSBHdkdOTUFqdXVq
            d2thK1pxV1kyaFhJbExTallYM3VyWXZRR2dZQXd5ZDljCsTO/LcQS8HEYvBScW4b
            ySIt1kmgsCinX37jtnrFe9eoj1NHqDTTTOPd2Rkx5LOKghD8sjdM8BawzJKeY5GV
            f+U=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtvpgtvl83qxn5kferysjnzrt0zs2svfygeuvqznlupmvtepcwv37v7pace
    encrypted_regex: ^(stringData)$
    lastmodified: "2026-08-13T17:41:06Z"
    mac: ENC[AES256_GCM,data:yR6SqevWkHk3NDnKgH8/O0cW+8esL6lEqci8nA/vnr2xKFsxGytPQL0/nnkEdXtjkCsiPkHBv2cSd7Sm35cU1WpYFBlgG7odPa9R1UaSQcgJWfUAx/KbJqLy5EB47qcRvctakK7pRsa3g6CmB+ApmHJL/ArJ4CxwwrPR++EqE7M=,iv:T5V7wqXr8M9CBxcnigppaqzailYXprKUXdJhUzawfXI=,tag:gIPpO8HpkwsZMcrSoUm32g==,type:str]
    version: 3.9.0
