apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: immich
type: Opaque
stringData:
    tunnel-token: ENC[AES256_GCM,data:qYq3yH18YTWy0z9gOXKykjvbdUJc3hHPcdf/iHkqTr2nxEtM6yhz/h/+w944hk6ZMLLnY4Rkt57wfEmjzIXyKkirVOwMPzszvMHe+1H/4kUwGnVeG/emgUjIEkz7C4aSqS4qLHkzbwGm1uQXxDulZuUJem2mOPr3TAeInBsyWZ2n3B4JPlXi7aLSevwNDt2o82gUuSPPUVwwLF2Z2GnH4shgz0KdxnUfsiVzVg0/LCJ/uhy+bPutag==,iv:vosh0rZ2c1xgOCz0utaXpedO7MN7OUV9ZArBDML9LXM=,tag:9sn9e2Cu08QqBXcWEL26Fw==,type:str]
    public-base-url: ENC[AES256_GCM,data:yMXNAcErsdrmKE9AJfJfuecV8ovEGMGLiLp+tztN59jF,iv:XhwJhJXm52LeTaDkIDlMdDtSchnxNtl+brq9CS+dkRI=,tag:eogPKze580M14nL6FravAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzbGdabXo5SVk3cy9qaHJz
            NGlsaEJRV0hRYzR2ZzlrOW9SYTloSk9oQnlvCmQ1OGowNElxeXlWVkFtU0lzOUd0
            azN3SEFwYnB0SG90WUhnT0FMZXE1SXMKLS0tIGdqc0dUMzFVaWk3S1R1NVdwSyt6
            L0g0MHcydVpuRFI1U0lpbTA3WjJPWlkKTpLF14lhqz5KchvfCZXJOrKpoP7DASBd
            k2sVa54m/lNgMIiX6jnl5i7IF2m+YhPaL8rhEWj2Sfe2qjK9dKx1zg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-13T17:41:06Z"
    mac: ENC[AES256_GCM,data:yR6SqevWkHk3NDnKgH8/O0cW+8esL6lEqci8nA/vnr2xKFsxGytPQL0/nnkEdXtjkCsiPkHBv2cSd7Sm35cU1WpYFBlgG7odPa9R1UaSQcgJWfUAx/KbJqLy5EB47qcRvctakK7pRsa3g6CmB+ApmHJL/ArJ4CxwwrPR++EqE7M=,iv:T5V7wqXr8M9CBxcnigppaqzailYXprKUXdJhUzawfXI=,tag:gIPpO8HpkwsZMcrSoUm32g==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
