---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-config
  namespace: immich
data:
  DB_HOSTNAME: database-rw
  DB_PORT: "5432"
  REDIS_HOSTNAME: redis
  REDIS_PORT: "6379"
  IMMICH_MACHINE_LEARNING_URL: "http://immich-machine-learning:3003"
