---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secret.yaml
  - configmap.yaml
  - pvc.yaml
  - redis.yaml
  - otel-redis-sidecar.yaml
  - otel-postgres-sidecar.yaml
  - database.yaml
  - immich-server.yaml
  - immich-machine-learning.yaml
