apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: database
  namespace: immich
spec:
#   inheritedMetadata:
#     annotations:
#       sidecar.opentelemetry.io/inject: "postgres-sidecar"
  instances: 3

  storage:
    size: 10Gi
    storageClass: openebs-crucial

  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.9-0.4.3

  postgresql:
    shared_preload_libraries:
      - "vchord.so"

  superuserSecret:
    name: immich-secrets

  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-secrets
      # TODO: Use managed extensions (pg 18)
      postInitApplicationSQL:
        # Commands based on: https://immich.app/docs/administration/postgres-standalone/#without-superuser-permission
        - CREATE EXTENSION vchord CASCADE;
        - CREATE EXTENSION earthdistance CASCADE;
