---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-photos
  namespace: immich
spec:
  storageClassName: openebs-crucial
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 350Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-model-cache
  namespace: immich
spec:
  storageClassName: openebs-crucial
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
