---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-photos
  namespace: immich
  labels:
    k8up.io/backup: "true"
    app: immich-server
spec:
  storageClassName: openebs-crucial
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 450Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-model-cache
  namespace: immich
spec:
  storageClassName: openebs-crucial
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
