apiVersion: v1
kind: Secret
metadata:
    name: immich-secrets
    namespace: immich
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:2G1Vr0+H,iv:cAwPmxFEfD7LPW7dl6vJGpKe+uGAuYNI6brQUG5nvvU=,tag:sijpWByT8D3oxXG43IuwiA==,type:str]
    password: ENC[AES256_GCM,data:jXCSVb9jgA1T,iv:LkRXrXNbIUOL3b5MExvJLuO1xrfQvz2pRawpwLr7pXM=,tag:PZ5Gb35jADiQ/1evWYHJ4Q==,type:str]
    dbname: ENC[AES256_GCM,data:03t+UpWy,iv:JOE7vmrKPCG0cWoC5Haq1p+alVaseyCa0AZ5zDEwdDs=,tag:ZX1uv0ajheBKdqk5cmBRaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNklLbWlRcndia09DZ2Vh
            ZEN5T1lRaUN6WFE5ZnpxQWZuZW1ZQk5ySmxjCmlrZXZweHFZeURZajZ6WTZKSzhw
            M0dRVXc1dG5BVCtVb0o2S2d4RjRqUWsKLS0tIHJ3SEUweFRTV28vakVTK0R1MlVN
            NFdwcE10VGZ0cVZXcmN6ZjErYjg1eDAK6cLAQZt+X2gGNhRfLW5/P9P+4TFY3GjA
            YaAc4dh0e26vVOIP8I2gBljRvFr69O+ypSNKdgK8exk6kFncGPsR0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T22:46:04Z"
    mac: ENC[AES256_GCM,data:5F5FAglhV3gGdw5rTTCVcpUHIrNfiBwN7B+vg8nrCQ7NOFJkOmguRlfxLdGuYUppWoQSofBEoIqzmzpjuDZKTHN+X5oN7EhcsOZNhridpbXQtBvWscWU240JcAjs6L9sutEY1unL3X16j4iyKNThh7pZbUAeEaiRkNp7lsO5wig=,iv:z/nEcJthDuVscO/81344c+mTRzv83uk5qudL+5JuVj4=,tag:Xz2ubSVPTgXVxM+4cWA4Qg==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
