apiVersion: v1
kind: Secret
metadata:
    labels:
        app: ambient-api-server
        component: api
    name: ambient-api-server
    namespace: ambient-code
stringData:
    sentry.key: ""
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZTJ0SzFDdE14SndZMWNk
            dS9ZMk9LZXU0MHhqRjE4SllLZFJ6NURma0JjCk5IdkM0Qm9RV1VLU3JNdUdxSjZj
            ZXhFMDFJWHY5SFpKSFBwVG15VGtCS0UKLS0tIFR6cU42cG1SaFFBbXRKcWt0aDRh
            amNDcEVURlowM1dvN3FPSjRMRnR3TUEKLy2X66+s/+Y9WaCTQBm6lQ81AF4JRSVQ
            RN9b73sWGcm5tFHWs7/2PHLXO5HcTzMgHYZzhegVSlW5RHctpFaiiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T23:54:56Z"
    mac: ENC[AES256_GCM,data:AoCmU01Tq9PwJXn4UiId12Y5gqfqHN6sv8R/fKpExDf81SExcam7VBBCL6Gcmo36QPQoqwvPkNs5VQeqshYBLXND5MwraobIZfHA5Vqd7LHOaQlxUBMKytbc5r+hQDikLcoT3RGC+2qt7lS+flvg96XYPG71S4eGglbQvBFrcGI=,iv:EnppTvqZzrwIvJrglK7itYi1SfDaZ1d42c2vH1UmipM=,tag:Enx7udEOAJD08sj7u3mTjw==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    labels:
        app: ambient-api-server
        component: database
    name: ambient-api-server-db
    namespace: ambient-code
stringData:
    db.host: ENC[AES256_GCM,data:kQHpAkcgLYWFim/ADEDHRbmp4l21,iv:aaiaEnt+aSsOfJq9fmOdT7YPfweJ0aaTpeJc5dHU3Vs=,tag:mw4a/HPXqS7TYrSuHMU0vg==,type:str]
    db.name: ENC[AES256_GCM,data:BEbI+2ju/RmQVxEB1d0d0onj,iv:Zb6kcqIV29v4OTILbW2ihPhYCWo5+P4OZ3D+DAT+4E8=,tag:TW21PvrUKC7MiFQcxqshzA==,type:str]
    db.password: ENC[AES256_GCM,data:5E8lBd74K2odUg+L0VM9SA==,iv:qK3L64VFg/upK4IBcayth4yr3b0cFxLKh393eRqkxxA=,tag:rFUr395x/FSB2rX9no7izA==,type:str]
    db.port: ENC[AES256_GCM,data:IbL1vQ==,iv:aQSN6Q8bsTRQcgG3nIDCasBMBFZbiJGy4cufvRltNuU=,tag:WlOZ3mNlKQNp/jQkiYeCXw==,type:str]
    db.user: ENC[AES256_GCM,data:cBgdk23V1A==,iv:O7r0ipnb4I+0ReCJMQQ6bdgzksBoxYPITcBgH47P3SA=,tag:T3it65yHyaO70alRD0uxzQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZTJ0SzFDdE14SndZMWNk
            dS9ZMk9LZXU0MHhqRjE4SllLZFJ6NURma0JjCk5IdkM0Qm9RV1VLU3JNdUdxSjZj
            ZXhFMDFJWHY5SFpKSFBwVG15VGtCS0UKLS0tIFR6cU42cG1SaFFBbXRKcWt0aDRh
            amNDcEVURlowM1dvN3FPSjRMRnR3TUEKLy2X66+s/+Y9WaCTQBm6lQ81AF4JRSVQ
            RN9b73sWGcm5tFHWs7/2PHLXO5HcTzMgHYZzhegVSlW5RHctpFaiiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T23:54:56Z"
    mac: ENC[AES256_GCM,data:AoCmU01Tq9PwJXn4UiId12Y5gqfqHN6sv8R/fKpExDf81SExcam7VBBCL6Gcmo36QPQoqwvPkNs5VQeqshYBLXND5MwraobIZfHA5Vqd7LHOaQlxUBMKytbc5r+hQDikLcoT3RGC+2qt7lS+flvg96XYPG71S4eGglbQvBFrcGI=,iv:EnppTvqZzrwIvJrglK7itYi1SfDaZ1d42c2vH1UmipM=,tag:Enx7udEOAJD08sj7u3mTjw==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    labels:
        app: vteam-git
    name: git-credentials
    namespace: ambient-code
stringData:
    GIT_URL: ENC[AES256_GCM,data:24NIp+Y4I1auG8HWbXLoOlLkGBIgyg==,iv:yAPWBPcW9DioajHSf3TWTW4mD1ZYdl6jVm5vaDrjSPI=,tag:kRQAOA21dEsT/Vl39Vt6Dg==,type:str]
    GIT_TOKEN: ENC[AES256_GCM,data:cKcY1z4yf/oeXhrmB5WzrSpOgPywEsuOPtXXcD2Szm3LxhAk+n4Nsw==,iv:9fE5t0eN+WDbjXWnhLOq2LfL/o48JqfT2WzULOt3iI0=,tag:OiKKRjl074FYebWbacwbaA==,type:str]
    GIT_USERNAME: ""
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZTJ0SzFDdE14SndZMWNk
            dS9ZMk9LZXU0MHhqRjE4SllLZFJ6NURma0JjCk5IdkM0Qm9RV1VLU3JNdUdxSjZj
            ZXhFMDFJWHY5SFpKSFBwVG15VGtCS0UKLS0tIFR6cU42cG1SaFFBbXRKcWt0aDRh
            amNDcEVURlowM1dvN3FPSjRMRnR3TUEKLy2X66+s/+Y9WaCTQBm6lQ81AF4JRSVQ
            RN9b73sWGcm5tFHWs7/2PHLXO5HcTzMgHYZzhegVSlW5RHctpFaiiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T23:54:56Z"
    mac: ENC[AES256_GCM,data:AoCmU01Tq9PwJXn4UiId12Y5gqfqHN6sv8R/fKpExDf81SExcam7VBBCL6Gcmo36QPQoqwvPkNs5VQeqshYBLXND5MwraobIZfHA5Vqd7LHOaQlxUBMKytbc5r+hQDikLcoT3RGC+2qt7lS+flvg96XYPG71S4eGglbQvBFrcGI=,iv:EnppTvqZzrwIvJrglK7itYi1SfDaZ1d42c2vH1UmipM=,tag:Enx7udEOAJD08sj7u3mTjw==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: minio-credentials
    namespace: ambient-code
stringData:
    access-key: ENC[AES256_GCM,data:SKdN6LEJjskl4Q==,iv:aKSawb0q/F8bbFoIdxZv5gq0h0x6oxEkXY1Gokmiuus=,tag:jrZbVZAK3QsxwI2jJLAt2g==,type:str]
    root-password: ENC[AES256_GCM,data:vXTkrs60/ROkVlX6sw==,iv:9h/SKfNx0ntfC7K6Fy0pLzY2C+51ZCcEtGU+u5N+ey4=,tag:F8GbhGwOhXycF9GRj/Y+ZQ==,type:str]
    root-user: ENC[AES256_GCM,data:Gipw5AtcyQUaJA==,iv:AesmBWzJobgOkOd44ROP7h5+UedVny5sFw8Om/VVpGQ=,tag:wp+fpqYjgpz4LUvt3rr7Aw==,type:str]
    secret-key: ENC[AES256_GCM,data:cmwstwKzZt8VhyYCyg==,iv:WH9AS10b/MVwo6V3FhCQLTn5M8lYtP0uzfp+aSLqMwc=,tag:JZRww2//G0iLPSqPuAbu0g==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZTJ0SzFDdE14SndZMWNk
            dS9ZMk9LZXU0MHhqRjE4SllLZFJ6NURma0JjCk5IdkM0Qm9RV1VLU3JNdUdxSjZj
            ZXhFMDFJWHY5SFpKSFBwVG15VGtCS0UKLS0tIFR6cU42cG1SaFFBbXRKcWt0aDRh
            amNDcEVURlowM1dvN3FPSjRMRnR3TUEKLy2X66+s/+Y9WaCTQBm6lQ81AF4JRSVQ
            RN9b73sWGcm5tFHWs7/2PHLXO5HcTzMgHYZzhegVSlW5RHctpFaiiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T23:54:56Z"
    mac: ENC[AES256_GCM,data:AoCmU01Tq9PwJXn4UiId12Y5gqfqHN6sv8R/fKpExDf81SExcam7VBBCL6Gcmo36QPQoqwvPkNs5VQeqshYBLXND5MwraobIZfHA5Vqd7LHOaQlxUBMKytbc5r+hQDikLcoT3RGC+2qt7lS+flvg96XYPG71S4eGglbQvBFrcGI=,iv:EnppTvqZzrwIvJrglK7itYi1SfDaZ1d42c2vH1UmipM=,tag:Enx7udEOAJD08sj7u3mTjw==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    labels:
        app: mlflow
        app.kubernetes.io/name: mlflow
    name: mlflow-db-credentials
    namespace: ambient-code
stringData:
    uri: ENC[AES256_GCM,data:Vty9CoDK32HTqBNIIg1mdK6rYd/T0qx1+gjGzRRF/v3X/lw/ZWhJcldfFHDdFnkOlhNeYVQdvuY0dSI6J4Vw5qGoqCkwRlTQHaHDoodjU20DsEu1hffNcLcZTijg7D25HwPij1XDjA==,iv:oEFJwUcZQ96HK974+HmKWYNKbS7UQjhqk+kBuY5zRv4=,tag:j/9XjPo9apwvUQzpFgVmFA==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZTJ0SzFDdE14SndZMWNk
            dS9ZMk9LZXU0MHhqRjE4SllLZFJ6NURma0JjCk5IdkM0Qm9RV1VLU3JNdUdxSjZj
            ZXhFMDFJWHY5SFpKSFBwVG15VGtCS0UKLS0tIFR6cU42cG1SaFFBbXRKcWt0aDRh
            amNDcEVURlowM1dvN3FPSjRMRnR3TUEKLy2X66+s/+Y9WaCTQBm6lQ81AF4JRSVQ
            RN9b73sWGcm5tFHWs7/2PHLXO5HcTzMgHYZzhegVSlW5RHctpFaiiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T23:54:56Z"
    mac: ENC[AES256_GCM,data:AoCmU01Tq9PwJXn4UiId12Y5gqfqHN6sv8R/fKpExDf81SExcam7VBBCL6Gcmo36QPQoqwvPkNs5VQeqshYBLXND5MwraobIZfHA5Vqd7LHOaQlxUBMKytbc5r+hQDikLcoT3RGC+2qt7lS+flvg96XYPG71S4eGglbQvBFrcGI=,iv:EnppTvqZzrwIvJrglK7itYi1SfDaZ1d42c2vH1UmipM=,tag:Enx7udEOAJD08sj7u3mTjw==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    labels:
        app: postgresql
        app.kubernetes.io/name: postgresql
    name: postgresql-credentials
    namespace: ambient-code
stringData:
    db.host: ENC[AES256_GCM,data:Wt+AqCAcnh+KVA==,iv:gpI67Vz0A98jVrAgFv3swnVKstbYndz5EXy9ao9Vq78=,tag:bydmWoGeTpmq+tBuP1jX4A==,type:str]
    db.name: ENC[AES256_GCM,data:iJ62HJ6ln2U=,iv:VTZBtxxCoQFkp9nGG5q2/UMSztGLzWoHBfAGIBN0i28=,tag:u89GPdr1in76eXKFNcYfpg==,type:str]
    db.password: ENC[AES256_GCM,data:uOHjhNB39XhazAY=,iv:cs5pzynAwiqs8+VwadwKWGCPKymY/S+6VcCiSxxnZk4=,tag:Dc8n69HHbCXglcbZHQO5cw==,type:str]
    db.port: ENC[AES256_GCM,data:44PnrA==,iv:Lt6KNORk26TEvbXI+9AJM267bxDXFaV0v621JARy7Kk=,tag:+/AMXA3TRG3QS6rDLHZvLQ==,type:str]
    db.user: ENC[AES256_GCM,data:AQHVcz4Mamk=,iv:fzIcBwqRUBSlozRP6Fji8pYTDqJZWZ/UyHO95JnK4os=,tag:WrotfiAwm5ZJnVN+FjpUyg==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZTJ0SzFDdE14SndZMWNk
            dS9ZMk9LZXU0MHhqRjE4SllLZFJ6NURma0JjCk5IdkM0Qm9RV1VLU3JNdUdxSjZj
            ZXhFMDFJWHY5SFpKSFBwVG15VGtCS0UKLS0tIFR6cU42cG1SaFFBbXRKcWt0aDRh
            amNDcEVURlowM1dvN3FPSjRMRnR3TUEKLy2X66+s/+Y9WaCTQBm6lQ81AF4JRSVQ
            RN9b73sWGcm5tFHWs7/2PHLXO5HcTzMgHYZzhegVSlW5RHctpFaiiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T23:54:56Z"
    mac: ENC[AES256_GCM,data:AoCmU01Tq9PwJXn4UiId12Y5gqfqHN6sv8R/fKpExDf81SExcam7VBBCL6Gcmo36QPQoqwvPkNs5VQeqshYBLXND5MwraobIZfHA5Vqd7LHOaQlxUBMKytbc5r+hQDikLcoT3RGC+2qt7lS+flvg96XYPG71S4eGglbQvBFrcGI=,iv:EnppTvqZzrwIvJrglK7itYi1SfDaZ1d42c2vH1UmipM=,tag:Enx7udEOAJD08sj7u3mTjw==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    annotations:
        kubernetes.io/service-account.name: test-user
    labels:
        app: vteam-e2e
        component: test-user
    name: test-user-token
    namespace: ambient-code
type: kubernetes.io/service-account-token
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZTJ0SzFDdE14SndZMWNk
            dS9ZMk9LZXU0MHhqRjE4SllLZFJ6NURma0JjCk5IdkM0Qm9RV1VLU3JNdUdxSjZj
            ZXhFMDFJWHY5SFpKSFBwVG15VGtCS0UKLS0tIFR6cU42cG1SaFFBbXRKcWt0aDRh
            amNDcEVURlowM1dvN3FPSjRMRnR3TUEKLy2X66+s/+Y9WaCTQBm6lQ81AF4JRSVQ
            RN9b73sWGcm5tFHWs7/2PHLXO5HcTzMgHYZzhegVSlW5RHctpFaiiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T23:54:56Z"
    mac: ENC[AES256_GCM,data:AoCmU01Tq9PwJXn4UiId12Y5gqfqHN6sv8R/fKpExDf81SExcam7VBBCL6Gcmo36QPQoqwvPkNs5VQeqshYBLXND5MwraobIZfHA5Vqd7LHOaQlxUBMKytbc5r+hQDikLcoT3RGC+2qt7lS+flvg96XYPG71S4eGglbQvBFrcGI=,iv:EnppTvqZzrwIvJrglK7itYi1SfDaZ1d42c2vH1UmipM=,tag:Enx7udEOAJD08sj7u3mTjw==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    labels:
        app: unleash
        app.kubernetes.io/name: unleash
    name: unleash-credentials
    namespace: ambient-code
stringData:
    admin-api-token: ENC[AES256_GCM,data:Kt7TDiOoyna4X1fD6k4Oa7cTniDxaho=,iv:0ZhgEAPX8MUVugl3tONZqsl5GYJgx7CP9KyfysanRuw=,tag:sdOX8u5cwAWWjIH3Ykaq8w==,type:str]
    client-api-token: ENC[AES256_GCM,data:STV2bulZ+4OvjpnhK+2PtwrRwmnlzboqA1xxk4pVEc/DcU93R2EfYg==,iv:tTPPjFzOmQJPceP2J1/kB0S7tcUiYn6TuTtIQlUbg0o=,tag:DIAOdrcyG2ayoD5zBHWwNg==,type:str]
    database-ssl: ENC[AES256_GCM,data:22qFEyo=,iv:DAtgwYKl79iUYrR7G7AZev8bAvEF7KbcZFWqQhLUnP0=,tag:IKFi8u9CFUrKzKygIx+e1g==,type:str]
    database-url: ENC[AES256_GCM,data:gifPNrSVjOO0naBzBqctFPqb5cG4xd0J70D8evAzK25rn2cPQgqLsDLRHU7wX83wP+iQXNlagA==,iv:luQ5bZtfVIirUfBFeSZ0nuTB/gLUPVjX0kwHePYMsxg=,tag:c3yLh2MYGX4twocBlGyVSg==,type:str]
    default-admin-password: ENC[AES256_GCM,data:q8M/lKAbg8maBsrk8nPkZ5IjCQk=,iv:w1WGHr4RX2k8J8QZalM3/2gJAvStNnNhcFFTLJU0HGs=,tag:IYb9YR6JomOWeUEeIV9pAA==,type:str]
    frontend-api-token: ENC[AES256_GCM,data:ZUaMGD4ZyE/Hx/Ph5wjTR08Xrcptn+XBoC7Za2co/AbFdv1syJVCstms,iv:QoLZuOEixUaxPNyuhwYbOPb1OyqTqGa4dvF8rjLC/uU=,tag:zhyEZp+TNOL97rb7DMWkBg==,type:str]
    unleash-admin-url: ENC[AES256_GCM,data:L0ovNQrKav1+YzIKixNoL40tgw==,iv:wal5fd99hQEEP3JQrq+ztaz8xJyI8fvUPKLDyrMjU1o=,tag:KuUDE1MJ5PIBvXBvfbK8EA==,type:str]
    unleash-environment: ENC[AES256_GCM,data:zgt4qJZpcOpoXmg=,iv:TpKxRfFDovgUe0c4CeHxs05OixLKsJvUIh2Tw1uLxio=,tag:LoW5PbUAhpBvoUPBq/Svag==,type:str]
    unleash-project: ENC[AES256_GCM,data:N9kgNqnmgA==,iv:KUd5mnnOuVSUkmNd7GmviHwlK6XNbTuvzdnym0HvUOI=,tag:mQwjht9Hk40e4rYWLPiSmA==,type:str]
    unleash-url: ENC[AES256_GCM,data:eF9YwZQ7fgUmY3ygQF5S9iZn/6Lpx98=,iv:8ddFsvcuQP20grh4CJ3RSPIOO28kCCdItTCuYmF2ykI=,tag:11aXJew/nKVJK02KmVuVNQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZTJ0SzFDdE14SndZMWNk
            dS9ZMk9LZXU0MHhqRjE4SllLZFJ6NURma0JjCk5IdkM0Qm9RV1VLU3JNdUdxSjZj
            ZXhFMDFJWHY5SFpKSFBwVG15VGtCS0UKLS0tIFR6cU42cG1SaFFBbXRKcWt0aDRh
            amNDcEVURlowM1dvN3FPSjRMRnR3TUEKLy2X66+s/+Y9WaCTQBm6lQ81AF4JRSVQ
            RN9b73sWGcm5tFHWs7/2PHLXO5HcTzMgHYZzhegVSlW5RHctpFaiiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T23:54:56Z"
    mac: ENC[AES256_GCM,data:AoCmU01Tq9PwJXn4UiId12Y5gqfqHN6sv8R/fKpExDf81SExcam7VBBCL6Gcmo36QPQoqwvPkNs5VQeqshYBLXND5MwraobIZfHA5Vqd7LHOaQlxUBMKytbc5r+hQDikLcoT3RGC+2qt7lS+flvg96XYPG71S4eGglbQvBFrcGI=,iv:EnppTvqZzrwIvJrglK7itYi1SfDaZ1d42c2vH1UmipM=,tag:Enx7udEOAJD08sj7u3mTjw==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    labels:
        app: claude-code
        component: llm
    name: claude-code-config
    namespace: ambient-code
stringData:
    #ENC[AES256_GCM,data:yCEv2+Gp6IMcS1TCif/HXzBEZFxtA28ilqZUFQDPuztKsm6r8yvLu6eByk4lwiwOiww=,iv:rijHLNzYM5WCX9N7c8sJ90sVsvckPGkC3hqYa3EcYyA=,tag:tdZfY2VKLVmcaQMwyx2OVg==,type:comment]
    ANTHROPIC_AUTH_TOKEN: ENC[AES256_GCM,data:ghnQPt5N,iv:Gt5U4VkZuAAZ9HiATh4Rbi78qEhzGWzLV6B5RKtgbWc=,tag:lRqRkSdKeUxz4ldlcoQujA==,type:str]
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:G7Up7fo6W/iT/JcwTJrpVhDIVeIx2w==,iv:kPaHsxCxNgN+FMGWpZP2cl4M1u5bGZtccYnlVhAuhEM=,tag:9gZJ4bqoRrfj++UhU9P4UQ==,type:str]
    ANTHROPIC_BASE_URL: ENC[AES256_GCM,data:KKsxcCXmq3gcKODApi+rNbKqRwLlun7WTkiw678h5jz99I+1jtqihoY=,iv:C9Sg1pTio6Lde+qNQUcKnxbCxrvSRgTxkPYOmvJmmZQ=,tag:sc+66HGqjqs3RJc+5OPLdw==,type:str]
    #ENC[AES256_GCM,data:MZ7ZxHClxp0mD802c3vJDVXro08nv+n8kXme+LTCkV8=,iv:94+0RFUIgeWRaSyJEDwjiVzG+qvdqxwbGhZz/m2Fjss=,tag:Mt4wGPIYHOTOioh7XvzhDg==,type:comment]
    ANTHROPIC_MODEL: ENC[AES256_GCM,data:3KRnQy16es8UQwyPXR0cpewj,iv:WpHRFdGmmgIPhzMkR2YQLk1Svhsqz3EwopczBTYZVps=,tag:jm+/t8DBT0M+hDME/Aa1oA==,type:str]
    ANTHROPIC_CUSTOM_MODEL_OPTION: ENC[AES256_GCM,data:wd0SlLmaYQlxrMVpvLYvzWq4,iv:7xoWzlOD0/OCvz40To58DXW0dAsGY0nPL+EHxk25wu0=,tag:RTjVbGMgodxy5uVsK/fcxg==,type:str]
    ANTHROPIC_CUSTOM_MODEL_OPTION_NAME: ENC[AES256_GCM,data:zrp3ZV5HmGxXcgs1AabnsiA=,iv:nVuMlZEq0W+Nb4oJH90aJZ4MPrpV/fqfshQmhcjPmoE=,tag:iVeFyLbqu+4bcQQjSq2zNg==,type:str]
    ANTHROPIC_CUSTOM_MODEL_OPTION_DESCRIPTION: ENC[AES256_GCM,data:yfDPDOXqHPm0wVrtihCHc+gmffBXszFEd6qxEzvGFuh3qUxW5QWzPepgXpOkcCC0e/4M1pDUgAk1,iv:JXaV924oalSneevRM/g6LwaiOLSsvHEGME+DRkCBrsE=,tag:gFgv0LtpK11uvdNOxWhsrA==,type:str]
    #ENC[AES256_GCM,data:zYQLMMl3VHCmuaOrrvygkgLTMeKCr8q4,iv:yxN8gEW/3Rp4N+QQ8A+jpCcujTSF0D0JKXHZldFKpik=,tag:35x0g4dBIgKQP4V6YPr+Nw==,type:comment]
    CLAUDE_CODE_ENABLE_TELEMETRY: ENC[AES256_GCM,data:DQ==,iv:mQiVCjny3RpxIrk/FX+fn6Sns5dAIp6xLu//TcLTvcw=,tag:eUPtyLs1p9kcCGPVeIQCtg==,type:str]
    OTEL_METRICS_EXPORTER: ENC[AES256_GCM,data:jtVdFg==,iv:vSS7wlqGGzeNxbNCWw5bh2aupWrF7cXvOOKU9zxpZes=,tag:QG6zUMGQrgtMi1UgStd5Vw==,type:str]
    OTEL_LOGS_EXPORTER: ENC[AES256_GCM,data:Qp6Tyg==,iv:zaM5CzqIOo0GQPBvSJARh7AVZs7T0mBYLpIfqHSMz2g=,tag:XY+UzPTrVWJq8iLMCq0q1Q==,type:str]
    OTEL_EXPORTER_OTLP_PROTOCOL: ENC[AES256_GCM,data:81v9Ii5bn/q5Rg7hKA==,iv:feSrGVfBNVglkBZmiDFpzN03x3iP0nRmzar5mdbCZt0=,tag:iwJGnEhn01XJbDZsdKlRRw==,type:str]
    OTEL_EXPORTER_OTLP_ENDPOINT: ENC[AES256_GCM,data:XQk6OzINM8kvaUzz2DwJS8EYuPrT5AsNj5vhQjuBfnhX2MaFofDGaUuckM5W1nxq/sZ6,iv:OFat/onhphocTDtecig3XnSwegChE/E055HiVxCvcgA=,tag:5DkjbMbAXPyL2b70GmDccg==,type:str]
    OTEL_LOG_TOOL_DETAILS: ENC[AES256_GCM,data:+A==,iv:i01lctCVLwMA4dcL4SoJJhR3RsHN60jWVB0B5Wlm66c=,tag:mRUBvSKOEYmBBOl63ZkYqA==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZTJ0SzFDdE14SndZMWNk
            dS9ZMk9LZXU0MHhqRjE4SllLZFJ6NURma0JjCk5IdkM0Qm9RV1VLU3JNdUdxSjZj
            ZXhFMDFJWHY5SFpKSFBwVG15VGtCS0UKLS0tIFR6cU42cG1SaFFBbXRKcWt0aDRh
            amNDcEVURlowM1dvN3FPSjRMRnR3TUEKLy2X66+s/+Y9WaCTQBm6lQ81AF4JRSVQ
            RN9b73sWGcm5tFHWs7/2PHLXO5HcTzMgHYZzhegVSlW5RHctpFaiiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T23:54:56Z"
    mac: ENC[AES256_GCM,data:AoCmU01Tq9PwJXn4UiId12Y5gqfqHN6sv8R/fKpExDf81SExcam7VBBCL6Gcmo36QPQoqwvPkNs5VQeqshYBLXND5MwraobIZfHA5Vqd7LHOaQlxUBMKytbc5r+hQDikLcoT3RGC+2qt7lS+flvg96XYPG71S4eGglbQvBFrcGI=,iv:EnppTvqZzrwIvJrglK7itYi1SfDaZ1d42c2vH1UmipM=,tag:Enx7udEOAJD08sj7u3mTjw==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
