apiVersion: v1
kind: ConfigMap
metadata:
  name: karakeep-configuration
  namespace: bookmarks
data:
  NEXTAUTH_URL: https://bookmarks.klimlive.de
  KARAKEEP_VERSION: 0.33.1
  MEILI_ADDR: http://meilisearch:7700
  BROWSER_WEB_URL: http://chrome:9222
  DATA_DIR: /data
  OAUTH_WELLKNOWN_URL: https://auth.klimlive.de/application/o/bookmarks/.well-known/openid-configuration
  OAUTH_PROVIDER_NAME: Authentik
  OAUTH_SCOPE: "openid email profile"
  DISABLE_PASSWORD_AUTH: "true"
  OAUTH_AUTO_REDIRECT: "true"
  OLLAMA_BASE_URL: "http://ollama.llm:11434"
  INFERENCE_TEXT_MODEL: "deepseek-v4-flash:cloud"
  INFERENCE_IMAGE_MODEL: "gemma4:31b-cloud"
