apiVersion: ENC[AES256_GCM,data:d0E=,iv:bVzl/WoSVEKjsCimdck96X0fdnqwOBtG+KKvMQZyJbk=,tag:nOiZ3lqSxeD9Oh2yQlWLkw==,type:str]
kind: ENC[AES256_GCM,data:TfbTIGYZ,iv:Hna29mMES1MKRI1b+A/xopII6aEi/ltIEw6FKeiLF04=,tag:1Oyl6qw2fns2lGFT5nRJUg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:vbm9MfJerufuzCSRQi9piw==,iv:ws2sRjOMoT3/XbU5TpoWSklFzEPVnlAFcZnZMoOSXlE=,tag:eCllPlhCXNO3binHq7tJVA==,type:str]
    namespace: ENC[AES256_GCM,data:HGF8Q+w2wUKM,iv:vb7k3h/iyOzxoAutljP7pjySP3LqE1V1Edwy61bxqdE=,tag:ZxW1H1VuL/2VNLhUc2be9A==,type:str]
type: ENC[AES256_GCM,data:0xM6d0A1,iv:yEvDEy4g8hHiCbHny6/1qoQUe7rBYRksB0QVtFc1lMI=,tag:anbVCA1mai8Qkz3KtW+Yqw==,type:str]
stringData:
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:veOpdtNsNQAZvBsaO+tEfGfp5In59LsHmEQQlr8aJh9zU3X/G8ayhqGQm+84C0lG,iv:ZdVVrR++sX8php7dE7AoXg4Xj6gYmgSWNfB1w98oqEw=,tag:gtKOcPdBRa1KJtt1kZ5/nQ==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:tP5byXwuDrapACxx4AJQ6gGFKcb3cO6Px/LpLVt5d6rXnCMXAAM1yOBA5LjcPQ==,iv:7KvMsael6uKypma/IYqmHCm9XGkW+toGRs5UHsYpOys=,tag:Fk8kXbhrY/n/duhH5yw77g==,type:str]
    NEXT_PUBLIC_SECRET: ENC[AES256_GCM,data:K8Bal73UxRgNbAILHBuDI+wchOPg7hSlBKok6XBTEBg+Z5tCiZTyFSHkm25uNXwx,iv:U+xFSE263oThFUreEAq/KLFMnioFeXG6fYfA+JG6svA=,tag:EBKIbTt8bYN73BtMNKCk5w==,type:str]
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:ow9LB+4gX5nkoyo934Qsfd8MXMV+T7V+UnXHi6BwIdj+fzNJ1addjA==,iv:vBa3RlGqMz8hi8/gxf/WE89VLeO8PKFVlT25kFcKS6U=,tag:Jl5JaC+aosoVnbNIzAbyyQ==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:HNtM/iOpjhqa0E8WlHwvJohkC5NWjkvyRlDSVw1y84T6hYaeUoTGUFNQzvVtjlCAyD97/iwEtLuvrmmf5DUjKF2u43S3EeOycqLBmS1VrjMuBbx91BaU5LaDXxa9/O9AQcJb6P6or6QrIfxNiuqI+kincrtIRazTrsBFKWnQacM=,iv:e+6ZYQ+lRpuKfw/R7WaBCBGDotljMi+1Gw2h4MIS2/g=,tag:4P2dKQUNgcIUg635REOYdg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6TDFqbXgwV2FuMmpvd0VS
            YlU0YThqWnRjM01TemIrR3BOdEsvamluUFFzCjRwZmtrcWY4d1BUMTZFVmhzWFRF
            RVQweTVLalNIN2ZHWGFVKzZsVER5TEEKLS0tIDdSNWI4Z0R6a21QMzcrUHY1MFdH
            Zm51WTA5OEFCak90NzRwTWtLTHFUNWsK5uMCrQyFSVmnYyaLV4qic8UjV8MsyCFt
            iFonWSviErZhNEY1c0+Ar9ghVltjo/AncMZ6vxhCA2iQGX9gjXmKqQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IFJTSlJydyBBK3NFd0xN
            MWlqSk9JbW1iY2QrUTE4WGpDbmJudVA5MTFVUTV4S0NSUncycwpxQi90S1lueURV
            cDRpTkRpcW9ZSFZ4cGRhejdPaVVuOEhPSTVidGtjQTJVCi0tLSAwMVIwaWo4Lyt2
            QUxGUFBJVjIvV0pBZXhBWHljcmQrYW52bHVnWHFKMTNRCkJ9DZ9cWFTwM2cu06vC
            JebOWHUqfi4n7eTQPXQxJqdXk5iOo/ng4mIC+mDR4aQ3KbwJ2lsnWZ1Egt9ezV6l
            hws=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qgn7ll64pzy4wd64h85xxq386cexa98676zw4raej9rvxl822p782xrjn5z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDY0dUwvQSBBL2pmenMx
            d3lGS0tmWUFoUnNIY3RPM2plbDNjS25GSVlWV1JtU3phM3JYcApLcVNkMlArTlVF
            aldLMitBWG8xekN3dlZ0M0VGVGk4R0lvZ0xqUHNBemlFCi0tLSAxckxDM0JiQ1ox
            TjlhQ3hqS0V0TG5JR3RWdWhoMVgvRlYyalJxS1JtWllBChxgye+qkybYoPnEVI9M
            KzszhOnwDIge5qX8Azx+UXF/OK+fP+Jn3Iw3WmNaqWtLuMLagNNF02jFx79xiDEo
            Nx4=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtvpgtvl83qxn5kferysjnzrt0zs2svfygeuvqznlupmvtepcwv37v7pace
    lastmodified: "2026-09-02T09:55:22Z"
    mac: ENC[AES256_GCM,data:IrTWJUG8tOAnJsRN6HeXyjU1PkWV5TEBYQibqqReHlefWO8QTmoK8i/gnieKxqOFkMCUoFGcTdZrKWaEiV7136fKjnhR3pPvFIg7FijqU2mV6zZaRrmBai9UTnLIZjtIk75mHyPGnmb2hElPSYJlEetsWJtTpGEQitnmT76d4cg=,iv:a0e58M24yP6CtTm233eS5iQQS5xOKlhxh7fe5Z+fAso=,tag:fMojaIrZkIiWraWOTAYzTg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
