apiVersion: v1
kind: Secret
metadata:
    name: karakeep-secrets
    namespace: bookmarks
type: Opaque
stringData:
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:1V3veXfTQuudWeerARzTyZMxFTgH2mGpdLLt88tD/mW0AVLocZbRZ1a+bCqDzgRk,iv:gLSVyA+DPJk+4y7U2BLlGz1+7jS5fCzKfLXoHDbD5rM=,tag:5eMiigIX8cCXgFA0io5tfA==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:vet98hTCbqtrxZOX8QcsfrGgAlHuvqXIRyujDryOsRzLs5pRhCo/LO/IrjgzGA==,iv:3+Q93c2UqAhmIvlmO7SNsSsaXiYNUKJlIY+7vQ9P0Gk=,tag:1jxS0X339Li//ZiThxwEaQ==,type:str]
    NEXT_PUBLIC_SECRET: ENC[AES256_GCM,data:SimOFlY99GxWp3RVpeze8qVEQfcCd8a85M/LQ2MfO1hlMZRJ3InC5fBDGOXfQtsI,iv:oB+UGdFIZ1/7JntC9M3qX3n0nhrK34mJKnWlh8fqMmw=,tag:GmsNJwIVITvFxurwP1ICsg==,type:str]
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:ZkPe4cIVssl1XXoF8VtWqv4IldkHufEa9fQU3jmKmA1YzJLPDZfcKw==,iv:8Rn+rySmYuu/ZNeUbL5A1FZy+33Y4iUnj15/7ev4CMw=,tag:uHtbTEVYoxuSTTw6jSgU+g==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:1PKUI19lEj86q8J8MTAfBdkxOOo3O1gpZwtlOh8yTcBcaYD0hJNUglKoO/vioQZ417115iNLBWpTXAy98gluu5n+uUaGJ1ZNG+8OwgtxAeY5svKqBjWPdlqV3lsADmFb656DRPqpUXEb5LVqOAP2OYAC81ox+5OCi86QLrPdUyM=,iv:OXjoMPE3jFxkHj/Uv9pi3AsUA21SLZfTZ/oQT/n2vlg=,tag:Gg68zw9Aprt9cEthpsg7Fg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VVllWHIzYnE2QkhKNXZa
            cmtxdmN6RDU0NlBub1FIclFwMXpuWHVUakRBCjhFdEw3K1ppazE1RmVDNVZ3UFAx
            TGlDZkZPZkJwWW9WWEJrUlJVbVVkTTgKLS0tIFJEaG9VZjU0WWRRcTArZTNaZ3Vu
            aEY1ZEdES0xiMkIrckR1MTdXWmRLVUEKDSCLT9iBQoCyBKgdUddAR0clbnvhiRXj
            ErrFLJKiL6S6fiPrYgmQmH/Gscmg9w1E7GAlelmAev95xChWUNVVDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-07T23:58:22Z"
    mac: ENC[AES256_GCM,data:e58eXicwCyo8rO5/CByavNonDbLNa8eSLfZARAdPsTlSsjuGGRNZlHzDWZIolcUyZuCF0S12tb8crXdPjEPe5feQP86LiNCimJLtdSu/BJ6nH+w+tM+AB8b9uN0bC39PjlWvK4EZStkN/m7RmegxCxY1EydxG9Z97bnMAUa5SNs=,iv:YgYOo+w8WV0KdmtGxb0O8op8cJ29N+LCPx18iVerCiU=,tag:9qOXLKPMVyKxYnCd5DygQA==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
