---
apiVersion: v1
kind: ConfigMap
metadata:
  name: docs-config
  namespace: docs
data:
  DJANGO_ALLOWED_HOSTS: "docs.klimlive.de"
  DJANGO_CSRF_TRUSTED_ORIGINS: "https://docs.klimlive.de"
  DJANGO_CONFIGURATION: "Production"
  DB_HOST: "database-rw"
  DB_PORT: "5432"
  DB_NAME: "docs"
  REDIS_URL: "redis://redis:6379/0"
  CELERY_BROKER_URL: "redis://redis:6379/1"

  AWS_S3_ENDPOINT_URL: "http://seaweedfs:8333"
  AWS_STORAGE_BUCKET_NAME: "docs-media"
  AWS_S3_REGION_NAME: "us-east-1"

  COLLABORATION_API_URL: "http://y-provider:4444"
  COLLABORATION_WS_URL: "wss://docs.klimlive.de/collaboration/ws/"

  OIDC_OP_JWKS_ENDPOINT: "https://auth.klimlive.de/application/o/docs/jwks/"
  OIDC_OP_AUTHORIZATION_ENDPOINT: "https://auth.klimlive.de/application/o/authorize/"
  OIDC_OP_TOKEN_ENDPOINT: "https://auth.klimlive.de/application/o/token/"
  OIDC_OP_USER_ENDPOINT: "https://auth.klimlive.de/application/o/userinfo/"
  OIDC_OP_LOGOUT_ENDPOINT: "https://auth.klimlive.de/application/o/docs/end-session/"
  OIDC_RP_SIGN_ALGO: "RS256"
  OIDC_RP_SCOPES: "openid email profile"
  LOGIN_REDIRECT_URL: "https://docs.klimlive.de/"
  LOGOUT_REDIRECT_URL: "https://docs.klimlive.de/"

  TZ: "Europe/Berlin"
