apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-s3-config
    namespace: docs
type: Opaque
stringData:
    s3.json: ENC[AES256_GCM,data:xt93sAO/+7lNrU8gnkOfD8Pny4VUQw/r2rCpC5AsDJ3n+3NYkSLsfWZsKXIIMuJq5tZrA4WnOK5AlQR2HzM2O1MQCaCGDhGFZwFWF8GH0ADfNsqfjppN7vQ1bMvo2KjljpHYdLoLHvMh6lwwr5fa8P22zHsFWBm43fpegLV23jhaC33B5YMqaq/o5p4+EoKJ/Brc9TfZYFBq0ExDzOWsGPkBshZTekRWGqPQcZWeEtMGvQvyv7ANxjniu0i4zMZcXZNprEU246T1eh7jl04qRBeRN63TKAabQ2TJAaW6SgGL4Sn20ogFFmjYm3gWvp5MnldVHaUIv5r7uikaTNEsTqPVWrns2PyDocbIYjWyuVHyebCn,iv:HGnFscRLaIXJF04fNxnXRf40wxFewZLHldLfxjItT6w=,tag:xdlFqIMrTAmnybpwz6bHdA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvYys1MVdmU2xUMmNEQzlB
            eFlqR01iN040a0hKR3hocHlwaldzTlc3N0ZFCnFPOTlmQ3RGWVdjYXhZVFVzU3BO
            NGk4SzZBbkVURFRiR3RxQVhnUG9rNzgKLS0tIG9KdzRMd3A0ay9yNDNPNlFWak55
            QTVmaTFQMkdFYTV2bWlXeTZFZEtSdkEKXTXZe4ereKGXp/IJRN86RxsGfBSdkq9/
            RwYrGreAIZlyGlyenHRFLXL11JSVZTL/LrKbjrJt1EYppAE86wL0/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-31T10:35:34Z"
    mac: ENC[AES256_GCM,data:5aaGyIuavqC7HzsfY+zuiLE5FNNd77R+N7vVmSdMLA10Mie6JQ66ndcLRwtWShF5P95CJlT8OGh/cOt2RJUN1dXQedtmUOVdifkIOSA86HQfTh16Z6snH9kAElcT++p5+FVqz+VYHAWzu2zvf5ZlOIWE1K05/k2y1FLubNEWPQM=,iv:XZNeOPL1CK6NPDR0ZRn6g/35f8ZVpvPcesvZ/GlCnBY=,tag:nm/EQ9ZjxTNaCi8g3otZ3w==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
