apiVersion: v1
kind: Secret
metadata:
    name: docs-secrets
    namespace: docs
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:61EQCQ==,iv:dXNhNs8cxB47AGCWnO10BB0HLJESsHiNb+xm4KDZYuE=,tag:0765vIq9KqHXNaPxlCrKLQ==,type:str]
    password: ENC[AES256_GCM,data:79Uns1iymBufCND/ajn9E/4BJ36VT731+5L9+lr2GQA=,iv:pC60Wd3H62AhXMdyUyq36ShMfj5K0lvpsRtMW91IZ9w=,tag:K5ePiT9kLgymRgOXzsmfBw==,type:str]
    dbname: ENC[AES256_GCM,data:GjHR3g==,iv:BYXxqvlXGeH0hcciofpn9QjADIsmUQYBIhVEvqUutLY=,tag:npbsCrmANOPS53mJtdEq5w==,type:str]
    DJANGO_SECRET_KEY: ENC[AES256_GCM,data:5ONQyiI6LVsskEct0g/18fcsWmlWogCo9E2VDpQ5IUkRJMB/l6smXkR051kgzOZs97h5+sYf+F/48O0cZ3NuCw==,iv:upuo57IWCxkXMunM8jWD8KJ5qa5OEolsXgm0Gkufpvw=,tag:UY6yaYoCS2KMb/45WUTnOA==,type:str]
    OIDC_RP_CLIENT_ID: ENC[AES256_GCM,data:Uht6Kpoao7ULWWgesWBV52SGxVE9ZHNgsPp30P1fHvMltCIU7lc+jQ==,iv:s5PRugoF0bpN12BIg1ybr/R3AMYMPhOVKFfhzsNmWRY=,tag:MKNPS0u9T7qWIbvfq79FUw==,type:str]
    OIDC_RP_CLIENT_SECRET: ENC[AES256_GCM,data:hY15XK53Gsbtcq1Uy39p4WRIgSRspnbAjme5qEym33G+DydjZ9x4ecLdeFoOifYivTULFr2V18H+yd8JEuYA7qDuELHrKkUMhYlQGUOJAQjRM6iOXR8U/2gf6AV7vVP/+Aru6LTh4jG5M/zAVtoscLpD7VFhZtymtdqGsQrF3Qk=,iv:yEdhrHq7reMQnyDmS3d+xU1/Fk79UMJ/jS433u4c3zE=,tag:DKEVzav0rfDAHwNwgisojQ==,type:str]
    Y_PROVIDER_API_KEY: ENC[AES256_GCM,data:TtWIZQ24HqrJF7CdOqfmEy2D5rYy3/rtKKxmhms8auauxLNRkTKCQnBPLsK1KTphsy6C5KB/AhHF9ms2JGsztA==,iv:Lp7s3ike/xrffxYpSKiOgbyh1TkjQXIzsJ08CS5PbLM=,tag:FKLp/ZzTMzmYCxNTHkT2Ew==,type:str]
    COLLABORATION_SERVER_SECRET: ENC[AES256_GCM,data:t1r6smkIwcDISON287pFTKD1te6XgPmQXsn0iTpw8TVTv+EbCntB1Mqz8miBAui/9QI35hYDHmkEbylYqWVy+g==,iv:YTZVnIXtUNkKyzgmpmoGQZ2cj5eQ8zhGGrawldKxKI4=,tag:G+SwFfbZ86O4ght60KZcvw==,type:str]
    SEAWEEDFS_S3_ACCESS_KEY: ENC[AES256_GCM,data:4T6o2w==,iv:igbVnZXlVYx2SPIN6oMvdby0AIlmm+enG1tDweBhF7M=,tag:piCKS+0Y53RvJwUQJ6s8vQ==,type:str]
    SEAWEEDFS_S3_SECRET_KEY: ENC[AES256_GCM,data:EXnjvejjFd5/skQ4PaCI5LXhpZgd40dKvthPNZA6hVDi5kb4oGXMNJJd0qs=,iv:bryjhGD7Nk+FoM9TkJZt/eeaebD/FMyqzkXkLiW8uWw=,tag:cspm+yICg7bQjwcO+oX9/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nl4pnuny2pjg3ejfk9vrx0y4ssmna36xlw3wqmzv55ku38psdylsp2t2yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTekdxNkYwN01QeFZzOExj
            by9FS0xxcjA5YnNTTjQvZExsemljQnFWM0RrCnhEZjVDc3ZWSk4zemlkRFBvSm1p
            S1BpVU1YVitqeXdmdXpaZ3VQOVh6SmMKLS0tICtWak1WNHlET244ZVpsaFo3algw
            MEowOWFsQlUzdWNSQnZOd0Vna0F1bG8KEkA4OokL8wooWC4pLbi45i6Nw08ppmNm
            2WvWATBSi982cg1E8dpp5/D5z9nrJsbyP2b8U0VxfsgTPB/tu5cudA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-31T10:33:43Z"
    mac: ENC[AES256_GCM,data:Gb9cYFEq+sOSFpJWluEoMNe71TUUmHCd/AZigwhIn37+p4X5uuSVfKQBH80dilrIMdUJ/ZbjmfK94WsogvTuu/SZSKIuVB7N3nn2GBuJWb9kaYTtpap1s6vSHm5qfPgR8Uz/Til3UYn64WH7c1SUuM7Hp8CFVx8ZExmSMZ3ZSjs=,iv:0lPsYv/O8sSe0cn4HSR/SKDrq9BT20JbCymStFemI1A=,tag:3TuNbZgzLnT+lZBqxmsawA==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.9.0
